/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "Foundation/NSObject.h"

typedef struct {
    long long value;
    int timescale;
    long long epoch;
    unsigned int flags;
} AVTime;

@interface AVController : NSObject
{
    struct AVControllerPrivate *_priv;
}

+ (id)compatibleAudioRouteForRoute:(id)fp8;
+ (void)setEnableNetworkMode:(BOOL)fp8;
+ (BOOL)isSupportedMimeType:(id)fp8;
+ (BOOL)isSupportedFileExtension:(id)fp8;
+ (BOOL)isNetworkSupportedPath:(id)fp8;
+ (id)avController;
+ (id)avControllerWithQueue:(id)fp8 error:(id *)fp12;
- (id)initWithError:(id *)fp8;
- (void)setAVItemClass:(Class)fp8;
- (id)init;
- (void)dealloc;
- (struct AVControllerPrivate *)privateStorage;
- (BOOL)isNewImageAvailableForTime:(const AVTime *)fp8 willNeverBeAvailable:(char *)fp12;
- (long)copyImageForTime:(struct __CVBuffer **)fp8 time:(const AVTime *)fp12;
- (void)scheduleQueueSpaceCheck;
- (void)checkQueueSpace;
- (id)queue;
- (void)feederRangeWasInserted:(id)fp8;
- (void)feederRangeWasRemoved:(id)fp8;
- (void)feederInvalidatedWithCurrentItemMoved:(id)fp8;
- (void)setQueueFeeder:(id)fp8 withIndex:(int)fp12;
- (void)setQueueFeeder:(id)fp8;
- (id)queueFeeder;
- (BOOL)setRepeatMode:(int)fp8;
- (int)repeatMode;
- (BOOL)havePlayedCurrentItem;
- (void)continueAfterRepeatGap;
- (void)cancelContinueAfterRepeatGap;
- (BOOL)beginRepeatGap;
- (BOOL)play:(id *)fp8;
- (void)pause;
- (void)dequeueFirstItem;
- (unsigned int)indexOfCurrentQueueFeederItem;
- (BOOL)setIndexOfCurrentQueueFeederItem:(unsigned int)fp8 error:(id *)fp12;
- (id)addNextFeederItemToQueue;
- (BOOL)playNextItem:(id *)fp8;
- (float)rate;
- (BOOL)shouldBeginPlayingItem:(id)fp8 error:(id *)fp12;
- (BOOL)setRate:(float)fp8 error:(id *)fp12;
- (BOOL)resumePlayback:(double)fp8 error:(id *)fp16;
- (id)errorWithDescription:(id)fp8 code:(long)fp12;
- (void)makeError:(id *)fp8 withDescription:(id)fp12 code:(long)fp16;
- (BOOL)beginInterruption:(id *)fp8;
- (BOOL)activate:(id *)fp8;
- (void)endInterruptionWithStatus:(id)fp8;
- (float)volume;
- (void)setVolume:(float)fp8;
- (double)currentTime;
- (void)setCurrentTime:(double)fp8;
- (void)setCurrentTime:(double)fp8 options:(int)fp16;
- (BOOL)muted;
- (void)setMuted:(BOOL)fp8;
- (void)setEQPreset:(int)fp8;
- (int)eqPreset;
- (struct OpaqueFigVisualContext *)visualContext;
- (void)setVisualContext:(struct OpaqueFigVisualContext *)fp8;
- (id)outputQTESFilePath;
- (void)setOutputQTESFilePath:(id)fp8;
- (id)lkLayer;
- (void)setLayer:(id)fp8;
- (id)captionLayer;
- (BOOL)shouldDisplayClosedCaptions;
- (void)setShouldDisplayClosedCaptions:(BOOL)fp8;
- (void)setSubtitleRecipient:(id)fp8;
- (id)attributeForKey:(id)fp8;
- (BOOL)setAttribute:(id)fp8 forKey:(id)fp12 error:(id *)fp16;
- (long)updateActionAtEnd;
- (BOOL)okToNotifyFromThisThread;
- (void)fmpUserVolumeDidChange:(id)fp8;
- (void)fmpRateDidChange;
- (void)rateDidChangeToRate:(float)fp8;
- (void)repeatModeHasChanged:(int)fp8;
- (void)currentItemWillChangeToItem:(id)fp8 oldItemCurrentTime:(double)fp12;
- (void)currentItemHasChanged:(id)fp8;
- (void)itemHasFinishedPlayingNotification:(id)fp8;
- (id)delegate;
- (void)setDelegate:(id)fp8;
- (void)safeClosedCaptionCommandPosted:(void *)fp8;
- (void)safeSubtitleCommandPosted:(void *)fp8;
- (id)initWithQueue:(id)fp8 error:(id *)fp12;
- (BOOL)isValid;
- (id)initWithQueue:(id)fp8 fmpType:(unsigned int)fp12 error:(id *)fp16;
- (void)maybeDumpPerformanceDictionary:(struct OpaqueFigPlaybackItem *)fp8;
- (void)setQueue:(id)fp8;
- (void)updateTimeMarkerObservations;
- (void)scheduleUpdateTimeMarkerObservations;
- (void)registerTimeMarkerObserver:(id)fp8 forItem:(id)fp12 times:(id)fp16 context:(id)fp20;
- (void)removeObserver:(id)fp8 fromTMOArray:(id)fp12;
- (void)unregisterTimeMarkerObserver:(id)fp8 forItem:(id)fp12;
- (BOOL)isCurrentItemReady;
- (void)makeCurrentItemReady;
- (id)currentItem;
- (struct OpaqueFigPlaybackItem *)currentFPItem;
- (void)ensurePlaybackQueueImmed;
- (struct OpaqueFigPlaybackItem *)createItemWithURL:(id)fp8 flags:(unsigned long)fp12 error:(int *)fp16;
- (void)avPlaybackQueueCurrentItemChangedNotification:(id)fp8;
- (void)fpItemNotification:(id)fp8 sender:(id)fp12;

@end

