/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@interface AVFileProcessor : NSObject
{
}

+ (id)fileProcessor;
- (id)processPurchasedItem:(id)fp8 withAttributes:(id)fp12;
- (id)processPurchasedItem:(id)fp8 withAttributes:(id)fp12 resultInfo:(id *)fp16;
- (id)rentalInfo:(id)fp8;

@end

