/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@interface AVRecorder : NSObject
{
    struct AVRecorderPrivate *_priv;
}

- (id)init;
- (void)dealloc;
- (void)setFilePath:(id)fp8;
- (id)filePath;
- (void)setAttribute:(id)fp8 forKey:(id)fp12;
- (id)attributeForKey:(id)fp8;
- (BOOL)activate:(id *)fp8;
- (BOOL)start;
- (void)stop;
- (BOOL)isRecording;
- (BOOL)isActive;
- (void)deactivate;
- (float)micVolume;
- (void)setMicVolume:(float)fp8;
- (long long)recordedFileSizeInBytes;
- (double)recordedDuration;
- (unsigned int)audioNumDeviceChannels;
- (BOOL)audioCurrentAverageVolumeLevels:(float *)fp8 andPeakVolumeLevels:(float *)fp12;
- (BOOL)audioCurrentAverageDecibelLevels:(float *)fp8 andPeakDecibelLevels:(float *)fp12;

@end

