/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@interface NSObject (NSObject_AVShared)
- (void)postNotificationWithDescription:(id)fp8;
- (void)allowSafePerformSelector;
- (void)disallowSafePerformSelector;
- (BOOL)okToNotifyFromThisThread;
- (void)fromNotifySafeThreadPerformSelector:(SEL)fp8 withObject:(id)fp12;
- (void)fromNotifySafeThreadPostNotificationName:(id)fp8 object:(id)fp12 userInfo:(id)fp16;
- (void)fromMainThreadPostNotificationName:(id)fp8 object:(id)fp12 userInfo:(id)fp16;
@end

