/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <TelephonyUI/TPBottomBar.h>

@class TPPushButton;

@interface TPBottomButtonBar : TPBottomBar
{
    id _delegate;
    TPPushButton *_button;
}

- (id)initForIncomingCallWaitingWithFrame:(struct CGRect)fp8;
- (id)initForEndCallWithFrame:(struct CGRect)fp8;
- (id)initForTTYWithFrame:(struct CGRect)fp8;
- (void)dealloc;
- (void)setButton:(id)fp8;
- (id)button;

#if 1 // iOS 5.0
- (void)setButton:(id)fp8 andStyle:(int)style;
#endif

@end

