/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <TelephonyUI/TPBottomButtonBar.h>

@class TPPushButton;

@interface TPBottomDualButtonBar : TPBottomButtonBar
{
    TPPushButton *_button2;
    unsigned int _drawSeparator:1;
}

- (id)initWithFrame:(struct CGRect)fp8;
- (id)initForIncomingCallWithFrame:(struct CGRect)fp8;
- (id)initForCallFailureWithFrame:(struct CGRect)fp8;
- (id)initForEmergencyCallWithFrame:(struct CGRect)fp8;
- (void)dealloc;
- (float)_buttonWidth;
- (void)_updateButtonSettings:(id)fp8;
- (void)setButton:(id)fp8;
- (void)setButton2:(id)fp8;
- (id)button2;
- (void)setDrawsSeparateWells:(BOOL)fp8;
- (void)drawRect:(struct CGRect)fp8;

@end

