/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIView.h"

@class NSString, NSTimer, UIFont;

@interface TPLockTextView : UIView
{
    NSString *_label;
    struct CGImage *_textCache;
    char *_textData;
    NSTimer *_maskTimer;
    double _maskStartTime;
    UIFont *_labelFont;
    float _fps;
}

- (void)dealloc;
- (void)_cacheLabel:(id)fp8 size:(struct CGSize)fp12;
- (id)initWithLabel:(id)fp8 fontSize:(float)fp12;
- (id)label;
- (void)startAnimation;
- (void)stopAnimation;
- (void)setFPS:(float)fp8;
- (BOOL)isAnimating;
- (void)drawRect:(struct CGRect)fp8;
- (void)movedFromWindow:(id)fp8;

@end

