/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIControl.h"

@interface TPPhonePad : UIControl
{
    int _downKey;
    id _delegate;
    BOOL _playsSounds;
    float _topHeight;
    float _midHeight;
    float _bottomHeight;
    float _leftWidth;
    float _midWidth;
    float _rightWidth;
    struct __CFSet *_inflightSounds;
    struct __CFDictionary *_keyToButtonMap;
    unsigned int _incompleteSounds;
    unsigned int _delegateSoundCallbacks:1;
    unsigned int _soundsActivated:1;
}

+ (BOOL)shouldStringAutoDial:(id)fp8 givenLastChar:(BOOL)fp12;
+ (BOOL)launchFieldTestIfNeeded:(id)fp8;
+ (void)_delayedDeactivate;
- (id)initWithFrame:(struct CGRect)fp8;
- (void)dealloc;
- (void)_activateSounds:(BOOL)fp8;
- (void)removeFromSuperview;
- (void)_appSuspended;
- (void)_appResumed;
- (void)movedFromWindow:(id)fp8;
- (void)movedToWindow:(id)fp8;
- (void)setDelegate:(id)fp8;
- (void)setPlaysSounds:(BOOL)fp8;
- (void)setButton:(id)fp8 forKeyAtIndex:(int)fp12;
- (void)setNeedsDisplayForKey:(int)fp8;
- (id)_pressedImage;
- (id)_keypadImage;
- (float)_yFudge;
- (void)drawRect:(struct CGRect)fp8;
- (BOOL)pointMostlyInside:(struct CGPoint)fp8 forEvent:(struct __GSEvent *)fp16;
- (id)hitTest:(struct CGPoint)fp8 forEvent:(struct __GSEvent *)fp16;
- (void)setHighlighted:(BOOL)fp8;
- (BOOL)cancelMouseTracking;
- (void)_handleKey:(id)fp8 forEvent:(struct __GSEvent *)fp12;
- (void)_handleKeyPressAndHold:(id)fp8;
- (int)_keyForPoint:(struct CGPoint)fp8;
- (struct CGRect)_rectForKey:(int)fp8;
- (void)_notifySoundCompletionIfNecessary:(unsigned long)fp8;
- (void)_playSoundForKey:(int)fp8;
- (void)_stopSoundForKey:(int)fp8;
- (void)_stopAllSoundsForcingCallbacks:(BOOL)fp8;

@end

