/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <ChatKit/CKFixedImageMediaObject.h>

@interface CKAnimatedImageMediaObject : CKFixedImageMediaObject
{
}

+ (id)mimeTypesToFileExtensions;
- (id)newPreview:(int)fp8 highlight:(BOOL)fp12;
- (Class)balloonPreviewClassWithPreviewData:(id)fp8;
- (float)balloonHeightWithPreviewData:(id)fp8;
- (void)configureBalloon:(id)fp8 withPreviewData:(id)fp12;
- (BOOL)_imageHasAnimation;

@end

