/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <ChatKit/CKAVMediaObject.h>

@class NSDictionary, NSString;

@interface CKAudioMediaObject : CKAVMediaObject
{
    NSDictionary *_transcodeOptions;
    NSString *_transcodePath;
}

+ (id)mimeTypesToFileExtensions;
- (void)dealloc;
- (BOOL)shouldTranscodeForMMS;
- (int)mediaType;
- (unsigned long long)sizeInBytes;
- (id)optionsForMedia;
- (void)prepareForTranscode;
- (id)transcodePath;
- (id)transcodedFilename;
- (id)transcodeMimeType;
- (id)transcodedPathExtension;
- (double)transcodeStartTime;
- (double)transcodeEndTime;
- (double)transcodeDuration;
- (id)effectiveExportedFilename;
- (id)previewTitle;
- (id)filenameForMedia;

@end

