/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIViewController.h"

#import "MFMailComposeViewControllerDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class CKConversationList, CKService, CKTranscriptController, MFMailComposeViewController, UINavigationController, UITableView, UIToolbar;

@interface CKConversationListController : UIViewController <UITableViewDataSource, UITableViewDelegate, MFMailComposeViewControllerDelegate>
{
    UINavigationController *_navigationController;
    UITableView *_table;
    CKTranscriptController *_transcriptController;
    UIToolbar *_buttonBar;
    unsigned int _willBeMarkedReadCount;
    unsigned int _dirty:1;
    unsigned int _isVisible:1;
    unsigned int _isUpdatingDisabled:1;
    CKService *_currentService;
    CKConversationList *_conversationList;
    MFMailComposeViewController *_mailComposeController;
}

- (void)setConversationList:(id)fp8;
- (id)initWithNavigationController:(id)fp8 service:(id)fp12;
- (void)dealloc;
- (id)transcriptController;
- (void)_conversationWasMarkedAsRead:(id)fp8;
- (void)_conversationDidChange:(id)fp8;
- (void)_conversationMessageWasSent:(id)fp8;
- (void)_groupsChanged:(id)fp8;
- (void)updateTitle;
- (void)updateNavigationItems;
- (void)conversationWillBeMarkedRead:(id)fp8;
- (void)noteUnreadCountsChanged;
- (void)significantTimeChange;
- (void)updateConversationList;
- (void)disableConversationListUpdates;
- (void)enableConversationListUpdates;
- (void)noteConversationListChanged;
- (void)showMessagesForAddress:(id)fp8 animate:(BOOL)fp12;
- (void)showNewMessageCompositionPanel:(BOOL)fp8;
- (void)showConversation:(id)fp8 animate:(BOOL)fp12;
- (BOOL)resumeToConversation:(id)fp8 unsentComposition:(id)fp12;
- (void)show:(BOOL)fp8;
- (BOOL)showUnreadConversations;
- (BOOL)isShowingTranscriptWithUnsentText;
- (void)loadView;
- (void)viewWillAppear:(BOOL)fp8;
- (void)viewDidAppear:(BOOL)fp8;
- (void)viewDidDisappear:(BOOL)fp8;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (void)_getRotationContentSettings:(CDAnonymousStruct1 *)fp8;
- (void)setEditing:(BOOL)fp8 animated:(BOOL)fp12;
- (void)composeButtonClicked:(id)fp8;
- (int)selectedIndex;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (void)tableView:(id)fp8 willBeginEditingRowAtIndexPath:(id)fp12;
- (void)tableView:(id)fp8 didEndEditingRowAtIndexPath:(id)fp12;
- (void)deleteButtonPressedForIndexPath:(id)fp8;
- (void)tableView:(id)fp8 commitEditingStyle:(int)fp12 forRowAtIndexPath:(id)fp16;
- (void)_displaySMSDatabaseFullWarning;
- (void)_showMailComposeSheet;
- (void)showMailComposeSheetForAutosavedMessage;
- (void)autosaveMailComposition;
- (void)showMailComposeSheetForAddress:(id)fp8;
- (void)mailComposeController:(id)fp8 didFinishWithResult:(int)fp12 error:(id)fp16;
- (void)didCancelComposition:(id)fp8;
- (id)conversationList;

@end

