/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSObject<CKContentEntryBridgeClient>;

@interface CKContentEntryBridge : NSObject
{
    NSObject<CKContentEntryBridgeClient> *_entryView;
}

+ (id)newContentEntryBridge;
- (void)dealloc;
- (void)setMessageComposition:(id)fp8;
- (id)messageComposition;
- (void)setMessageParts:(id)fp8;
- (id)messageParts;
- (id)attachments;
- (void)insertMessagePart:(id)fp8;
- (BOOL)hasContent;
- (id)newContentViewWithFrame:(struct CGRect)fp8;
- (id)supportedPasteboardTypesInTextContentView:(id)fp8;
- (id)documentFragmentForPasteboardItemAtIndex:(int)fp8 inTextContentView:(id)fp12;
- (id)contentEntryView;
- (void)setContentEntryView:(id)fp8;

@end

