/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIAnimation.h"

@interface CKContentOffsetAnimation : UIAnimation
{
    struct CGPoint _startContentOffset;
    struct CGPoint _endContentOffset;
}

- (void)setProgress:(float)fp8;
- (void)setStartContentOffset:(struct CGPoint)fp8;
- (void)setEndContentOffset:(struct CGPoint)fp8;
- (struct CGPoint)endContentOffset;

@end

