/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UITableViewCell.h"

@class CKConversation, CKSummaryLabel, UIDateLabel, UIImageView, UILabel;

@interface CKConversationListCell : UITableViewCell
{
    CKConversation *_conversation;
    UIDateLabel *_dateLabel;
    CKSummaryLabel *_summaryLabel;
    CKSummaryLabel *_backupSummaryLabel;
    UIImageView *_unreadIndicatorImageView;
    UILabel *_fromLabel;
    UIImageView *_groupImageView;
}

+ (id)identifier;
+ (float)cellHeight;
- (id)initWithFrame:(struct CGRect)fp8 conversation:(id)fp24;
- (void)setConversation:(id)fp8;
- (void)dealloc;
- (void)clearText;
- (void)updateContents;
- (void)_createBackupSummaryLabel;
- (void)setHighlighted:(BOOL)fp8 animated:(BOOL)fp12;
- (void)willTransitionToState:(unsigned int)fp8;
- (void)didTransitionToState:(unsigned int)fp8;
- (void)layoutSubviews;

@end

