/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIScrollView.h"

#import "CKContentEntryBridgeClient-Protocol.h"
#import "CKEntryField-Protocol.h"
#import "UITextContentViewDelegate-Protocol.h"

@class CKContentEntryBridge, CKTextContentView, NSMutableArray, UIView;

@interface CKContentEntryView : UIScrollView <CKEntryField, UITextContentViewDelegate, CKContentEntryBridgeClient>
{
    NSMutableArray *_contentViews;
    CKTextContentView *_subjectView;
    CKTextContentView *_activeView;
    UIView *_subjectLine;
    CKContentEntryBridge *_bridge;
    unsigned int _showsSubject:1;
    unsigned int _viewsLoaded:1;
    id _entryFieldDelegate;
    BOOL _needsScrollToVisible;
}

- (id)initWithFrame:(struct CGRect)fp8;
- (void)dealloc;
- (void)removeFromSuperview;
- (void)setContentOffset:(struct CGPoint)fp8;
- (void)_scrollViewAnimationEnded;
- (void)updateCandidateDisplay;
- (void)setFrame:(struct CGRect)fp8;
- (void)scrollSelectionToVisible:(BOOL)fp8;
- (struct CGRect)contentEntryFrame:(BOOL)fp8;
- (BOOL)showsSubject;
- (void)setShowsSubject:(BOOL)fp8;
- (void)showSubjectLinesAndDefaultText:(BOOL)fp8;
- (void)tapGesture:(id)fp8;
- (void)resetKeyboardDelegate:(id)fp8;
- (BOOL)textContentView:(id)fp8 shouldChangeTextInRange:(struct _NSRange)fp12 replacementText:(id)fp20;
- (void)textContentViewDidChange:(id)fp8;
- (BOOL)textContentViewShouldBeginEditing:(id)fp8;
- (void)textContentViewDidBeginEditing:(id)fp8;
- (BOOL)textContentViewShouldEndEditing:(id)fp8;
- (BOOL)textContentView:(id)fp8 shouldChangeSizeForContentSize:(struct CGSize)fp12;
- (void)textContentView:(id)fp8 didChangeSize:(struct CGSize)fp12;
- (id)supportedPasteboardTypesInTextContentView:(id)fp8;
- (id)documentFragmentForPasteboardItemAtIndex:(int)fp8 inTextContentView:(id)fp12;
- (void)attachmentsDidChange;
- (void)reflowContent;
- (void)setContentHidden:(BOOL)fp8 subjectHidden:(BOOL)fp12;
- (void)setEntryFieldDelegate:(id)fp8;
- (id)entryFieldDelegate;
- (void)clearMessage;
- (BOOL)hasContent;
- (void)setMessageComposition:(id)fp8;
- (id)messageComposition;
- (void)setMessageParts:(id)fp8;
- (id)messageParts;
- (void)insertMessagePart:(id)fp8;
- (void)moveCursorToEnd;
- (void)setCursorPosition:(int)fp8;
- (int)cursorPosition;
- (int)lastCursorPosition;
- (void)saveCursorPosition;
- (void)restoreCursorPosition;
- (void)makeActive;
- (BOOL)isActive;
- (void)disableEditing;
- (void)setIgnoreAnimations:(BOOL)fp8;
- (id)subject;
- (void)setSubject:(id)fp8;
- (void)loadSubviews;
- (id)attachments;
- (void)setContentOffset:(struct CGPoint)fp8 animated:(BOOL)fp16;
- (void)_addContentView:(id)fp8;
- (void)_reloadEntryViewsIfLoaded;
- (void)_removeContentView:(id)fp8;
- (void)_loadEntryViews;
- (void)_adjustAllContent;
- (void)_setupGestureRecognizers;
- (BOOL)canPasteObject:(id)fp8;
- (id)contentViews;

@end

