/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class CKMessage, CKService, NSArray, NSMutableArray, NSMutableDictionary, NSString;

@interface CKConversation : NSObject
{
    NSMutableArray *_messages;
    NSString *_name;
    int _unreadCount;
    NSMutableArray *_failedMessages;
    NSMutableArray *_pendingMessages;
    CKMessage *_latestIncomingMessage;
    BOOL _hasPlaceholder;
    CKMessage *_placeholderMessage;
    NSArray *_names;
    NSArray *_recipients;
    int _groupID;
    NSMutableDictionary *_groupMessages;
    NSMutableArray *_queuedGroupMessages;
    int _groupAddStack;
    BOOL _moreMessagesToLoad;
    int _limitToLoad;
    CKService *_service;
    BOOL _updatesDisabled;
}

- (void)setUnsentComposition:(id)fp8;
- (id)unsentComposition;
- (int)groupID;
- (id)initWithGroupID:(int)fp8 service:(id)fp12;
- (id)recipient;
- (void)dealloc;
- (void)setName:(id)fp8;
- (id)name;
- (id)latestMessage;
- (id)date;
- (void)setRecipients:(id)fp8;
- (id)recipients;
- (void)_recalculateUnreadCounts;
- (void)removeMessage:(id)fp8;
- (BOOL)isEmpty;
- (BOOL)isPlaceholder;
- (id)placeholderMessage;
- (void)_setPlaceholderMessage:(id)fp8;
- (void)updateMessage:(id)fp8;
- (int)addMessage:(id)fp8 incrementUnreadCount:(BOOL)fp12;
- (void)_beginGroupAdd;
- (void)_addGroupMessage:(id)fp8;
- (int)_endGroupAdd:(BOOL)fp8;
- (void)resetPendingMessages;
- (void)markAllMessagesAsRead;
- (void)removeAllMessages;
- (void)_deleteAllMessagesAndRemoveGroup:(BOOL)fp8;
- (void)deleteAllMessages;
- (void)deleteAllMessagesAndRemoveGroup;
- (BOOL)moreMessagesToLoad;
- (void)_postUpdate;
- (void)_reloadMessagesToLimit;
- (void)loadAllMessages;
- (void)loadMoreMessages;
- (id)pendingMessages;
- (id)messages;
- (id)latestIncomingMessage;
- (void)setUnreadCount:(int)fp8;
- (int)unreadCount;
- (BOOL)hasUnreadMessages;
- (id)_trulyLatestMessage;
- (int)compareByDateDescending:(id)fp8;
- (void *)abRecord;
- (int)propertyType;
- (int)identifier;
- (void)resetCaches;
- (id)groupMessageWithAssociationID:(int)fp8;
- (void)pendingMessagesTotalMessages:(int *)fp8 percentComplete:(float *)fp12;
- (id)failedMessages;
- (BOOL)updatesDisabled;
- (void)setUpdatesDisabled:(BOOL)fp8;
- (id)service;

@end

