/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class CKService;

@interface CKEntity : NSObject
{
    int _addressBookUID;
    int _identifier;
    int _propertyType;
    BOOL _foundABNameForSender;
    BOOL _senderIsVoicemail;
    void *_abRecord;
    CKService *_service;
}

- (void)resetCaches;
- (id)_initWithService:(id)fp8;
- (void)dealloc;
- (id)rawAddress;
- (id)name;
- (BOOL)senderIsVoicemail;
- (BOOL)foundABNameForSender;
- (int)propertyType;
- (void)setPropertyType:(int)fp8;
- (void *)abRecord;
- (int)identifier;
- (void)setIdentifier:(int)fp8;
- (int)addressBookUID;
- (void)setAddressBookUID:(int)fp8;
- (id)service;

@end

