/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

@protocol CKEntryField
- (void)setEntryFieldDelegate:(id)fp8;
- (id)entryFieldDelegate;
- (void)clearMessage;
- (BOOL)hasContent;
- (id)attachments;
- (void)setMessageComposition:(id)fp8;
- (id)messageComposition;
- (void)setMessageParts:(id)fp8;
- (id)messageParts;
- (void)insertMessagePart:(id)fp8;
- (struct CGPoint)contentOffset;
- (struct UIEdgeInsets)contentInset;
- (void)moveCursorToEnd;
- (void)setCursorPosition:(int)fp8;
- (void)reflowContent;
- (int)cursorPosition;
- (int)lastCursorPosition;
- (void)saveCursorPosition;
- (void)restoreCursorPosition;
- (void)makeActive;
- (BOOL)isActive;
- (void)disableEditing;
- (void)setIgnoreAnimations:(BOOL)fp8;
- (id)subject;
- (void)setSubject:(id)fp8;
- (void)setContentHidden:(BOOL)fp8 subjectHidden:(BOOL)fp12;
- (void)loadSubviews;
@end

