/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UITableViewCell.h"

@class CKEntity, UILabel;

@interface CKEntityView : UITableViewCell
{
    UILabel *_label;
    CKEntity *_entity;
}

+ (float)defaultHeight;
- (id)initWithStyle:(int)fp8 reuseIdentifier:(id)fp12;
- (void)dealloc;
- (void)setEntity:(id)fp8;
- (void)sizeToFit;

@end

