/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <ChatKit/CKMessage.h>

@interface CKLoopbackMessage : CKMessage
{
    BOOL _isOutgoing;
    BOOL _isRead;
    BOOL _isPlaceholder;
}

- (void)dealloc;
- (id)initWithConversation:(id)fp8 text:(id)fp12 date:(id)fp16;
- (BOOL)isEqual:(id)fp8;
- (void)markAsRead;
- (BOOL)hasBeenRead;
- (int)sentCount;
- (void)markAsSent;
- (void)setOutgoing:(BOOL)fp8;
- (id)initPlaceholderConversation:(id)fp8 date:(id)fp12;
- (id)initWithConversation:(id)fp8 text:(id)fp12;
- (BOOL)isOutgoing;

@end

