/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class CKMessage;

@interface CKMessagePart : NSObject
{
    unsigned int _height;
    unsigned int _flags;
    CKMessage *_parentMessage;
}

+ (id)_assembleTextPartFromRange:(id)fp8;
+ (id)_newPartsForNode:(id)fp8 resources:(id)fp12;
+ (id)copyDetachedMessageParts:(id)fp8;
+ (id)copyMessagePartsFromComposition:(id)fp8;
+ (id)_newPartForPartRepresentation:(id)fp8 previewPartRepresentation:(id)fp12;
+ (id)copyMessagePartsFromArrayRepresentation:(id)fp8;
+ (id)copyDeletedPart;
+ (id)copyUnknownPart;
- (id)mediaObject;
- (id)previewText;
- (BOOL)isDisplayable;
- (id)text;
- (id)imageData;
- (id)image;
- (id)highlightData;
- (id)previewImage;
- (id)composeImage;
- (id)imageFilename;
- (id)detachedCopy;
- (void)getUIHeight:(unsigned int *)fp8 flags:(unsigned int *)fp12;
- (int)type;
- (void)setUIHeight:(unsigned long)fp8 flags:(unsigned long)fp12;
- (void)dealloc;
- (id)previewData;
- (id)composeData;
- (void)copyToPasteboard;
- (id)parentMessage;
- (void)setParentMessage:(id)fp8;

@end

