/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableDictionary;

@interface CKMediaObjectManager : NSObject
{
    NSMutableDictionary *_mediaObjectDict;
}

+ (id)sharedInstance;
- (void)_registerAllMediaTypes;
- (id)newMediaObjectForFilename:(id)fp8 mimeType:(id)fp12 exportedFilename:(id)fp16;
- (id)newMediaObjectForData:(id)fp8 mimeType:(id)fp12 exportedFilename:(id)fp16;
- (Class)mediaObjectClassForMIMEType:(id)fp8;
- (void)dealloc;

@end

