/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <ChatKit/CKMessageComposition.h>

@class CKMessage;

@interface CKMessageLinkedComposition : CKMessageComposition
{
    CKMessage *_message;
}

- (BOOL)isTextOnly;
- (id)textString;
- (id)markupString;
- (id)subject;
- (id)resources;
- (void)dealloc;
- (id)message;
- (void)setMessage:(id)fp8;

@end

