/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIView.h"

#import "CKOverlayViewProtocol-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class ComposeRecipientView, NSArray, SearchShadowView, UIScroller, UITableView;

@interface CKRecipientSelectionView : UIView <UITableViewDataSource, UITableViewDelegate, CKOverlayViewProtocol>
{
    ComposeRecipientView *_toField;
    UIScroller *_toFieldScrollingView;
    NSArray *_searchResults;
    UITableView *_searchResultsTable;
    SearchShadowView *_shadowView;
    BOOL _showingSearchField;
    id _delegate;
}

- (id)initWithFrame:(struct CGRect)fp8 ABProperties:(id)fp24;
- (void)dealloc;
- (BOOL)hasText;
- (id)recipients;
- (void)reset;
- (id)toField;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (void)composeRecipientView:(id)fp8 textDidChange:(id)fp12;
- (void)composeRecipientView:(id)fp8 requestDeleteRecipientAtIndex:(int)fp12;
- (void)composeRecipientViewDidFinishEnteringRecipient:(id)fp8;
- (id)composeRecipientView:(id)fp8 composeRecipientForAddress:(id)fp12;
- (id)composeRecipientView:(id)fp8 composeRecipientForRecord:(void *)fp12 property:(int)fp16 identifier:(int)fp20;
- (void)composeRecipientView:(id)fp8 didChangeSize:(struct CGSize)fp12;
- (void)composeRecipientViewRequestAddRecipient:(id)fp8;
- (void)composeRecipientViewDidFinishPickingRecipient:(id)fp8;
- (void)animationDidStop:(id)fp8;
- (void)_updateContentSize;
- (void)reflow;
- (void)_hideSearchField:(BOOL)fp8;
- (void)_showSearchField:(BOOL)fp8;
- (void)_searchWithText:(id)fp8;
- (float)heightWithoutSeparator;
- (BOOL)isShowingSearchField;
- (id)delegate;
- (void)setDelegate:(id)fp8;

@end

