/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIView.h"

@class CKProgressBar, UILabel;

@interface CKSendingProgressView : UIView
{
    CKProgressBar *_sendingProgress;
    UILabel *_statusLabel;
}

+ (struct CGRect)defaultFrame;
- (id)initWithFrame:(struct CGRect)fp8;
- (void)dealloc;
- (void)layoutSubviews;
- (void)setStatus:(id)fp8;
- (float)progressValue;
- (void)setProgressValue:(float)fp8;

@end

