/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class CKConversationList, NSString;

@interface CKService : NSObject
{
    NSString *_serviceID;
    CKConversationList *_conversationList;
}

- (id)initWithServiceID:(id)fp8;
- (int)createConversationWithRecipients:(id)fp8;
- (int)conversationIDWithRecipients:(id)fp8;
- (int)unreadConversationCount;
- (int)unreadCountForConversation:(id)fp8;
- (id)headerTitleForEntities:(id)fp8;
- (id)headerTitleForComposeRecipients:(id)fp8 mediaObjects:(id)fp12 subject:(id)fp16;
- (BOOL)canSendToRecipients:(id)fp8 withAttachments:(id)fp12 alertIfUnable:(BOOL)fp16;
- (void)markAllMessagesInConversationAsRead:(id)fp8;
- (BOOL)dbFull;
- (BOOL)canSendMessageWithMediaObjectTypes:(int *)fp8;
- (void)dealloc;
- (id)placeholderMessageForConversation:(id)fp8 withDate:(id)fp12;
- (id)newMessageWithComposition:(id)fp8 forConversation:(id)fp12;
- (id)newMessageWithMessage:(id)fp8 forConversation:(id)fp12 isForward:(BOOL)fp16;
- (void)sendMessage:(id)fp8;
- (id)conversationSummaries:(id *)fp8 groupIDs:(id *)fp12;
- (id)lookupRecipientsForConversation:(id)fp8;
- (void)fixupNames;
- (int)maxRecipientCount;
- (int)unreadCount;
- (id)messagesForConversation:(id)fp8 limit:(int)fp12 moreToLoad:(char *)fp16;
- (BOOL)restrictsMediaObjects;
- (BOOL)canAcceptMediaObject:(id)fp8 givenMediaObjects:(id)fp12;
- (BOOL)canAcceptMediaObjectType:(int)fp8 givenMediaObjects:(id)fp12;
- (double)maxTrimDurationForMediaType:(int)fp8;
- (id)copyEntityForAddressString:(id)fp8;
- (id)unknownEntity;
- (id)abPropertyTypes;
- (BOOL)isValidAddress:(id)fp8;
- (int)maxAttachmentCount;
- (void)deleteMessagesForConversationIDs:(id)fp8 removeConversations:(BOOL)fp12;
- (id)conversationList;
- (id)serviceID;

@end

