/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <ChatKit/CKMessage.h>

@class CKSMSMessageDelivery, NSMutableArray;

@interface CKSMSMessage : CKMessage
{
    NSMutableArray *_messages;
    int _associationID;
    CKSMSMessageDelivery *_delivery;
}

- (void)setDelivery:(id)fp8;
- (void)dealloc;
- (void)_loadFailedSendCount;
- (BOOL)isPlaceholder;
- (BOOL)hasBeenRead;
- (int)totalMessageCount;
- (int)sentCount;
- (void)_storeUIFlags:(unsigned long)fp8;
- (void)_loadUIFlags;
- (void)_loadSubject;
- (void)_loadText;
- (BOOL)_loadOutgoing;
- (id)_createParts;
- (void)addMessage:(struct __CKSMSRecord *)fp8;
- (void)setMessages:(id)fp8;
- (void)markAsRead;
- (double)_loadDate;
- (void)permanentlyRemoveMessage;
- (id)messages;
- (id)initWithCTMessage:(struct __CKSMSRecord *)fp8 messageParts:(id)fp12;
- (BOOL)isEqual:(id)fp8;
- (id)initWithCTMessages:(id)fp8 messageParts:(id)fp12;
- (int)messageCount;
- (BOOL)isForward;
- (void)prepareToResend;
- (id)sender;
- (id)address;
- (id)alertImageData;
- (BOOL)isOnlyDisplayableMessagePart:(id)fp8;
- (BOOL)containsDisplayableMessageParts;
- (void)deleteMessagePart:(id)fp8;
- (void)_setupDeliveryIfPending;
- (void)deliveredSubpart:(int)fp8 totalSubparts:(int)fp12 success:(BOOL)fp16;
- (void)deliveryCompletedForMessage:(id)fp8;
- (void)deliveryFailedForMessage:(id)fp8;
- (void)deliveryPartiallyFailedForMessage:(id)fp8;
- (id)delivery;
- (int)associationID;

@end

