/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <ChatKit/CKMessage.h>

@class NSString;

@interface CKSMSDeferredMessage : CKMessage
{
    NSString *_address;
}

- (id)initWithAddress:(id)fp8;
- (void)dealloc;
- (id)address;

@end

