/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <ChatKit/CKTranscriptController.h>

@class NSMutableArray;

@interface CKSMSComposeController : CKTranscriptController
{
    NSMutableArray *_presetMessageParts;
    id _delegate;
    BOOL _mimeType;
    BOOL _alreadySetUp;
    BOOL _shouldReenableAutomaticKeyboard;
    NSMutableArray *_partsToInsert;
    NSMutableArray *_typesToInsert;
    int _entryViewInvisible;
}

+ (BOOL)acceptsMIMEType:(id)fp8;
+ (double)maxTrimDurationForAudio;
+ (double)maxTrimDurationForVideo;
+ (BOOL)canSendPhotos:(int)fp8 videos:(int)fp12 audioClips:(int)fp16;
+ (id)_newMediaObjectForFilename:(id)fp8 mimeType:(id)fp12 exportedFilename:(id)fp16 options:(id)fp20;
- (void)_addPart:(id)fp8;
- (BOOL)_insertMediaObject:(id)fp8;
- (BOOL)insertFilename:(id)fp8 MIMEType:(id)fp12 exportedFilename:(id)fp16;
- (BOOL)insertFilename:(id)fp8 MIMEType:(id)fp12 exportedFilename:(id)fp16 options:(id)fp20;
- (BOOL)insertData:(id)fp8 MIMEType:(id)fp12 exportedFilename:(id)fp16;
- (void)setTextEntryContentsVisible:(BOOL)fp8;
- (void)viewWillDisappear:(BOOL)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (void)viewDidAppear:(BOOL)fp8;
- (void)transitionFromNewMessageToConversation;
- (void)cancelButtonClicked:(id)fp8;
- (void)send:(id)fp8;
- (void)dealloc;
- (void)_addPresetMessagePart:(id)fp8;
- (BOOL)mimeType;
- (void)setMimeType:(BOOL)fp8;
- (id)presetMessageParts;
- (void)setPresetMessageParts:(id)fp8;
- (id)delegate;
- (void)setDelegate:(id)fp8;

@end

