/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <ChatKit/CKService.h>

@class NSMutableSet;

@interface CKSMSService : CKService
{
    NSMutableSet *_deliveryObjects;
}

+ (id)sharedSMSService;
+ (id)dbPath;
+ (void)migrate;
- (int)messageCount;
- (id)userFormattedAlphanumericStringForAddress:(id)fp8;
- (int)unreadCountForConversation:(id)fp8;
- (BOOL)dbFull;
- (void)markAllMessagesInConversationAsRead:(id)fp8;
- (void)_receivedMessage:(struct __CKSMSRecord *)fp8 replace:(BOOL)fp12;
- (void)_sentMessage:(struct __CKSMSRecord *)fp8;
- (void)_sendError:(struct __CKSMSRecord *)fp8;
- (int)createConversationWithRecipients:(id)fp8;
- (int)conversationIDWithRecipients:(id)fp8;
- (void)_registerForCTNotifications;
- (id)init;
- (id)abPropertyTypes;
- (id)_newMMSMessageWithParts:(id)fp8 forConversation:(id)fp12 subject:(id)fp16;
- (id)_newMMSMessageWithComposition:(id)fp8 forConversation:(id)fp12;
- (id)_newSMSMessageWithText:(id)fp8 forConversation:(id)fp12;
- (BOOL)_sendMMSByDefaultForConversation:(id)fp8;
- (id)newMessageWithMessage:(id)fp8 forConversation:(id)fp12 isForward:(BOOL)fp16;
- (id)newMessageWithComposition:(id)fp8 forConversation:(id)fp12;
- (int)unreadConversationCount;
- (int)unreadCount;
- (id)placeholderMessageForConversation:(id)fp8 withDate:(id)fp12;
- (void)sendMessage:(id)fp8;
- (void)fixupNames;
- (id)lookupRecipientsForConversation:(id)fp8;
- (id)conversationSummaries:(id *)fp8 groupIDs:(id *)fp12;
- (id)messagesForConversation:(id)fp8 limit:(int)fp12 moreToLoad:(char *)fp16;
- (void)deleteMessagesForConversationIDs:(id)fp8 removeConversations:(BOOL)fp12;
- (void)dealloc;
- (id)copyEntityForAddressString:(id)fp8;
- (id)unknownEntity;
- (id)headerTitleForEntities:(id)fp8;
- (id)headerTitleForComposeRecipients:(id)fp8 mediaObjects:(id)fp12 subject:(id)fp16;
- (BOOL)restrictsMediaObjects;
- (BOOL)canSendMessageWithMediaObjectTypes:(int *)fp8;
- (BOOL)canAcceptMediaObjectType:(int)fp8 givenMediaObjects:(id)fp12;
- (BOOL)canSendToRecipients:(id)fp8 withAttachments:(id)fp12 alertIfUnable:(BOOL)fp16;
- (int)maxRecipientCount;
- (BOOL)canAcceptMediaObject:(id)fp8 givenMediaObjects:(id)fp12;
- (int)maxAttachmentCount;
- (BOOL)isValidAddress:(id)fp8;
- (double)maxTrimDurationForMediaType:(int)fp8;

@end

