/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UITextContentView.h"

@class UILabel;

@interface CKTextContentView : UITextContentView
{
    UILabel *_defaultTextView;
}

+ (float)singleLineTextHeight;
- (id)initWithFrame:(struct CGRect)fp8;
- (void)dealloc;
- (void)setDefaultText:(id)fp8;
- (void)setText:(id)fp8;
- (BOOL)hasImages;
- (BOOL)keyboardInputChanged:(id)fp8;
- (void)hideDefaultText:(BOOL)fp8;
- (id)automaticallySelectedOverlay;
- (void)scrollRectToVisible:(struct CGRect)fp8 animated:(BOOL)fp24;
- (void)_adjustForSingleLineHeightIfNecessary;
- (void)reflow;
- (void)_updateDefaultText;

@end

