/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <ChatKit/CKTranscriptBubbleData.h>

@interface CKTranscriptBubbleData (ConvenienceAndClarity)
- (int)typeAtIndex:(int)fp8;
- (id)entityAtIndex:(int)fp8;
- (id)messageAtIndex:(int)fp8;
- (id)dateAtIndex:(int)fp8;
- (id)partAtIndex:(int)fp8;
- (id)textAtIndex:(int)fp8;
- (id)subjectAtIndex:(int)fp8;
- (int)heightAtIndex:(int)fp8;
- (Class)balloonClassAtIndex:(int)fp8;
- (BOOL)isSubjectPlaceholderAtIndex:(int)fp8;
- (BOOL)isMessageContinuationAtIndex:(int)fp8;
@end

