/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSDate, NSMutableArray;

@interface CKTranscriptBubbleData : NSObject
{
    NSMutableArray *_bubbleDataArray;
    float _balloonWidth;
    NSDate *_nextEligibleTimestamp;
}

+ (Class)balloonClassForMessagePart:(id)fp8;
+ (Class)balloonClassForFlags:(unsigned long)fp8;
+ (Class)balloonClassForMessage:(id)fp8;
+ (unsigned long)_processFlags:(unsigned long)fp8 forText:(id)fp12;
- (void)dealloc;
- (int)count;
- (id)data:(int)fp8 forIndex:(int)fp12;
- (id)bubbleDataForIndex:(int)fp8;
- (BOOL)bubbleData:(id)fp8 isEqualToIndex:(int)fp12;
- (id)deleteMessageAtIndex:(int)fp8;
- (void)appendBubbleDataForMessage:(id)fp8;
- (void)clearBubbleData;
- (void)_createArrayIfNeeded;
- (void)_createBubbleInfoForImage:(id)fp8 part:(id)fp12 subject:(id)fp16;
- (void)_appendTextMessage:(id)fp8 part:(id)fp12 height:(int)fp16 text:(id)fp20 subject:(id)fp24 bubbleClass:(Class)fp28 messageContinuation:(BOOL)fp32;
- (void)_createSegmentArrayForMessageText:(id)fp8 height:(unsigned int *)fp12 message:(id)fp16 subject:(id)fp20 part:(id)fp24 messageContinuation:(BOOL)fp28;
- (void)_createBubbleInfoForTextMessage:(id)fp8 part:(id)fp12 subject:(id)fp16;
- (void)_appendDateForMessageIfNeeded:(id)fp8;
- (void)_appendEntity:(id)fp8;
- (void)_appendDate:(id)fp8;
- (void)_appendEntityForMessageIfNeeded:(id)fp8;
- (void)_setupNextEligibleTimestamp:(id)fp8;
- (BOOL)_shouldShowTimestampForDate:(id)fp8;
- (float)balloonWidth;
- (void)setBalloonWidth:(float)fp8;

@end

