/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <ChatKit/CKMediaObject.h>

@interface CKUnknownMediaObject : CKMediaObject
{
}

+ (BOOL)supportsMIMEType:(id)fp8;
- (float)balloonHeightWithPreviewData:(id)fp8;
- (Class)balloonPreviewClassWithPreviewData:(id)fp8;
- (BOOL)shouldTranscodeForMMS;
- (id)newTranscodingForMMSWithMaxByteLength:(int)fp8;
- (id)newPreview:(int)fp8 highlight:(BOOL)fp12;
- (id)_icon;
- (void)configureBalloon:(id)fp8 withPreviewData:(id)fp12;
- (id)_effectiveFilename;

@end

