/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <ChatKit/CKMediaObject.h>

@interface CKVCalMediaObject : CKMediaObject
{
}

+ (id)mimeTypesToFileExtensions;
- (int)mediaType;
- (BOOL)shouldTranscodeForMMS;
- (Class)balloonPreviewClassWithPreviewData:(id)fp8;
- (void)configureBalloon:(id)fp8 withPreviewData:(id)fp12;

@end

