/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <ChatKit/CKAVMediaObject.h>

@class NSDictionary, NSString;

@interface CKVideoMediaObject : CKAVMediaObject
{
    NSDictionary *_transcodeOptions;
    struct CGImage *_videoPreviewCGImage;
    NSString *_transcodePath;
}

+ (id)mimeTypesToFileExtensions;
- (void)dealloc;
- (BOOL)shouldTranscodeForMMS;
- (int)mediaType;
- (id)transcodedFilename;
- (Class)balloonPreviewClassWithPreviewData:(id)fp8;
- (float)balloonHeightWithPreviewData:(id)fp8;
- (id)newPreview:(int)fp8 highlight:(BOOL)fp12;
- (void)configureBalloon:(id)fp8 withPreviewData:(id)fp12;
- (unsigned long long)sizeInBytes;
- (id)optionsForMedia;
- (id)transcodePath;
- (id)transcodeMimeType;
- (double)transcodeStartTime;
- (double)transcodeEndTime;
- (double)transcodeDuration;
- (id)effectiveExportedFilename;
- (id)transcodedPathExtension;
- (id)_transcodeOptions;
- (struct CGImage *)_newPreviewImageWithTailStyle:(int)fp8;
- (struct CGImage *)_newPreviewImageForIncomingVideoWithTailStyle:(int)fp8;
- (void)_generatePreviewOnMainThreadForVideoFile:(id)fp8;
- (struct CGImage *)_newVideoPreviewImageForImage:(struct CGImage *)fp8 withTailStyle:(int)fp12;
- (id)filenameForMedia;

@end

