/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIRemoveControl.h"

@interface MailMultiSelectControl : UIRemoveControl
{
    unsigned int _inEditMode:1;
}

- (id)initWithTarget:(id)fp8 inEditMode:(BOOL)fp12;
- (void)_setInterceptMouseEvent:(BOOL)fp8;
- (void)setChecked:(BOOL)fp8 selected:(BOOL)fp12;

@end

