/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIThreePartButton.h"

@class UIImageView, UITextLabel;

@interface MailToolbarButton : UIThreePartButton
{
    UITextLabel *_titleLabel;
    UIImageView *_iconView;
    BOOL _isRed;
    BOOL _isMinibar;
}

- (id)initAsRed:(BOOL)fp8;
- (void)dealloc;
- (void)setEnabled:(BOOL)fp8;
- (struct CGPoint)_offsetForMiniBarState:(BOOL)fp8;
- (void)updateForMiniBarState:(BOOL)fp8;
- (void)setTitle:(id)fp8;
- (void)layoutSubviews;

@end

