/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIImage.h"

@interface UIImage (ImageWithTail)
+ (id)_balloonMask:(BOOL)fp8;
+ (id)_highlightImage;
+ (id)_imageWithColor:(BOOL)fp8;
+ (id)_balloonImage:(BOOL)fp8 color:(BOOL)fp12;
- (id)newBalloonImageWithTail:(BOOL)fp8;
- (id)newBalloonImageWithTail:(BOOL)fp8 size:(struct CGSize)fp12;
@end

