/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <QuartzCore/CAPropertyAnimation.h>

@interface CABasicAnimation : CAPropertyAnimation
{
}

- (void *)CA_copyRenderValue;
- (id)fromValue;
- (void)setFromValue:(id)fp8;
- (id)toValue;
- (void)setToValue:(id)fp8;
- (id)byValue;
- (void)setByValue:(id)fp8;
- (void)applyForTime:(double)fp8 presentationObject:(id)fp16 modelObject:(id)fp20;

@end

