/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <QuartzCore/CAContext.h>

@interface CAContextImpl : CAContext
{
    unsigned int _refcount;
    struct _opaque_pthread_mutex_t _mutex;
    void *_next;
    void *_layer;
    struct _CARenderContext *_renderCtx;
    struct CGColorSpace *_colorspace;
    unsigned int _serverPort;
    unsigned int _clientPort;
    struct __CFMachPort *_clientPortRef;
    struct __CFRunLoopSource *_clientPortSource;
    unsigned int _clientId;
    unsigned int _localId;
    struct x_list_struct *_shmems;
    struct x_list_struct *_deletedShmems;
    float _level;
    unsigned int _fenceName;
    unsigned int _fenceCount;
    struct commitClosure *_commit;
    unsigned int _ownsServerPort:1;
    unsigned int _synchronized:1;
    unsigned int _serverDied:1;
}

- (id)initWithOptions:(id)fp8 localContext:(_Bool)fp12;
- (id)initRemoteWithOptions:(id)fp8;
- (void)invalidate;
- (void)dealloc;
- (id)retain;
- (void)release;
- (unsigned int)retainCount;
- (unsigned int)contextId;
- (struct CGColorSpace *)colorSpace;
- (void)setColorSpace:(struct CGColorSpace *)fp8;
- (id)layer;
- (void)setLayer:(id)fp8;
- (void)orderAbove:(unsigned int)fp8;
- (void)orderBelow:(unsigned int)fp8;
- (void)setLevel:(float)fp8;
- (float)level;
- (struct _CARenderContext *)renderContext;
- (BOOL)valid;
- (void)setFence:(unsigned int)fp8 count:(unsigned int)fp12;
- (unsigned int)createSlot;
- (void)deleteSlot:(unsigned int)fp8;
- (void)setObject:(id)fp8 forSlot:(unsigned int)fp12;

@end

