/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <QuartzCore/CALayer.h>

@interface CALayer (CALayerScrolling)
- (void)_scrollPoint:(struct CGPoint)fp8 fromLayer:(id)fp16;
- (void)scrollPoint:(struct CGPoint)fp8;
- (void)_scrollRect:(struct CGRect)fp8 fromLayer:(id)fp24;
- (void)scrollRectToVisible:(struct CGRect)fp8;
- (struct CGRect)_visibleRectOfLayer:(id)fp8;
- (struct CGRect)visibleRect;
@end

