/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <QuartzCore/CALayer.h>

@interface CALayerHost : CALayer
{
}

- (void)didChangeValueForKey:(id)fp8;
- (struct _CARenderLayer *)_copyRenderLayer:(struct _CATransaction *)fp8 flags:(unsigned int *)fp12;
- (_Bool)_renderLayerDefinesProperty:(unsigned int)fp8;
- (unsigned int)contextId;
- (void)setContextId:(unsigned int)fp8;

@end

