/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <QuartzCore/CAMediaTimingFunction.h>

@interface CAMediaTimingFunctionBuiltin : CAMediaTimingFunction
{
    unsigned int _index;
}

- (void)_getPoints:(float *)fp8;
- (id)description;

@end

