/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <QuartzCore/CAAnimation.h>

@interface CAPropertyAnimation : CAAnimation
{
}

+ (id)animationWithKeyPath:(id)fp8;
- (void)applyForTime:(double)fp8 presentationObject:(id)fp16 modelObject:(id)fp20;
- (struct _CARenderAnimation *)_setCARenderAnimation:(struct _CARenderAnimation *)fp8;
- (BOOL)isAdditive;
- (void)setAdditive:(BOOL)fp8;
- (id)keyPath;
- (void)setKeyPath:(id)fp8;
- (BOOL)isCumulative;
- (void)setCumulative:(BOOL)fp8;
- (BOOL)additive;
- (BOOL)cumulative;

@end

