/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@interface CATransaction : NSObject
{
}

+ (void)begin;
+ (BOOL)beginWithoutBlocking;
+ (void)commit;
+ (void)flush;
+ (id)valueForKey:(id)fp8;
+ (void)setValue:(id)fp8 forKey:(id)fp12;
- (void)_addTimer:(id)fp8;

@end

