/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSValue.h"

@interface NSValue (CATransform3DAdditions)
+ (id)valueWithCATransform3D:(struct CATransform3D)fp8;
- (struct CATransform3D)CATransform3DValue;
@end

