/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSDictionary, NSString;

@interface SBRemoteNotification : NSObject
{
    NSString *_bundleIdentifier;
    NSString *_publisher;
    NSDictionary *_userInfo;
    struct __CFUserNotification *_userNotification;
    struct __CFRunLoopSource *_userNotificationSource;
}

- (void)setUserNotification:(struct __CFUserNotification *)fp8;
- (void)setUserNotificationSource:(struct __CFRunLoopSource *)fp8;
- (void)dealloc;
- (struct __CFRunLoopSource *)userNotificationSource;
- (struct __CFUserNotification *)userNotification;
- (id)userInfo;
- (void)setUserInfo:(id)fp8;
- (id)publisher;
- (void)setPublisher:(id)fp8;
- (id)bundleIdentifier;
- (void)setBundleIdentifier:(id)fp8;

@end

