/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlertItem.h"

@class NSString;

@interface SBUserNotificationAlert : SBAlertItem
{
    unsigned int _replyPort;
    int _token;
    int _timeout;
    unsigned int _requestFlags;
    NSString *_alertHeader;
    NSString *_alertMessage;
    NSString *_defaultButtonTitle;
    NSString *_alternateButtonTitle;
    id _textFieldTitles;
    id _textFieldValues;
    id _keyboardTypes;
    id _autocapitalizationTypes;
    id _autocorrectionTypes;
    NSString *_launchAppUponDefaultButton;
    double _creationTime;
    unsigned int _replyFlags;
    unsigned int _cancel:1;
    unsigned int _isActivated:1;
    unsigned int _aboveLock:1;
    unsigned int _dismissOnLock:1;
    unsigned int _allowMenuButtonDismissal:1;
    unsigned int _showInAwayItems:1;
}

- (id)_localizedValue:(id)fp8 withBundle:(id)fp12;
- (id)initWithMessage:(id)fp8 replyPort:(unsigned int)fp12 requestFlags:(int)fp16;
- (void)dealloc;
- (id)alertSheet;
- (int)token;
- (BOOL)shouldShowInLockScreen;
- (BOOL)dismissOnLock;
- (BOOL)allowMenuButtonDismissal;
- (id)lockLabel;
- (BOOL)willShowInAwayItems;
- (void)configure:(BOOL)fp8 requirePasscodeForActions:(BOOL)fp12;
- (void)wakeup;
- (void)cancel;
- (void)_sendResponse:(int)fp8;
- (void)launchAppIfRequested;
- (void)alertSheet:(id)fp8 buttonClicked:(int)fp12;
- (void)didDeactivateForReason:(int)fp8;
- (void)performUnlockAction;

@end

