/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SBAlertItem.h"

@class NSDictionary, NSMutableArray, NSString, NSTimer, UITable;

@interface SBWiFiAlertItem : SBAlertItem
{
    NSMutableArray *_networks;
    NSTimer *_scanTimer;
    UITable *_table;
    struct CGSize _size;
    int _joinRow;
    NSString *_password;
    NSDictionary *_joinDict;
    SBAlertItem *_childAlert;
    BOOL _selectingRow;
    BOOL _storedPassword;
    BOOL _passwordFailed;
    BOOL _sentResponse;
}

- (void)scan;
- (id)init;
- (int)_joinRow;
- (void)setNetworks:(id)fp8;
- (void)setChildAlert:(id)fp8;
- (id)insertionsForNewNetworks:(id)fp8;
- (id)deletionSetForLostNetworks:(id)fp8 originalNetworks:(id)fp12;
- (void)wifiManager:(id)fp8 scanCompleted:(id)fp12;
- (void)_enableTable;
- (void)dismiss;
- (void)willDeactivateForReason:(int)fp8;
- (void)willActivate;
- (void)wifiManager:(id)fp8 joinCompleted:(int)fp12;
- (void)didPresentAlertSheet:(id)fp8;
- (void)passwordEntered:(id)fp8;
- (void)dealloc;
- (void)alertSheet:(id)fp8 buttonClicked:(int)fp12;
- (BOOL)allowMenuButtonDismissal;
- (void)performUnlockAction;
- (int)numberOfRowsInTable:(id)fp8;
- (id)table:(id)fp8 cellForRow:(int)fp12 column:(id)fp16;
- (void)tableSelectionDidChange:(id)fp8;
- (void)configure:(BOOL)fp8 requirePasscodeForActions:(BOOL)fp12;
- (BOOL)dismissOnLock;
- (void)dismissAlertsForApplicationTransition;
- (void)didDeactivateForReason:(int)fp8;

@end

