/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@class UIView;

@interface SBAwayViewPluginController : NSObject
{
    UIView *_view;
}

+ (void)enableBundleNamed:(id)fp8;
+ (void)disableBundleNamed:(id)fp8;
- (void)dealloc;
- (id)view;
- (void)setView:(id)fp8;
- (void)loadView;
- (void)purgeView;
- (void)viewWillAppear:(BOOL)fp8;
- (void)viewDidAppear:(BOOL)fp8;
- (void)viewWillDisappear:(BOOL)fp8;
- (void)viewDidDisappear:(BOOL)fp8;
- (void)disable;
- (int)pluginPriority;
- (BOOL)animateResumingToApplicationWithIdentifier:(id)fp8;
- (BOOL)showAwayItems;
- (BOOL)handleMenuButtonTap;
- (BOOL)handleMenuButtonDoubleTap;
- (BOOL)handleMenuButtonHeld;
- (BOOL)handleGesture:(int)fp8 fingerCount:(unsigned int)fp12;

@end

