/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "mSMSBalloonTextField.h"

@class DOMHTMLElement, UIWebDocumentView;

@interface mSMSBalloonWebTextField : mSMSBalloonTextField
{
    UIWebDocumentView *_webLayer;
    DOMHTMLElement *_textElement;
}

+ (float)heightForText:(id)fp8;
- (id)initWithFrame:(struct CGRect)fp8;
- (void)dealloc;
- (void)setOrientation:(int)fp8;
- (void)setText:(id)fp8;
- (void)setDraws:(BOOL)fp8;
- (id)text;
- (void)setNeedsDisplay;
- (void)tighten;
- (void)cancelInteraction;
- (void)webViewDidChange:(id)fp8;

@end

