/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

#import "ABNewPersonViewControllerDelegate-Protocol.h"
#import "ABPeoplePickerNavigationControllerDelegate-Protocol.h"
#import "ABPersonViewControllerDelegate-Protocol.h"
#import "ABUnknownPersonViewControllerDelegate-Protocol.h"
#import "UIModalViewDelegate-Protocol.h"

@class ABPeoplePickerNavigationController, MailComposeController, NSDictionary, UINavigationController, UIWindow, mSMSLinkViewController, mSMSMessageListController, mSMSMessageTranscriptController;

@interface mSMSUIController : NSObject <UIModalViewDelegate, ABPersonViewControllerDelegate, ABUnknownPersonViewControllerDelegate, ABNewPersonViewControllerDelegate, ABPeoplePickerNavigationControllerDelegate>
{
    UIWindow *_window;
    UINavigationController *_navigationController;
    mSMSMessageListController *_messageListController;
    mSMSMessageTranscriptController *_messageTranscriptController;
    mSMSLinkViewController *_linkViewController;
    MailComposeController *_mailComposeController;
    ABPeoplePickerNavigationController *_peoplePickerController;
    BOOL _hasEmail;
    BOOL _restoringState;
    struct __CFArray *_queuedMessages;
    NSDictionary *_propsCache;
    id _navBarLeftButtonTarget;
    SEL _navBarLeftButtonAction;
    id _navBarRightButtonTarget;
    SEL _navBarRightButtonAction;
}

+ (id)sharedInstance;
- (struct CGRect)contentViewRect;
- (void)_init;
- (void)_displaySMSDatabaseFullWarning;
- (void)dealloc;
- (id)messageListController;
- (id)messageTranscriptController;
- (id)existingMessageGroupForAddresses:(id)fp8;
- (void)showMessagesForAddress:(id)fp8 animate:(BOOL)fp12;
- (BOOL)resumeToMessageGroup:(id)fp8 unsentText:(id)fp12;
- (void)showMessageGroup:(id)fp8 animate:(BOOL)fp12;
- (void)showTranscriptList:(BOOL)fp8;
- (void)showURLListForMessage:(id)fp8;
- (void)showNewMessageCompositionPanel:(BOOL)fp8;
- (BOOL)_shouldPlaySounds;
- (void)_playMessageSent;
- (void)_playMessageRecieved;
- (void)compose:(id)fp8;
- (void)transitionFromNewMessageToConversation;
- (void)_processReceivedMessage:(struct __CTSMSMessage *)fp8 replace:(BOOL)fp12 isLastMessage:(BOOL)fp16 animate:(BOOL)fp20;
- (void)_receivedMessage:(struct __CTSMSMessage *)fp8 replace:(BOOL)fp12;
- (void)markMessageGroupAsRead:(id)fp8;
- (void)noteMessageGroupChanged:(id)fp8 animate:(BOOL)fp12;
- (void)receivedMessage:(struct __CTSMSMessage *)fp8;
- (void)receivedReplaceMessage:(struct __CTSMSMessage *)fp8;
- (void)_sentMessage:(struct __CTSMSMessage *)fp8;
- (void)sentMessage;
- (long)numberOfQueuedMessages;
- (void)dequeueMessages;
- (void)addReceivedMessageToQueue:(struct __CTSMSMessage *)fp8 replace:(BOOL)fp12;
- (void)displayAlertSheet:(id)fp8;
- (void)dismissAlertSheet:(id)fp8;
- (void)alertSheet:(id)fp8 buttonClicked:(int)fp12;
- (void)dismissPeoplePicker:(id)fp8;
- (void)dismissPeoplePicker;
- (void)showPeoplePickerWithDelegate:(id)fp8;
- (void)tearDownPeoplePicker;
- (BOOL)peoplePickerNavigationController:(id)fp8 shouldContinueAfterSelectingPerson:(void *)fp12 property:(int)fp16 identifier:(int)fp20;
- (BOOL)peoplePickerNavigationController:(id)fp8 shouldContinueAfterSelectingPerson:(void *)fp12;
- (void)peoplePickerNavigationController:(id)fp8 displayedMembersOfGroup:(void *)fp12;
- (void)peoplePickerNavigationControllerDisplayedGroups:(id)fp8;
- (void)_updateUI;
- (void)_abUpdated:(void *)fp8;
- (void)_restoreUnsentMessages;
- (void)handleURL:(id)fp8;
- (BOOL)restoringState;
- (BOOL)_restoreState;
- (BOOL)showUnreadConversations;
- (BOOL)isShowingTranscriptWithUnsentText;
- (void)storeState:(id)fp8;
- (void *)createPersonWithValue:(struct __CFString *)fp8 forMultiValueProperty:(int)fp12;
- (id)_abPersonViewControllerForPerson:(void *)fp8 property:(int)fp12 withIdentifier:(int)fp16;
- (BOOL)personViewController:(id)fp8 shouldPerformDefaultActionForPerson:(void *)fp12 property:(int)fp16 identifier:(int)fp20;
- (id)_unknownPersonViewControllerForProps:(id)fp8;
- (id)_personViewControllerForProps:(id)fp8;
- (void)_displayABPersonViewController:(id)fp8;
- (void)showABCardForPerson:(void *)fp8 highlightedProperty:(int)fp12 identifier:(int)fp16;
- (void)showABCardForLinkProperties:(id)fp8;
- (void)cardViewer:(id)fp8 presentActionsSheet:(id)fp12;
- (void)cardViewer:(id)fp8 dismissActionsSheet:(id)fp12;
- (void)cardViewer:(id)fp8 presentActionsView:(id)fp12 withTitle:(id)fp16;
- (void)unknownPersonViewController:(id)fp8 didResolveToPerson:(void *)fp12;
- (void)_showMailComposeSheet;
- (void)_showComposeEmailForAddress:(id)fp8;
- (void)mailComposeControllerCompositionFinished:(id)fp8;
- (void)_emailDeliveryFailed:(id)fp8;
- (void)_backgroundDeliverEmail:(id)fp8;
- (void)mailComposeController:(id)fp8 willUseMessageHeaders:(id)fp12;
- (void)mailComposeControllerContentsDidChange:(id)fp8;
- (BOOL)mailComposeControllerIsEditingDraft:(id)fp8;
- (void)mailComposeController:(id)fp8 loadedAttachments:(id)fp12;
- (void)showNewContactViewForNumber:(id)fp8;
- (void)newPersonViewController:(id)fp8 didCompleteWithNewPerson:(void *)fp12;
- (void)showAddToExistingContactViewForNumber:(id)fp8;
- (void)peoplePickerNavigationControllerDidCancel:(id)fp8;
- (BOOL)peoplePickerNavigationController:(id)fp8 shouldShowInsertEditorForPerson:(void *)fp12 insertProperty:(int *)fp16 copyInsertValue:(id *)fp20 copyInsertLabel:(id *)fp24;
- (BOOL)peoplePickerNavigationController:(id)fp8 shouldDismissAfterInsertEditorConfirmed:(BOOL)fp12 withPerson:(void *)fp16;

@end

