/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIImageAndTextTableCell.h"

@class SMSMessageSynopsisLabel, UIDateLabel, mSMSMessageGroup;

@interface mSMSMessageSynopsisLayer : UIImageAndTextTableCell
{
    mSMSMessageGroup *_messageGroup;
    UIDateLabel *_dateLabel;
    SMSMessageSynopsisLabel *_messageLabel;
    SMSMessageSynopsisLabel *_backupMessageLabel;
    BOOL _willShowRemove;
}

+ (float)cellHeight;
- (id)initWithFrame:(struct CGRect)fp8 messageGroup:(id)fp24;
- (void)setMessageGroup:(id)fp8;
- (void)dealloc;
- (void)clearText;
- (void)updateContents;
- (void)updateHighlightColors;
- (void)_setupBackupMessageLabel;
- (void)layoutSubviews;
- (void)removeControlWillShowRemoveConfirmation:(id)fp8;
- (void)removeControlWillHideRemoveConfirmation:(id)fp8;

@end

