/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIView.h"

@class NSString, UIProgressBar;

@interface mSMSSendingProgressLayer : UIView
{
    UIProgressBar *_progressLayer;
    NSString *_displayString;
    UIView *_partialFailurePane;
    id _delegate;
}

- (id)initWithSize:(struct CGSize)fp8;
- (void)dealloc;
- (void)showPartialFailurePane;
- (void)sendPushed;
- (void)cancelPushed;
- (void)hidePartialFailurePane;
- (void)setDelegate:(id)fp8;
- (void)setDisplayString:(id)fp8;
- (void)setProgress:(float)fp8;
- (void)drawRect:(struct CGRect)fp8;

@end

