/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIViewController.h>

@class CollapsibleAtomList, NSMutableArray, NSTimer, SMSMessage, SMSMessageDelivery, SMSRecipientSelectionView, TranscriptFrameAnimation, UIButton, UIControl, UIFrameAnimation, UIKeyboard, UIModalView, UIScroller, UIView, mSMSBalloonTextField, mSMSMessageEntryView, mSMSMessageGroup, mSMSMessageTranscriptLayer, mSMSSendingProgressLayer, mSMSUIController;

@interface mSMSMessageTranscriptController : UIViewController <UIModalViewDelegate>
{
    mSMSMessageGroup *_messageGroup;
    mSMSUIController *_uiController;
    UIView *_backPlacard;
    UIKeyboard *_keyboardLayer;
    BOOL _keyboardVisible;
    mSMSMessageTranscriptLayer *_transcriptLayer;
    CollapsibleAtomList *_recipientList;
    UIControl *_recipientContainer;
    UIScroller *_recipientScroller;
    UIView *_recipientSeparator;
    mSMSMessageEntryView *_entryView;
    UIButton *_clearButton;
    UIView *_multipleRecipientTitleView;
    NSMutableArray *_bubbleData;
    id _lastMessage;
    mSMSBalloonTextField *_outboundMessageLayer;
    UIView *_replacementMessageLayer;
    mSMSSendingProgressLayer *_sendingProgressLayer;
    double _progStart;
    float _sendingProgress;
    float _progressRate;
    NSTimer *_sendingProgressTimer;
    NSMutableArray *_recipients;
    SMSMessageDelivery *_delivery;
    int _numberSent;
    int _numberToSend;
    SMSMessage *_outboundMessage;
    BOOL _newRecipient;
    SMSRecipientSelectionView *_recipientSelectionView;
    UIFrameAnimation *_throwAnimation;
    TranscriptFrameAnimation *_transcriptAnimation;
    UIFrameAnimation *_messageEntryViewAnimation;
    unsigned int _rescroll:1;
    unsigned int _sending:1;
    unsigned int _waitingOnMessageSend:1;
    unsigned int _failedToSend:1;
    unsigned int _isThrowingOutboundMessageToTable:1;
    unsigned int _recipientListScrollingEnabled:1;
    unsigned int _recipientListShouldBeExpanded:1;
    unsigned int _shouldMoveFocusToUnsentCursorPosition:1;
    NSTimer *_errorDisplayTimer;
    UIModalView *_contactAlertSheet;
    UIModalView *_clearConversationAlertSheet;
}

+ (id)tableColor;
- (id)initWithUIController:(id)fp8;
- (void)dealloc;
- (struct CGPoint)bestVisibleOffsetForBubbleAtIndex:(int)fp8;
- (void)scrollBubbleIndexToVisible:(int)fp8;
- (void)setMessageGroup:(id)fp8;
- (void)_reloadTranscriptLayer;
- (void)reload:(BOOL)fp8;
- (id)messageGroup;
- (void)_setupRecipientSelectionView;
- (void)updateEnablednessOfSendButton;
- (void)_adjustMessageEntryViewOriginDelta:(float)fp8 heightDelta:(float)fp12 animate:(BOOL)fp16 animationLength:(float)fp20;
- (void)_adjustTranscriptLayerFrameDelta:(struct CGRect)fp8 offsetDelta:(struct CGPoint)fp24 animate:(BOOL)fp32 animationLength:(float)fp36;
- (float)smsRecipientSelectionViewMaxHeight:(id)fp8;
- (float)smsRecipientSelectionViewMaxToFieldHeight:(id)fp8;
- (void)smsRecipientSelectionView:(id)fp8 recipientAdded:(id)fp12;
- (void)smsRecipientSelectionViewEmpty:(id)fp8;
- (void)hideKeyboard:(BOOL)fp8;
- (void)showKeyboard:(BOOL)fp8;
- (BOOL)isSendingMessage;
- (id)entryView;
- (id)sendingProgressLayer;
- (void)loadView;
- (void)viewWillAppear:(BOOL)fp8;
- (void)moveCursorToEnd;
- (void)saveMessageStore;
- (void)viewDidAppear:(BOOL)fp8;
- (void)viewWillDisappear:(BOOL)fp8;
- (id)titleViewForMultipleRecipients;
- (void)updateTitle;
- (void)updateNavigationButtons;
- (void)cancelButtonClicked:(id)fp8;
- (void)clearButtonClicked:(id)fp8;
- (void)scrollerWillStartDragging:(id)fp8;
- (void)resignEntryViewFirstResponder;
- (void)makeRecipientFieldFirstResponder;
- (void)restoreEntryViewCursor;
- (void)makeEntryViewFirstResponder;
- (void)activateURLButton:(id)fp8;
- (void)addressAtomClicked:(id)fp8;
- (void)_setupTranscriptHeader;
- (void)_clearExpandRecipientListFlag;
- (void)_loadMore;
- (void)_showTranscriptButtons;
- (void)_hideAccessoryView;
- (void)_hideTranscriptButtons;
- (void)_showRecipientList;
- (void)_hideRecipientList;
- (void)_updateRecipientContainerViewFrame;
- (void)_updateRecipientScrollViewFrame;
- (void)_updateTranscriptScrollerIndicatorSubrect;
- (void)collapsibleAtomList:(id)fp8 sizeDidChange:(struct CGSize)fp12;
- (Class)balloonClassForText:(id)fp8;
- (id)_createSegmentArrayForMessageText:(id)fp8 height:(unsigned int *)fp12 smsMessage:(id)fp16;
- (void)appendDataArraysFromMessageToBubbleData:(id)fp8;
- (void)_computeBubbleData;
- (id)bubbleData;
- (void)addOutboundMessage:(id)fp8 reloadForInsertion:(BOOL)fp12;
- (id)table:(id)fp8 cellForRow:(int)fp12 column:(id)fp16;
- (int)numberOfRowsInTable:(id)fp8;
- (float)table:(id)fp8 heightForRow:(int)fp12;
- (void)cleanUpAfterSendAttempt:(BOOL)fp8;
- (void)animator:(id)fp8 stopAnimation:(id)fp12;
- (struct CGPoint)_transcriptScrollToBottomOffsetWithHeightDelta:(float)fp8;
- (void)throwOutboundMessageToTable:(id)fp8 clearTranscript:(BOOL)fp12;
- (void)didBeginSendingText:(id)fp8 alphaIn:(BOOL)fp12 rebuildOutboundLayer:(BOOL)fp16;
- (void)didBeginSendingText:(id)fp8;
- (void)_scheduleNextProgressUpdate:(SEL)fp8;
- (void)finishProgress;
- (void)updateSendingProgress;
- (void)resetErrorDisplay;
- (void)tearDownErrorDisplay;
- (void)showErrorDisplay;
- (void)mSMSSendingProgressLayerCancelHit:(id)fp8;
- (void)mSMSSendingProgressLayerTryAgainHit:(id)fp8;
- (void)_showPartialFailureDisplay;
- (void)didEndSendingMessage:(id)fp8;
- (void)_fadeOutSendingProgressLayer;
- (void)_actuallyClearCurrentMessageThread;
- (void)clearCurrentMessageThread;
- (void)_startUpdatingSendProgress;
- (void)sendMessage:(id)fp8;
- (void)deliveredSubpart:(int)fp8 totalSubparts:(int)fp12 success:(BOOL)fp16;
- (void)deliveryPartiallyFailedForMessage:(id)fp8;
- (void)deliveryCompletedForMessage:(id)fp8;
- (void)deliveryFailedForMessage:(id)fp8;
- (void)send:(id)fp8;
- (void)transcriptLayerTapped:(id)fp8;
- (struct CGRect)messageEntryViewFinalFrame;
- (id)smsTextEntryViewMessageEntryView:(id)fp8;
- (void)smsTextEntryViewWillBecomeFirstResponder:(id)fp8;
- (void)smsTextEntryViewTextChanged:(id)fp8;
- (void)smsTextEntryViewSizeChanged:(id)fp8 height:(float)fp12 animate:(BOOL)fp16;
- (id)text;
- (void)setText:(id)fp8;
- (void)setText:(id)fp8 resizeEntryView:(BOOL)fp12 animate:(BOOL)fp16;
- (void)findMessageGroupForRecipients:(id)fp8;
- (id)recipients;
- (id)proposedRecipients;
- (void)setNewCompositionAddresses:(id)fp8;
- (void)setupForNewRecipient;
- (BOOL)isNewRecipient;
- (void)addRecipient:(void *)fp8 identifier:(int)fp12 phoneNumber:(id)fp16;
- (void)webView:(id)fp8 decidePolicyForNavigationAction:(id)fp12 request:(id)fp16 frame:(id)fp20 decisionListener:(id)fp24;
- (void)smsTranscriptTopCell:(id)fp8 buttonClicked:(int)fp12;
- (void)alertSheet:(id)fp8 buttonClicked:(int)fp12;

@end

