/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "mSMSApplication.h"

@interface mSMSApplication (mSMSApplicationTesting)
- (BOOL)runTest:(id)fp8 options:(id)fp12;
- (void)finishedTest:(id)fp8 extraResults:(id)fp12;
- (void)failedTest:(id)fp8;
- (void)showTranscriptList;
- (void)didShowAMessage;
- (void)didShowTranscriptList;
- (void)didSendMessage;
- (void)showNextMessage;
- (void)startShowMessagesTest:(id)fp8;
- (void)startSendMessageTest:(id)fp8;
- (void)sendNextMessage;
- (void)startThrowTest:(id)fp8;
- (void)flickFinished:(id)fp8;
- (void)_scrollTranscriptTest:(id)fp8;
- (void)startScrollTranscriptTest:(id)fp8;
@end

