/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UITable.h>

@interface mSMSMessageTranscriptLayer : UITable
{
    id _transcriptDelegate;
}

- (void)setTranscriptDelegate:(id)fp8;
- (void)touchesEnded:(id)fp8 withEvent:(id)fp12;

@end

