/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@interface NSObject (SMSTextEntryViewDelegate)
- (void)smsTextEntryViewSizeChanged:(id)fp8 height:(float)fp12 animate:(BOOL)fp16;
- (id)smsTextEntryViewMessageEntryView:(id)fp8;
- (void)smsTextEntryViewTextChanged:(id)fp8;
- (void)smsTextEntryViewWillBecomeFirstResponder:(id)fp8;
- (struct CGRect)smsTextEntryViewFinalFrame:(id)fp8;
@end

