/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSCalendarDate, NSMutableArray, NSString;

@interface SMSMessage : NSObject
{
    NSMutableArray *_messages;
    double _date;
    BOOL _dateLoaded;
    NSCalendarDate *_calendarDate;
    BOOL _outgoingLoaded;
    BOOL _outgoing;
    NSString *_text;
    unsigned int _height;
    unsigned int _flags;
    BOOL _heightAndFlagsLoaded;
    int _failedSendCount;
    BOOL _failedSendCountLoaded;
    int _associationID;
    int _groupID;
}

- (id)init;
- (id)initWithMessage:(struct __CTSMSMessage *)fp8;
- (id)initWithMessages:(id)fp8;
- (BOOL)isEqual:(id)fp8;
- (void)dealloc;
- (void)_resetData;
- (void)addMessage:(struct __CTSMSMessage *)fp8;
- (int)associationID;
- (int)groupID;
- (id)messages;
- (double)timeIntervalSince1970;
- (id)date;
- (id)unreadMessages;
- (void)markAsRead;
- (void)permanentlyRemoveMessage;
- (BOOL)isOutgoing;
- (id)text;
- (unsigned long)height;
- (void)setUIHeight:(unsigned long)fp8 flags:(unsigned long)fp12;
- (void)getUIHeight:(unsigned int *)fp8 flags:(unsigned int *)fp12;
- (int)pendingCount;
- (BOOL)pending;
- (BOOL)failedSend;
- (BOOL)partiallyFailedSend;
- (int)sentCount;
- (BOOL)hasBeenSent;
- (BOOL)hasBeenRead;
- (BOOL)isPlaceholder;
- (int)failedSendCount;
- (BOOL)completelyFailedSend;
- (void)reloadFailedSendCount;

@end

