/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@interface SMSMessageAddress : NSObject
{
    void *_address;
    int _hash;
    BOOL _hashComputed;
}

+ (id)addressessForCTMessageAddresses:(id)fp8;
- (id)initWithCTMessageAddress:(void *)fp8;
- (void)dealloc;
- (id)phoneNumber;
- (unsigned int)hash;
- (BOOL)isEqual:(id)fp8;

@end

