/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIView.h"

@class ComposeRecipientView, NSMutableArray, SearchShadowView, UIScroller, UITable;

@interface SMSRecipientSelectionView : UIView
{
    ComposeRecipientView *_toField;
    UIScroller *_toFieldScrollingView;
    NSMutableArray *_searchResults;
    UITable *_searchResultsTable;
    SearchShadowView *_shadowView;
    BOOL _showingSearchField;
    id _delegate;
}

- (id)firstRecipient;
- (id)recipients;
- (float)_maxHeight;
- (float)_properHeight;
- (void)setFrame:(struct CGRect)fp8;
- (void)_resetHeight;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;
- (void)reset;
- (id)toField;
- (void)setDelegate:(id)fp8;
- (void)_hideSearchField;
- (void)_showSearchField;
- (int)numberOfRowsInTable:(id)fp8;
- (id)table:(id)fp8 cellForRow:(int)fp12 column:(id)fp16 reusing:(id)fp20;
- (void)tableSelectionDidChange:(id)fp8;
- (void)appendSearchResults:(id)fp8 identifiers:(id)fp12 recipientClass:(Class)fp16;
- (void)searchWithText:(id)fp8;
- (void)composeRecipientView:(id)fp8 textDidChange:(id)fp12;
- (void)composeRecipientView:(id)fp8 requestDeleteRecipientAtIndex:(int)fp12;
- (void)composeRecipientViewDidFinishEnteringRecipient:(id)fp8;
- (void)composeRecipientView:(id)fp8 peoplePicker:(id)fp12 selectedRecord:(void *)fp16 withIdentifier:(int)fp20;
- (id)composeRecipientView:(id)fp8 composeRecipientForAddress:(id)fp12;
- (id)composeRecipientView:(id)fp8 composeRecipientForRecord:(void *)fp12 identifier:(int)fp16;
- (void)animationDidStop:(id)fp8;
- (void)composeRecipientView:(id)fp8 didChangeSize:(struct CGSize)fp12;
- (void)composeRecipientViewRequestAddRecipient:(id)fp8;
- (void)composeRecipientViewDidFinishPickingRecipient:(id)fp8;

@end

