/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIFrameAnimation.h"

@interface TranscriptFrameAnimation : UIFrameAnimation
{
    struct CGPoint _startTopLeftPoint;
    struct CGPoint _endTopLeftPoint;
}

- (void)setProgress:(float)fp8;
- (void)setStartTopLeftPoint:(struct CGPoint)fp8;
- (void)setEndTopLeftPoint:(struct CGPoint)fp8;
- (struct CGPoint)endTopLeftPoint;

@end

