/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class ABCardController, NSString;

@interface ABActionsController : NSObject
{
    ABCardController *_cardController;
    BOOL _isUnknownPerson;
    int _property;
    NSString *_stringValue;
    NSString *_label;
    int _multiValueIdentifier;
    id _value;
    int _recordID;
}

+ (id)createActionsControllerForProperty:(int)fp8 withCardController:(id)fp12;
- (id)initWithProperty:(int)fp8 cardController:(id)fp12;
- (void)dealloc;
- (void)setIsKnown:(BOOL)fp8;
- (int)actionsGroupFirstIndexOfSecondGroup;
- (int)actionsCount;
- (id)actionTitleForIndex:(int)fp8;
- (void)performActionAtIndex:(int)fp8;
- (void)performDefaultAction;
- (void)setLabel:(id)fp8;
- (id)stringValue;
- (void)setStringValue:(id)fp8;
- (id)value;
- (void)setValue:(id)fp8;
- (void)setMultiValueIdentifier:(int)fp8;
- (void)setRecordID:(int)fp8;
- (void)actionSelectedAtIndex:(int)fp8;
- (void)openURLWithFormat:(id)fp8 value:(id)fp12;
- (BOOL)shouldShowAddToFavorites;
- (int)phoneActionsGroupFirstIndexOfSecondGroup;
- (int)phoneActionCount;
- (id)phoneActionTitleForIndex:(int)fp8;
- (void)phoneActionSelectedAtIndex:(int)fp8;
- (int)emailActionsGroupFirstIndexOfSecondGroup;
- (int)emailActionCount;
- (id)emailActionTitleForIndex:(int)fp8;
- (void)emailActionSelectedAtIndex:(int)fp8;
- (int)urlActionsGroupFirstIndexOfSecondGroup;
- (int)urlActionCount;
- (id)urlActionTitleForIndex:(int)fp8;
- (void)urlActionSelectedAtIndex:(int)fp8;
- (int)addressActionsGroupFirstIndexOfSecondGroup;
- (int)addressActionCount;
- (id)addressActionTitleForIndex:(int)fp8;
- (void)addressActionSelectedAtIndex:(int)fp8;
- (int)cardActionsGroupFirstIndexOfSecondGroup;
- (int)cardActionCount;
- (id)cardActionTitleForIndex:(int)fp8;
- (void)cardActionSelectedAtIndex:(int)fp8;

@end

