/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIView.h"

@class ABEditorController, UIDatePicker, UIKeyboard, UIScroller;

@interface ABCardEditingLayer : UIView
{
    ABEditorController *_editingController;
    UIScroller *_scroller;
    UIKeyboard *_keyboard;
    UIDatePicker *_datePicker;
    BOOL _reallyNeedsLayout;
}

- (id)initWithSize:(struct CGSize)fp8;
- (void)setEditingController:(id)fp8;
- (id)updateButtonBarAndKeyboard:(BOOL)fp8 withType:(int)fp12 datePickerDelegate:(id)fp16;
- (void)update;
- (BOOL)becomeFirstResponder;
- (void)setNeedsLayout;
- (void)layoutSubviews;
- (id)editorModelForLayer:(id)fp8;
- (void)editCountryCodeForItemEditorLayer:(id)fp8;
- (void)editLabelForItemEditorLayer:(id)fp8 additionalLabels:(id)fp12 property:(int)fp16;
- (void)fieldEndedEditing:(id)fp8;
- (void)itemEditorDidRefreshUI:(id)fp8;
- (void)itemFieldTextChanged:(id)fp8;
- (void)drawRect:(struct CGRect)fp8;

@end

