/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIView.h"

@class UIPreferencesTable;

@interface ABCardPropertyPicker : UIView
{
    UIPreferencesTable *_table;
    struct __CFArray *_properties;
    id _delegate;
}

- (id)initWithFrame:(struct CGRect)fp8;
- (void)dealloc;
- (void)setProperties:(struct __CFArray *)fp8;
- (void)setDelegate:(id)fp8;
- (void)deselectAllRowsWithAnimation:(BOOL)fp8;
- (void)tableSelectionDidChange:(id)fp8;
- (int)numberOfGroupsInPreferencesTable:(id)fp8;
- (int)preferencesTable:(id)fp8 numberOfRowsInGroup:(int)fp12;
- (id)preferencesTable:(id)fp8 cellForRow:(int)fp12 inGroup:(int)fp16;
- (BOOL)table:(id)fp8 showDisclosureForRow:(int)fp12;

@end

