/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <AddressBookUI/ABAbstractCardView.h>

@interface ABCardViewer : ABAbstractCardView
{
}

+ (struct __CFArray *)copyDefaultDisplayedProperties;
- (void)setAllowsDeletion:(BOOL)fp8;
- (void)setEditing:(BOOL)fp8 animated:(BOOL)fp12;
- (void)setTagLine:(id)fp8;
- (BOOL)performDefaultActionForPerson:(void *)fp8 property:(int)fp12 identifier:(int)fp16;
- (void)reloadNameData;

@end

