/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIPreferencesTableCell.h"

@class ABCardTableController, UIImageView;

@interface ABCardTableCell : UIPreferencesTableCell
{
    UIImageView *_badgeView;
    ABCardTableController *_tableController;
    struct {
        unsigned int multiLine:1;
        unsigned int isFavorite:1;
        unsigned int isNameCell:1;
        unsigned int isAddItem:1;
        unsigned int noDeleteAnimation:1;
        unsigned int reserved:26;
    } _itemFlags;
}

- (id)initWithProperty:(int)fp8 cardTableController:(id)fp12;
- (void)dealloc;
- (struct CGRect)abValueLabelFrame;
- (id)valueTextLabel;
- (id)createRemoveControl;
- (void)setIsFavorite:(BOOL)fp8;
- (void)setIsNameCell:(BOOL)fp8;
- (void)setIsAddItem:(BOOL)fp8;
- (id)_badgeView;
- (void)_updateFavoritesBadge:(BOOL)fp8;
- (void)layoutSubviews;
- (void)setAnimatesOnDelete:(BOOL)fp8;
- (BOOL)removeControl:(id)fp8 shouldRemoveTarget:(id)fp12;
- (void)removeControl:(id)fp8 willRemoveTarget:(id)fp12;
- (void)removeControl:(id)fp8 didRemoveTarget:(id)fp12;

@end

