/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIView.h"

@class NSString, UIColor;

@interface ABCardTitleView : UIView
{
    NSString *_title;
    NSString *_label;
    NSString *_status;
    UIColor *_titleColor;
    UIColor *_titleBevelColor;
    float _titleFontSize;
    BOOL _leftAligned;
}

- (id)initWithFrame:(struct CGRect)fp8;
- (void)dealloc;
- (void)drawLeftAlignedWithClipRect:(struct CGRect)fp8;
- (void)drawCenteredWithClipRect:(struct CGRect)fp8;
- (void)drawRect:(struct CGRect)fp8;
- (void)setTitleFontSize:(float)fp8;
- (void)setTitleColor:(id)fp8;
- (id)title;
- (void)setTitle:(id)fp8;
- (void)setTitleBevelColor:(id)fp8;
- (void)setLabel:(id)fp8;
- (void)setStatus:(id)fp8;
- (void)setLeftAligned:(BOOL)fp8;

@end

