/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIControl.h"

@class ABCardNameControl;

@interface ABCardNameInternalView : UIControl
{
    ABCardNameControl *_cardNameControl;
    BOOL _drawName;
}

- (id)initWithSize:(struct CGSize)fp8 cardNameControl:(id)fp16 namePart:(BOOL)fp20;
- (void)setFrame:(struct CGRect)fp8;
- (void)drawRect:(struct CGRect)fp8;

@end

