/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIView.h"

@class NSString;

@interface ABCardItemEditorEntryLayer : UIView
{
    NSString *_value;
}

- (void)setDelegate:(id)fp8;
- (BOOL)endEditing:(BOOL)fp8;
- (void)setValue:(id)fp8;
- (id)text;
- (void)drawRect:(struct CGRect)fp8;
- (void)dealloc;

@end

