/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIView.h"

@class NSMutableArray, NSMutableDictionary;

@interface ABCardRecentDatesView : UIView
{
    NSMutableDictionary *_timeByDay;
    NSMutableArray *_orderedDays;
    BOOL _recomputeFrameToFit;
}

- (id)initWithFrame:(struct CGRect)fp8;
- (void)dealloc;
- (struct CGRect)frameToFit;
- (void)setDates:(id)fp8;
- (void)drawRect:(struct CGRect)fp8;

@end

