/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

#import "ABContentControllerProtocol-Protocol.h"

@class UIView;

@interface ABContentController : NSObject <ABContentControllerProtocol>
{
    void *_addressBook;
    id _contentControllerDelegate;
    UIView *_contentLayer;
}

- (id)initWithContentControllerDelegate:(id)fp8 addressBook:(void *)fp12;
- (void)dealloc;
- (void *)addressBook;
- (id)contentControllerDelegate;
- (void)setContentControllerDelegate:(id)fp8;
- (BOOL)table:(id)fp8 showDisclosureForRow:(int)fp12;
- (id)contentView;
- (void)cleanUpContentLayer;
- (BOOL)contentViewIsVisible;
- (void)displayScrollerIndicators;
- (void)back:(BOOL)fp8 save:(BOOL)fp12;
- (void)reload;
- (void)preloadController;

@end

