/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIView.h"

@class NSArray, NSString, UISectionList;

@interface ABCountryCodePicker : UIView
{
    id _delegate;
    id _editedItem;
    NSString *_selectedCountryCode;
    UISectionList *_sectionList;
    NSArray *_sortedRegions;
    NSArray *_sortedRegionsIndices;
    NSArray *_sortedCountryInfos;
    unsigned int _manuallySettingRowSelection:1;
}

- (id)initWithFrame:(struct CGRect)fp8;
- (void)dealloc;
- (void)setEditedItem:(id)fp8;
- (id)editedItem;
- (void)_setSelectedCountryCode:(id)fp8;
- (void)setSelectedCountryCode:(id)fp8;
- (id)selectedCountryCode;
- (void)reloadCountryCodes;
- (void)setDelegate:(id)fp8;
- (void)buildUI;
- (void)_didEndPickingAndConfirmed:(BOOL)fp8 animate:(BOOL)fp12;
- (void)tableRowSelected:(id)fp8;
- (int)numberOfRowsInTable:(id)fp8;
- (id)table:(id)fp8 cellForRow:(int)fp12 column:(id)fp16 reusing:(id)fp20;
- (int)numberOfSectionsInSectionList:(id)fp8;
- (id)sectionList:(id)fp8 titleForSection:(int)fp12;
- (int)sectionList:(id)fp8 rowForSection:(int)fp12;
- (void)back:(BOOL)fp8 save:(BOOL)fp12;
- (void)reload;

@end

