/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <AddressBookUI/ABContentController.h>

@class NSMutableArray;

@interface ABEditorController : ABContentController
{
    NSMutableArray *_editorItems;
    unsigned int _allowsLabels;
}

- (void)dealloc;
- (id)contentView;
- (void)setEditorItems:(id)fp8;
- (id)editorItems;
- (BOOL)editorsNeedAllTheScrollingTheyCanGet;
- (void)cleanUpContentLayer;
- (BOOL)hasChanges:(char *)fp8 commit:(BOOL)fp12 force:(BOOL)fp16;
- (BOOL)hasTextInFields;
- (void)commitChangesAndSave:(BOOL)fp8;
- (void)keyboardAccepted:(id)fp8;
- (void)keyboardCancelled:(id)fp8;
- (void)back:(BOOL)fp8 save:(BOOL)fp12;
- (void)reload;
- (void)navigationBar:(id)fp8 buttonClicked:(int)fp12;

@end

