/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class ABCardItemEditorLayer, NSString;

@interface ABEditorModel : NSObject
{
    void *_person;
    int _property;
    int _identifier;
    id _originalValue;
    id _insertedValue;
    NSString *_originalLabel;
    ABCardItemEditorLayer *_subeditorLayer;
}

- (id)initWithPerson:(void *)fp8 property:(int)fp12 identifier:(int)fp16 insertedValue:(id)fp20;
- (void)labelDeleted:(id)fp8;
- (void)dealloc;
- (id)description;
- (int)property;
- (int)identifier;
- (void *)person;
- (id)value;
- (id)insertedValue;
- (id)subeditorLayer;
- (BOOL)hasChanges;
- (BOOL)atleastOneFieldHasData;
- (void)updateRecord;

@end

