/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableArray;

@interface ABFavoritesList : NSObject
{
    NSMutableArray *_list;
    struct __CFDictionary *_uidToEntry;
    struct {
        unsigned int dirty:1;
        unsigned int postCount:1;
        unsigned int needsReload:1;
        unsigned int unused:29;
    } _flags;
}

+ (id)sharedInstance;
- (void)_initializeList;
- (id)init;
- (void)dealloc;
- (void)_scheduleSave;
- (id)entries;
- (BOOL)isFull;
- (id)entriesForPerson:(void *)fp8;
- (id)entryWithIdentifier:(int)fp8 forPerson:(void *)fp12;
- (BOOL)containsEntryWithIdentifier:(int)fp8 forPerson:(void *)fp12;
- (BOOL)addEntryForPerson:(void *)fp8 property:(int)fp12 withIdentifier:(int)fp16;
- (void)_addEntryToMap:(id)fp8;
- (void)_removeEntryFromMap:(id)fp8 withUid:(int)fp12;
- (void)_applicationWillSuspend:(id)fp8;
- (void)_entryIdentityChanged:(id)fp8;
- (void)_postChangeNotification;
- (void)_listChangedExternally;
- (void)addEntry:(id)fp8;
- (void)removeEntryAtIndex:(int)fp8;
- (void)moveEntryAtIndex:(int)fp8 toIndex:(int)fp12;
- (BOOL)_writeFavoritesToFile:(id)fp8;
- (void)save;
- (void)recacheIdentitiesSoon;
- (void)_delayedLookup;
- (BOOL)entryIsDuplicateAndThusRemoved:(id)fp8 oldUid:(int)fp12;

@end

