/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <AddressBookUI/ABFavoritesEntry.h>

@interface ABFavoritesEntry (Lookup)
+ (void)_runLookup;
- (void)_queueLookup;
- (void)_unqueueLookup;
- (void)_postEntryChanged;
- (void)_lookupNotFound;
- (void)_lookupChanged:(id)fp8;
@end

