/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <AddressBookUI/ABPropertyGroup.h>

@interface ABFilteringPropertyGroup : ABPropertyGroup
{
    struct __CFArray *_values;
    struct __CFArray *_labels;
    struct __CFArray *_identifiers;
}

- (id)initWithRecord:(void *)fp8 property:(int)fp12 policy:(void *)fp16 cardController:(id)fp20 filter:(id)fp24;
- (void)dealloc;
- (unsigned int)propertyCount;
- (id)copyStringValueAtIndex:(int)fp8;
- (id)copyLabelAtIndex:(int)fp8;

@end

