/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <AddressBookUI/ABGroupWrapper.h>

@interface ABGlobalGroupWrapper : ABGroupWrapper
{
}

+ (id)createGlobalGroupWrapperWithAddressBook:(void *)fp8;
- (BOOL)isGlobalWrapper;
- (id)name;
- (BOOL)isEqual:(id)fp8;

@end

