/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIView.h"

@class NSString, UIImage;

@interface ABImageWellLabelView : UIView
{
    NSString *_label;
    UIImage *_editOverlayImage;
    UIImage *_maskImage;
}

- (id)initWithFrame:(struct CGRect)fp8;
- (void)dealloc;
- (void)setLabel:(id)fp8;
- (void)setEditOverlayImage:(id)fp8;
- (void)setMaskImage:(id)fp8;
- (void)drawRect:(struct CGRect)fp8;

@end

