/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIViewController.h"

@class ABEditorModel, ABItemLabelPicker, NSArray;

@interface ABLabelPickerViewController : UIViewController
{
    ABEditorModel *_model;
    NSArray *_additionalLabels;
    int _property;
    ABItemLabelPicker *_labelPicker;
    id _delegate;
}

- (id)initWithModel:(id)fp8 additionalLabels:(id)fp12 property:(int)fp16;
- (void)dealloc;
- (void)setDelegate:(id)fp8;
- (struct CGSize)fullScreenContentSize;
- (id)labelPicker;
- (void)itemLabelPicker:(id)fp8 endedWithSelectionConfirmed:(BOOL)fp12 animate:(BOOL)fp16;
- (id)itemLabelPickerPresentSimpleTextInputLayerWithContext:(id)fp8;
- (void)itemLabelPicker:(id)fp8 dismissSimpleTextInputLayer:(id)fp12 afterSelectionConfirmed:(BOOL)fp16;
- (void)viewWillAppear:(BOOL)fp8;
- (void)loadView;
- (void)setEditing:(BOOL)fp8 animated:(BOOL)fp12;

@end

