/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UILabel.h"

@class NSArray;

@interface ABMemberCell : UILabel
{
    void *_member;
    NSArray *_namePieces;
    int _highlightIndex;
    BOOL _isGroup;
}

- (id)initWithSize:(struct CGSize)fp8 member:(void *)fp16;
- (void)dealloc;
- (void)setNamePieces:(id)fp8;
- (void)setHighlightIndex:(long)fp8;
- (void *)member;
- (void)setMember:(void *)fp8;
- (void)setGroup:(BOOL)fp8;
- (id)groupName;
- (void)drawContentInRect:(struct CGRect)fp8 selected:(BOOL)fp24;
- (void)drawRect:(struct CGRect)fp8;
- (id)description;
- (id)_automationID;

@end

