/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol ABMembersControllerDelegate <NSObject>
- (void)membersControllerWillStartSearching:(id)fp8;
- (void)membersControllerWillEndSearching:(id)fp8;
- (void)membersController:(id)fp8 needsTitleUpdate:(id)fp12;
- (id)model;
@end

