/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIViewController.h"

@interface ABNewPersonViewController : UIViewController
{
    id <ABNewPersonViewControllerDelegate> _newPersonViewDelegate;
    id _parentGroup;
    id _personView;
    id _helper;
}

- (id)init;
- (void)dealloc;
- (id)newPersonViewDelegate;
- (void)setNewPersonViewDelegate:(id)fp8;
- (void *)addressBook;
- (void)setAddressBook:(void *)fp8;
- (void *)displayedPerson;
- (void)setDisplayedPerson:(void *)fp8;
- (void *)parentGroup;
- (void)setParentGroup:(void *)fp8;
- (id)parentGroupWrapper;
- (void)setParentGroupWrapper:(id)fp8;
- (void)cancel:(id)fp8;
- (void)save:(id)fp8;
- (void)setEditing:(BOOL)fp8 animated:(BOOL)fp12;
- (void)loadView;
- (void)viewWillAppear:(BOOL)fp8;
- (BOOL)canHandleSnapbackIdentifier:(id)fp8 animated:(BOOL)fp12;

@end

