/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIControl.h"

@class ABClippingImageView, ABImageWellLabelView, UIImage, UIView;

@interface ABPersonImageView : UIControl
{
    void *_displayedPerson;
    ABClippingImageView *_personImageView;
    ABClippingImageView *_wellBorderView;
    ABClippingImageView *_currentBorderView;
    ABClippingImageView *_outlineBorderView;
    ABClippingImageView *_editBorderView;
    ABClippingImageView *_pressedView;
    UIView *_bounceImageView;
    ABImageWellLabelView *_wellLabel;
    UIImage *_personImage;
    BOOL _isEditing;
    BOOL _showLabel;
    float _bounceProgress;
    BOOL _isAnimating;
}

+ (id)genericPersonImage;
+ (id)genericOrganizationImage;
+ (id)genericEditPersonImage;
+ (void)loadDefaultImage;
- (id)initWithFrame:(struct CGRect)fp8;
- (void)setHighlighted:(BOOL)fp8;
- (void)dealloc;
- (void)setShowsLabel:(BOOL)fp8 animate:(BOOL)fp12;
- (void)reflow;
- (void)reload;
- (void)setDisplayedPerson:(void *)fp8;
- (void)setPersonImage:(id)fp8;
- (void)finishedEditingAnimation;
- (void)setIsEditing:(BOOL)fp8 animate:(BOOL)fp12;
- (void)bounceAnimationFinished;
- (void)setBouncedImageView:(id)fp8;

@end

