/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

#import "UIModalViewDelegate-Protocol.h"

@class ABPersonViewControllerHelper;

@interface ABPersonViewController_DeletionDelegate : NSObject <UIModalViewDelegate>
{
    ABPersonViewControllerHelper *_controller;
}

- (id)initWithPersonViewController:(id)fp8;
- (void)modalView:(id)fp8 clickedButtonAtIndex:(int)fp12;

@end

