/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableDictionary;

@interface ABRefreshController : NSObject
{
    NSMutableDictionary *_lastAccountRefreshDates;
    NSMutableDictionary *_lastGroupListRefreshDates;
    id <ABAccountSettingsAccountManager> _accountManager;
}

+ (id)sharedInstance;
- (void)dealloc;
- (id)accountManager;
- (BOOL)groupWrapperNeedsRefresh:(id)fp8;
- (BOOL)accountGroupListNeedsRefresh:(id)fp8;
- (void)refreshGroupWrapper:(id)fp8;
- (void)refreshAccountGroupList:(id)fp8;

@end

