/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIView.h"

@class ABRingtoneTableController, UIPreferencesTable;

@interface ABRingtonePicker : UIView
{
    UIPreferencesTable *_table;
    ABRingtoneTableController *_tableController;
    id _delegate;
}

- (id)initWithFrame:(struct CGRect)fp8;
- (id)initWithFrame:(struct CGRect)fp8 avController:(id)fp24;
- (void)dealloc;
- (void)_reloadData;
- (void)setAVController:(id)fp8;
- (void)setShowsDefault:(BOOL)fp8;
- (void)setShowsNone:(BOOL)fp8;
- (void)setNoneString:(id)fp8;
- (void)setDelegate:(id)fp8;
- (void)buildUIWithAVController:(id)fp8;
- (void)ringtoneManagerContentsChanged:(id)fp8;
- (void)setSelectedRingtoneIdentifier:(id)fp8;
- (id)selectedRingtoneIdentifier;
- (void)setPerson:(void *)fp8;
- (void *)person;
- (void)displayScrollerIndicators;
- (void)stopPlaying;
- (void)stopPlayingWithFadeOut:(BOOL)fp8;
- (void)finishedWithPicker;
- (void)ringtoneTableController:(id)fp8 selectedRingtoneWithIdentifier:(id)fp12;
- (void)ringtoneTableController:(id)fp8 willPlayRingtoneWithIdentifier:(id)fp12;

@end

