/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIPreferencesTableCell.h"

@class NSString;

@interface ABRingtoneCell : UIPreferencesTableCell
{
    NSString *_ringtoneIdentifier;
}

- (void)dealloc;
- (void)setRingtoneIdentifier:(id)fp8;
- (id)ringtoneIdentifier;

@end

