/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIView.h"

@interface ABSearchDimmingView : UIView
{
    id _delegate;
}

- (void)mouseDown:(id)fp8;
- (void)mouseUp:(id)fp8;
- (void)touchesBegan:(id)fp8 withEvent:(id)fp12;
- (void)touchesEnded:(id)fp8 withEvent:(id)fp12;
- (id)delegate;
- (void)setDelegate:(id)fp8;

@end

