/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <AddressBookUI/ABServerSearchController.h>

@interface ABServerSearchController (Internal)
- (id)_searchString;
- (void)_beginSearch;
- (void)_endSearchFieldEditing;
- (void)_endEditingAnimationDidFinish;
- (void)_deselectAllRowsWithAnimation:(BOOL)fp8;
- (void)_setCurrentSearchResults:(id)fp8;
- (void)_setCurrentSearchResults:(id)fp8 error:(int)fp12;
- (void)_setCurrentSearchResults:(id)fp8 error:(int)fp12 callDelegate:(BOOL)fp16;
- (void)_clearSearchResults;
- (struct CGRect)_completionTableFrameWithKeyboardVisible;
- (int)_errorForDAStatusCode:(int)fp8;
- (id)_localizedStringForError:(int)fp8;
@end

