/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <AddressBookUI/ABContentController.h>

#import "DASearchQueryConsumer-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "UITextFieldDelegate-Protocol.h"

@class ABDimmingView, ABGroupWrapper, DASearchQuery, NSArray, UIImageView, UILabel, UISearchField, UITableView, UIView;

@interface ABServerSearchController : ABContentController <UITextFieldDelegate, UITableViewDelegate, UITableViewDataSource, DASearchQueryConsumer>
{
    ABGroupWrapper *_selectedGroupWrapper;
    UIView *_searchView;
    UISearchField *_searchField;
    UITableView *_searchResultsTable;
    UITableView *_completionTable;
    UIImageView *_shadowView;
    ABDimmingView *_keyboardDimmingView;
    UILabel *_informationalOverlay;
    NSArray *_currentSearchResults;
    NSArray *_currentResultsAsPeople;
    struct {
        unsigned int resumeToEditing:1;
        unsigned int isEndingEditingWithAnimation:1;
        unsigned int showingCardForPerson:1;
        unsigned int isSearching:1;
        unsigned int hasResults:1;
        unsigned int hasError:1;
        unsigned int unused:26;
    } _flags;
    DASearchQuery *_currentSearchQuery;
}

- (void)dealloc;
- (void)setSelectedGroupWrapper:(id)fp8;
- (id)navigationTitleView;
- (void)viewWillAppear:(BOOL)fp8;
- (void)viewDidAppear:(BOOL)fp8;
- (void)viewWillDisappear:(BOOL)fp8;
- (void)viewDidDisappear:(BOOL)fp8;
- (id)contentView;
- (void)_searchFieldDidChange:(id)fp8;
- (BOOL)textFieldShouldBeginEditing:(id)fp8;
- (BOOL)textFieldShouldReturn:(id)fp8;
- (BOOL)textFieldShouldEndEditing:(id)fp8;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (int)tableView:(id)fp8 accessoryTypeForRowWithIndexPath:(id)fp12;
- (void)resultsReceived:(id)fp8 forSearchQuery:(id)fp12 withStatus:(int)fp16;
- (void)tapInsideDimmingView:(id)fp8;
- (id)selectedGroupWrapper;

@end

