/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol ABSearchHelperDelegate <NSObject>
- (void)searchHelperWillStartSearching:(id)fp8;
- (void)searchHelperWillEndSearching:(id)fp8;
- (void)searchHelper:(id)fp8 didSelectSearchResults:(struct __CFArray *)fp12;
- (void)searchHelper:(id)fp8 didSelectPerson:(void *)fp12 withSearchResults:(struct __CFArray *)fp16;
@end

