/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIView.h"

@class UIKeyboard, UINavigationBar, UIPreferencesTextTableCell;

@interface ABSimpleTextInputLayer : UIView
{
    UIPreferencesTextTableCell *_inputField;
    UIView *_contentView;
    UIKeyboard *_keyboard;
    id _delegate;
    UINavigationBar *_navBar;
    BOOL _lastHasText;
}

- (id)initWithFrame:(struct CGRect)fp8 context:(id)fp24;
- (void)dealloc;
- (id)text;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)setLocalizedNavigationTitle:(id)fp8;
- (id)createEntryFieldForStringValue:(id)fp8;
- (void)buildUI;
- (BOOL)becomeFirstResponder;
- (void)movedFromSuperview:(id)fp8;
- (void)_didEndPickingAndConfirmed:(BOOL)fp8 animate:(BOOL)fp12;
- (void)doneButtonClicked:(id)fp8;
- (void)cancelButtonClicked:(id)fp8;
- (void)navigationBar:(id)fp8 buttonClicked:(int)fp12;
- (void)fieldEndedEditing:(id)fp8;
- (void)back:(BOOL)fp8 save:(BOOL)fp12;
- (void)reload;
- (void)_textValueChanged:(id)fp8;

@end

