/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <AddressBookUI/ABAbstractCardView.h>

@class ABActionsController;

@interface ABUnknownCardViewer : ABAbstractCardView
{
    id _unknownCardViewerDelegate;
    ABActionsController *_actionsController;
}

+ (id)createCardTableControllerWithCardController:(id)fp8;
- (id)initWithFrame:(struct CGRect)fp8;
- (void)dealloc;
- (id)cardTableController;
- (void)setUnknownCardViewerDelegate:(id)fp8;
- (void)setStringValue:(id)fp8 forContactProperty:(int)fp12;
- (id)stringValueForProperty:(int)fp8;
- (id)unknownCardStringValue;
- (int)unknownCardProperty;
- (void)setAllowAddingToAddressBook:(BOOL)fp8;
- (void)setAllowActions:(BOOL)fp8;
- (void)contactInfoButtonClicked:(id)fp8;
- (void)presentPickerUI:(id)fp8;
- (void)addNewContactButtonClicked:(id)fp8;
- (void)addToExistingContactButtonClicked:(id)fp8;
- (void)didEndPickingUI:(id)fp8 didResolveToPerson:(void *)fp12 endSession:(BOOL)fp16;
- (void)peoplePickerDidEndPicking:(id)fp8;
- (void)peoplePicker:(id)fp8 editedPerson:(void *)fp12 property:(int)fp16 identifier:(int)fp20;
- (void)newContactViewCancelled:(id)fp8;
- (void)newContactViewCompleted:(id)fp8 withNewPerson:(void *)fp12;

@end

