/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class ABVCardLexer, ABVCardValueSetter, NSData, NSMutableArray, NSMutableDictionary, NSMutableString, NSString;

@interface ABVCardParser : NSObject
{
    ABVCardLexer *_lexer;
    NSData *_data;
    unsigned int _defaultEncoding;
    BOOL _hasImportErrors;
    ABVCardValueSetter *_valueSetter;
    BOOL _30vCard;
    NSString *_first;
    NSString *_last;
    NSString *_org;
    NSString *_formattedName;
    NSMutableArray *_emails;
    NSMutableArray *_dates;
    NSMutableArray *_phones;
    NSMutableArray *_addresses;
    NSMutableArray *_aims;
    NSMutableArray *_jabbers;
    NSMutableArray *_msns;
    NSMutableArray *_yahoos;
    NSMutableArray *_icqs;
    NSMutableArray *_relatedNames;
    NSMutableArray *_urls;
    NSMutableString *_notes;
    NSMutableString *_otherNotes;
    NSMutableDictionary *_extensions;
    NSString *_uid;
    NSData *_imageData;
    NSMutableArray *_itemParameters;
    NSString *_grouping;
    unsigned int _encoding;
    BOOL _quotedPrintable;
    BOOL _base64;
}

+ (struct __CFArray *)supportedProperties;
- (id)initWithData:(id)fp8;
- (void)dealloc;
- (void)finalize;
- (BOOL)hasImportErrors;
- (void)cleanUpCardState;
- (void)addMultiValues:(id)fp8 toProperty:(unsigned int)fp12;
- (void)addAddressMultiValues;
- (BOOL)parseVERSION;
- (BOOL)parseN;
- (BOOL)parseNICKNAME;
- (BOOL)parseABMaiden;
- (BOOL)parseORG;
- (id)parseSingleValue;
- (id)parseURL;
- (id)genericLabel;
- (id)phoneLabel;
- (BOOL)parseABUID;
- (BOOL)parseEMAIL;
- (BOOL)parseTEL;
- (BOOL)parseADR;
- (BOOL)parseADD;
- (BOOL)parseABExtensionType:(id)fp8;
- (BOOL)addIMValueTo:(id)fp8;
- (id)dateFromISO8601String:(id)fp8;
- (BOOL)parseBDAY;
- (BOOL)parseABDATE;
- (void)parsePhoto:(id)fp8;
- (void)parseABPhoto;
- (void)parseABShowAs;
- (void)parseABOrder;
- (BOOL)parseABReleatedNames;
- (BOOL)parseItem;
- (BOOL)importToPerson:(void *)fp8 foundProperties:(const struct __CFArray **)fp12;
- (BOOL)importToValueSetter:(id)fp8;
- (void *)nextPersonWithLength:(int *)fp8 foundProperties:(const struct __CFArray **)fp12;
- (struct __CFArray *)peopleAndProperties:(const struct __CFArray **)fp8;
- (id)sortedPeopleAndProperties:(const struct __CFArray **)fp8;

@end

