/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableArray, NSString;

@interface ABVCardParameter : NSObject
{
    NSString *_name;
    NSString *_grouping;
    id _value;
    NSMutableArray *_types;
    BOOL _primary;
}

- (id)initWithName:(id)fp8;
- (void)dealloc;
- (void)finalize;
- (void)setValue:(id)fp8;
- (void)addType:(id)fp8;
- (void)addTypes:(id)fp8;
- (id)types;
- (id)name;
- (void)setGrouping:(id)fp8;
- (id)grouping;
- (id)value;
- (BOOL)isPrimary;
- (void)setIsPrimary:(BOOL)fp8;
- (id)description;

@end

