/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@interface ABVCardValueSetter : NSObject
{
}

- (BOOL)setValue:(void *)fp8 forProperty:(unsigned int)fp12;
- (void *)valueForProperty:(unsigned int)fp8;
- (BOOL)setImageData:(id)fp8;
- (id)fullName;
- (void)setValueInTemporaryCache:(void *)fp8 forProperty:(unsigned int)fp12;

@end

