/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSArray, NSMutableData;

@interface ABVCardLexer : NSObject
{
    NSMutableData *_data;
    char *_bytes;
    unsigned int _length;
    unsigned int _peakedPoint;
    unsigned int _cursor;
    BOOL _unicode;
    int _errorCount;
    NSArray *_activeTokenSets;
}

- (id)tokenName:(int)fp8;
- (id)initWithData:(id)fp8;
- (void)dealloc;
- (void)finalize;
- (unsigned int)cursor;
- (int)errorCount;
- (id)tokenSetForLength:(int)fp8;
- (int)nextTokenPeakSingle:(BOOL)fp8 length:(int)fp12;
- (int)nextTokenPeakUnicode:(BOOL)fp8 length:(int)fp12;
- (int)nextTokenPeak:(BOOL)fp8;
- (id)nextQuotedPrintableData;
- (id)nextEscapedCharacter;
- (id)nextSingleByteStringInEncoding:(unsigned int)fp8 quotedPrintable:(BOOL)fp12 stopTokens:(int)fp16 trim:(BOOL)fp20;
- (id)nextUnicodeStringStopTokens:(int)fp8 quotedPrintable:(BOOL)fp12 trim:(BOOL)fp16;
- (id)nextStringInEncoding:(unsigned int)fp8 quotedPrintable:(BOOL)fp12 stopTokens:(int)fp16 trim:(BOOL)fp20;
- (int)tokenAtCursor;
- (id)nextArraySeperatedByToken:(int)fp8 stoppingAt:(int)fp12 inEncoding:(unsigned int)fp16;
- (id)nextUnicodeBase64Line:(char *)fp8;
- (id)nextSingleByteBase64Line:(char *)fp8;
- (id)nextBase64Line:(char *)fp8;
- (id)nextBase64Data;
- (void)advanceToPeakPoint;
- (int)advanceToUnicodeString;
- (int)advanceToSingleByteString;
- (int)advanceToString;
- (BOOL)advanceToToken:(int)fp8 throughTypes:(int)fp12;
- (BOOL)advanceToEOLUnicode;
- (BOOL)advanceToEOLSingle;
- (BOOL)advanceToEOL;
- (BOOL)advancePastEOLUnicode;
- (BOOL)advancePastEOLSingle;
- (BOOL)advancePastEOL;
- (BOOL)atEOF;

@end

