/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <AddressBookUI/ABVCardValueSetter.h>

@interface ABVCardPersonValueSetter : ABVCardValueSetter
{
    void *_person;
    struct __CFArray *_properties;
}

+ (struct __CFArray *)supportedProperties;
- (id)initWithPerson:(void *)fp8;
- (struct __CFArray *)foundProperties;
- (void)dealloc;
- (BOOL)setValue:(void *)fp8 forProperty:(unsigned int)fp12;
- (void *)valueForProperty:(unsigned int)fp8;
- (BOOL)setImageData:(id)fp8;
- (id)fullName;
- (void)setValueInTemporaryCache:(id)fp8 forProperty:(unsigned int)fp12;

@end

