/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

struct CGPoint {
    float _field1;
    float _field2;
};

struct CGRect {
    struct CGPoint _field1;
    struct CGSize _field2;
};

struct CGSize {
    float _field1;
    float _field2;
};

struct _NSRange {
    unsigned int location;
    unsigned int length;
};

struct _NSZone;

struct __CFArray;

struct __CFDictionary;

struct __CFSet;

struct __GSEvent;

typedef struct {
    struct {
    } *_field1;
    int _field2;
    int _field3;
} CDAnonymousStruct3;

typedef struct {
    id _field1;
    unsigned int _field2;
} CDAnonymousStruct2;

typedef struct {
    id _field1;
    id _field2;
    id _field3;
    id _field4;
    struct CGRect _field5;
    void *_field6;
} CDAnonymousStruct1;

