/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIAnimation.h>

@interface _UIOldSliderAnimation : UIAnimation
{
    float _startValue;
    float _endValue;
    BOOL _sendAction;
}

- (void)setProgress:(float)fp8;

@end

