/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIImageView.h>

@class UIView;

@interface _UIPrefTableCellPiece : UIImageView
{
    struct CGRect _originalFrame;
    UIView *_syncPiece;
}

- (id)initWithFrame:(struct CGRect)fp8;
- (void)dealloc;
- (struct CGRect)originalFrame;
- (void)setSyncPiece:(id)fp8;
- (id)syncPiece;

@end

