/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@class UIImage;

@interface _UIPickerViewTopFrame : UIView
{
    UIImage *_leftImage;
    UIImage *_middleImage;
    UIImage *_rightImage;
    float _inset;
}

- (id)initWithFrame:(struct CGRect)fp8;
- (void)setLeftImage:(id)fp8 middleImage:(id)fp12 rightImage:(id)fp16;
- (void)dealloc;
- (BOOL)ignoresMouseEvents;
- (void)setInset:(float)fp8;
- (void)drawRect:(struct CGRect)fp8;

@end

