/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UISlider.h>

@class UIView;

@interface _UISwitchSlider : UISlider
{
    UIView *_labelClipView;
    UIView *_onLabelView;
    UIView *_offLabelView;
    struct {
        unsigned int alternateColors:1;
        unsigned int shouldFlipValue:1;
        unsigned int reserved:30;
    } _switchFlags;
}

- (id)init;
- (id)initWithFrame:(struct CGRect)fp8;
- (void)dealloc;
- (id)createThumbView;
- (void)setAlternateColors:(BOOL)fp8;
- (void)_initImages;
- (void)_initSubviews;
- (id)currentThumbImage;
- (struct CGRect)trackRectForBounds:(struct CGRect)fp8;
- (struct CGRect)thumbRectForBounds:(struct CGRect)fp8 trackRect:(struct CGRect)fp24 value:(float)fp40;
- (void)updateOnLabelRectForBounds:(struct CGRect)fp8;
- (void)updateOffLabelRectForBounds:(struct CGRect)fp8;
- (struct CGSize)sizeThatFits:(struct CGSize)fp8;
- (void)_layoutSubviewsForBoundsChange:(BOOL)fp8;
- (BOOL)beginTrackingAt:(struct CGPoint)fp8 withEvent:(struct __GSEvent *)fp16;
- (BOOL)continueTrackingAt:(struct CGPoint)fp8 previous:(struct CGPoint)fp16 withEvent:(struct __GSEvent *)fp24;
- (void)endTrackingAt:(struct CGPoint)fp8 previous:(struct CGPoint)fp16 withEvent:(struct __GSEvent *)fp24;
- (BOOL)cancelMouseTracking;
- (void)mouseUp:(struct __GSEvent *)fp8;
- (BOOL)beginTrackingWithTouch:(id)fp8 withEvent:(id)fp12;
- (BOOL)continueTrackingWithTouch:(id)fp8 withEvent:(id)fp12;
- (void)endTrackingWithTouch:(id)fp8 withEvent:(id)fp12;
- (void)cancelTrackingWithEvent:(id)fp8;
- (void)touchesEnded:(id)fp8 withEvent:(id)fp12;
- (void)sendAction:(SEL)fp8 to:(id)fp12 forEvent:(id)fp16;
- (void)sendAction:(SEL)fp8 toTarget:(id)fp12 forEvent:(struct __GSEvent *)fp16;

@end

