/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@class UITableView, UITableViewCell;

@interface _UITableViewSeparatorView : UIView
{
    UITableViewCell *_tableCell;
    UITableView *_table;
}

- (id)initWithTableCell:(id)fp8;
- (id)initWithFrame:(struct CGRect)fp8 withTable:(id)fp24;
- (void)drawRect:(struct CGRect)fp8;

@end

