/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@class NSIndexPath, NSTimer, UIShadowView, UITableViewCell;

@interface _UITableViewReorderingSupport : NSObject
{
    UITableViewCell *_reorderedCell;
    NSIndexPath *_initialIndexPath;
    NSIndexPath *_targetIndexPath;
    unsigned int _oldShowHorizontalScrollIndicator:1;
    unsigned int _oldShowVerticalScrollIndicator:1;
    unsigned int _bottomShadowNeedsToMove:1;
    unsigned int _reserved:29;
    NSTimer *_autoscrollTimer;
    UIShadowView *_topShadowView;
    UIShadowView *_bottomShadowView;
}

@end

