/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "DOMHTMLAreaElement.h"

@interface DOMHTMLAreaElement (UIWebViewScrubbingExtensions)
- (struct CGRect)boundingBoxAtPoint:(struct CGPoint)fp8;
- (struct _WKQuad)absoluteQuadAtPoint:(struct CGPoint)fp8;
- (id)boundingBoxesAtPoint:(struct CGPoint)fp8;
- (id)absoluteQuadsAtPoint:(struct CGPoint)fp8;
@end

