/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "DOMHTMLInputElement.h"

@interface DOMHTMLInputElement (UIWebViewAdditions)
- (id)textInputTraits;
- (id)text;
- (BOOL)isSecure;
- (BOOL)isTextControl;
- (Class)formPeripheralClass;
- (BOOL)canBecomeFirstResponder;
- (id)calloutTitle;
- (id)calloutSubtitle;
- (BOOL)isLikelyToBeginPageLoad;
@end

