/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "DOMHTMLSelectElement.h"

@interface DOMHTMLSelectElement (UIWebViewAdditions)
- (Class)formPeripheralClass;
- (int)itemCount;
- (id)itemAtIndex:(int)fp8;
- (void)selectItemAtIndex:(int)fp8;
- (int)indexOfSelectedItem;
- (BOOL)canBecomeFirstResponder;
- (id)calloutTitle;
- (id)calloutSubtitle;
@end

