/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "DOMNode.h"

@interface DOMNode (UIWebViewAdditions)
+ (id)approvedFocusNode;
- (id)calloutTitle;
- (id)calloutSubtitle;
- (void)setApprovedFocus:(BOOL)fp8;
- (BOOL)hasApprovedFocus;
- (BOOL)canBecomeFirstResponder;
- (struct CGRect)boundingBoxAtPoint:(struct CGPoint)fp8;
- (struct _WKQuad)absoluteQuadAtPoint:(struct CGPoint)fp8;
- (id)boundingBoxesAtPoint:(struct CGPoint)fp8;
- (id)absoluteQuadsAtPoint:(struct CGPoint)fp8;
- (BOOL)showsTapHighlight;
- (id)tapHighlightColor;
- (BOOL)touchCalloutEnabled;
- (struct CGRect)convertRect:(struct CGRect)fp8 toView:(id)fp24;
- (BOOL)isLikelyToBeginPageLoad;
- (BOOL)hasText;
- (BOOL)isTextControl;
@end

