/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@class NSString, UIFont;

@interface InlineCandidateCell : UIView
{
    NSString *_candidate;
    unsigned int _index;
    UIFont *_font;
    struct CGSize _stringImageSize;
    BOOL _highlighted;
    id _target;
    SEL _action;
    BOOL _lastItem;
    BOOL _dontDrawRightEdge;
}

- (id)initWithCandidate:(id)fp8 andIndex:(unsigned int)fp12 withFontSize:(float)fp16 target:(id)fp20 action:(SEL)fp24;
- (void)dealloc;
- (struct CGSize)stringImageSize;
- (unsigned int)index;
- (void)dontDrawRightEdge:(BOOL)fp8;
- (void)setLastItem:(BOOL)fp8;
- (BOOL)ignoresMouseEvents;
- (void)setHighlighted:(BOOL)fp8;
- (void)drawRect:(struct CGRect)fp8;

@end

