/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@class NSString;

@interface KBCandidateCell : UIView
{
    NSString *_candidate;
    unsigned int _index;
    struct CGSize _stringImageSize;
    BOOL _isLastInLine;
    BOOL _highlighted;
    float _atBottom;
    id _target;
    SEL _action;
    BOOL _drawDone;
}

+ (id)font;
- (id)initWithCandidate:(id)fp8 andIndex:(unsigned int)fp12 target:(id)fp16 action:(SEL)fp20;
- (void)dealloc;
- (struct CGSize)stringImageSize;
- (unsigned int)index;
- (void)setGap:(float)fp8;
- (float)dividorOriginX;
- (void)setLastInLine:(BOOL)fp8;
- (void)setAtBottom:(BOOL)fp8;
- (void)drawRect:(struct CGRect)fp8;
- (void)setHighlighted:(BOOL)fp8;
- (void)mouseUp:(struct __GSEvent *)fp8;
- (void)touchesEnded:(id)fp8 withEvent:(id)fp12;

@end

