/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSThread.h"

@class NSMutableArray;

@interface KBSearchThread : NSThread
{
    NSMutableArray *_queue;
}

- (id)init;
- (void)dealloc;
- (void)main;
- (void)addSearch:(id)fp8;
- (void)cancelAll;

@end

