/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@class NSData, NSMutableArray, NSString, ShiftMatcher, WordInfo;

@interface KBWordSearch : NSObject
{
    WordInfo *_learnDict[200];
    int _dictTopIndex;
    int _dictBottomIndex;
    NSMutableArray *_abPhoneticNamePairs;
    BOOL _isRegisteringABEntries;
    int _maxCands;
    NSMutableArray *_candidates;
    NSMutableArray *_emptyCandidates;
    int _lastConnection[10];
    int _lastConnections;
    int _searchMode;
    ShiftMatcher *_css[100];
    int _ncands;
    int _linkInd;
    int *_exactMatchArray;
    int _exactMatchCapacity;
    int _exactMatchCount;
    int _prefixMatchArray[10];
    int _prefixMatchCount;
    int _expandMatchStack[10];
    int _numberOfConnectionCands[10];
    CDAnonymousStruct8 *_expandExactArray;
    int _expandExactCapacity;
    int _expandExactCount;
    CDAnonymousStruct8 _expandPrefixArray[5];
    int _expandPrefixCount;
    char *_wordlist;
    struct _DictEntry *_dict;
    NSData *_dictData;
    void *_dictDataBytes;
    NSString *_deletedString;
    NSString *_deletedPat;
    int *_dictLink;
    int *_connectionLink;
    void *_candTrie;
    BOOL _isAddingExactMatch;
    BOOL _youTubeMode;
    BOOL _insertInputStringInCandidate;
    BOOL _kanaMode;
    NSString *_currentInputMode;
    BOOL _learningDictSaved;
}

- (id)a_matcher:(char *)fp8 withAmbiguity:(int)fp12;
- (id)c_matcher:(char *)fp8 withAmbiguity:(int)fp12;
- (int)dictHash:(char *)fp8;
- (id)learndicFileName;
- (void)_loadLearningDictionary;
- (void)saveLearningDictionary;
- (void)registerNamesFromAddressBook;
- (void)reallocExactMatchArray;
- (void)reallocExpandExactArray;
- (id)initKBWordSearch:(BOOL)fp8 dictPath:(id)fp12;
- (void)dealloc;
- (int)addCandidate:(char *)fp8 yomi:(char *)fp12 inConnection:(int)fp16 outConnection:(int)fp20 nCands:(int)fp24 weight:(int)fp28 type:(int)fp32;
- (BOOL)noDupWithArray:(int *)fp8 arrayCount:(int)fp12 index:(int)fp16;
- (void)addNeededCandidates;
- (BOOL)generateCand1:(int)fp8 connection:(int)fp12 matchedLen:(int)fp16 level:(int)fp20 patLen:(int)fp24;
- (BOOL)generateCand0:(int)fp8 matchedLen:(int)fp12 level:(int)fp16;
- (id)getCandidates0:(id)fp8 fixPat:(id)fp12;
- (id)getCandidates1:(id)fp8 fixPat:(id)fp12;
- (const char *)yomiInEngineRepresentation:(id)fp8;
- (id)wildcardString;
- (id)getCandidates:(id)fp8;
- (id)getCandidates:(id)fp8 fixPat:(id)fp12;
- (void)registABEntriesWithWord:(id)fp8 andYomi:(id)fp12;
- (void)regist:(id)fp8 withYomi:(id)fp12 inConnection:(int)fp16 outConnection:(int *)fp20 outConnections:(int)fp24;
- (id)lastWord;
- (void)setSearchMode:(int)fp8;
- (void)setYouTubeMode:(BOOL)fp8;
- (void)setInsertInputStringInCandidate:(BOOL)fp8;
- (void)setMaxCands:(int)fp8;
- (void)setDeletedString:(id)fp8;
- (id)deletedString;
- (void)setDeletedPat:(id)fp8;
- (id)deletedPat;
- (void)cancel;
- (BOOL)isCancelled;
- (BOOL)checkGSEventQueueContainsMouseEvent;
- (void)getCandidatesAsyncForString:(id)fp8 target:(id)fp12 action:(SEL)fp16;
- (void)_getCandidatesOnThread:(id)fp8;

@end

