/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@class KBWordSearch, NSString;

@interface KBWordSearchThreadParameters : NSObject
{
    KBWordSearch *_kbws;
    NSString *_inputString;
    id _target;
    SEL _action;
    BOOL _cancelled;
}

- (id)initWithKBWordSearch:(id)fp8 inputString:(id)fp12 target:(id)fp16 action:(SEL)fp20;
- (void)dealloc;
- (BOOL)isCancelled;
- (void)setCancelled:(BOOL)fp8;
- (SEL)action;
- (id)target;
- (id)inputString;
- (id)kbws;

@end

