/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSArray.h"

@interface NSArray (UICollectionAdditions_Performance)
- (id)initWithObjectsFromArray:(id)fp8 range:(struct _NSRange)fp12;
- (void)makeObjectsPerformSelector:(SEL)fp8 object:(id)fp12 range:(struct _NSRange)fp16;
@end

