/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSArray.h"

@interface NSArray (UIKBExtras)
- (id)_kb_firstObject;
- (BOOL)_kb_firstTwoObjectsEqual;
- (BOOL)_kb_firstObjectsEqual:(unsigned int)fp8;
@end

