/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSBundle.h"

@interface NSBundle (NSBundleAdditions)
- (id)loadNibNamed:(id)fp8 owner:(id)fp12 options:(id)fp16;
@end

