/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Foundation/NSIndexPath.h>

@interface NSIndexPath (UITableView)
+ (id)indexPathForRow:(unsigned int)fp8 inSection:(unsigned int)fp12;
- (unsigned int)section;
- (unsigned int)row;
@end

