/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSMutableArray.h"

@interface NSMutableArray (UICollectionAdditions_Performance)
- (void)addObjectsFromArray:(id)fp8 range:(struct _NSRange)fp12;
@end

