/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@class NSArray, UIImage;

@interface UIAccentedCharacterView : UIView
{
    NSArray *m_characters;
    unsigned int m_count;
    int m_expansion;
    int m_orientation;
    float m_stringWidth;
    UIImage *m_endcapImage;
    UIImage *m_middleImage;
    UIImage *m_grabberImage;
    struct CGPoint m_endcapPoint;
    struct CGRect m_middleToRect;
    struct CGRect m_middleFromRect;
    struct CGPoint m_grabberPoint;
    UIView *m_selectedView;
    unsigned int m_selectedIndex;
    BOOL m_dragged;
    struct CGPoint m_dragPoint;
}

- (id)initWithFrame:(struct CGRect)fp8 variants:(id)fp24 expansion:(int)fp28 orientation:(int)fp32;
- (void)dealloc;
- (void)setSelectedIndex:(int)fp8;
- (void)sendSelectedString;
- (BOOL)canHandleHandEvent:(struct __GSEvent *)fp8;
- (void)mouseDown:(struct __GSEvent *)fp8;
- (void)mouseDragged:(struct __GSEvent *)fp8;
- (void)mouseUp:(struct __GSEvent *)fp8;
- (void)touchesBegan:(id)fp8 withEvent:(id)fp12;
- (void)touchesMoved:(id)fp8 withEvent:(id)fp12;
- (void)touchesEnded:(id)fp8 withEvent:(id)fp12;
- (void)touchesCancelled:(id)fp8 withEvent:(id)fp12;
- (void)drawRect:(struct CGRect)fp8;

@end

