/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@interface UIAcceleration : NSObject
{
    double timestamp;
    double x;
    double y;
    double z;
}

- (double)z;
- (void)setZ:(double)fp8;
- (double)y;
- (void)setY:(double)fp8;
- (double)x;
- (void)setX:(double)fp8;
- (double)timestamp;
- (void)setTimestamp:(double)fp8;

@end

