/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIImageAndTextTableCell.h>

@interface UIAlertSheetTableCell : UIImageAndTextTableCell
{
}

- (id)initWithFrame:(struct CGRect)fp8;
- (void)setBackgroundColor:(id)fp8;
- (void)updateHighlightColors;
- (void)drawSeparatorInRect:(struct CGRect)fp8;

@end

