/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@interface UIAnimation : NSObject
{
    id _target;
    SEL _action;
    id _delegate;
    struct {
        unsigned int curve:4;
        unsigned int tvOutput:1;
        unsigned int reserved:27;
    } _animationFlags;
    double _startTime;
    double _duration;
    int _state;
}

- (id)initWithTarget:(id)fp8;
- (void)stopAnimation;
- (id)target;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)setAction:(SEL)fp8;
- (SEL)action;
- (void)setAnimationCurve:(int)fp8;
- (void)setProgress:(float)fp8;
- (float)progressForFraction:(float)fp8;
- (void)dealloc;

@end

