/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@class UIImage;

@interface UIAutocorrectImageView : UIView
{
    UIImage *m_image;
}

+ (id)imageWithMaskingView:(id)fp8 maskingRect:(struct CGRect)fp12;
- (id)initWithFrame:(struct CGRect)fp8 image:(id)fp24;
- (id)initWithFrame:(struct CGRect)fp8 string:(id)fp24 font:(id)fp28;
- (void)dealloc;
- (void)drawRect:(struct CGRect)fp8;

@end

