/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@class NSTimer;

@interface UIAutoscrollTimer : NSObject
{
    id m_target;
    struct CGPoint m_point;
    int m_directions;
    float m_delta;
    NSTimer *m_timer;
}

- (id)initWithTarget:(id)fp8 point:(struct CGPoint)fp12 directions:(int)fp20 repeatInterval:(double)fp24;
- (void)dealloc;
- (struct CGPoint)point;
- (int)directions;
- (float)delta;
- (void)invalidate;
- (void)timerFired:(id)fp8;

@end

