/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@class NSString, UIFont;

@interface UIAutocorrectStringView : UIView
{
    NSString *m_string;
    UIFont *m_font;
}

- (id)initWithFrame:(struct CGRect)fp8 string:(id)fp24 font:(id)fp28;
- (void)dealloc;
- (void)drawRect:(struct CGRect)fp8;

@end

