/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIBarButtonItem.h>

@interface UIBarButtonItem (Internal)
- (id)nextResponder;
- (void)setView:(id)fp8;
- (id)view;
- (BOOL)isSystemItem;
- (BOOL)isCustomViewItem;
- (int)systemItem;
- (void)_sendAction:(id)fp8 withEvent:(id)fp12;
@end

