/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@class UIBarButtonItem, UIImageView;

@interface UIBarButtonItemProxy : NSObject
{
    UIBarButtonItem *_item;
    UIImageView *_view;
}

- (id)initWithItem:(id)fp8 inToolbar:(id)fp12;
- (void)dealloc;
- (id)item;
- (id)view;

@end

