/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIBarButtonItem.h>

@interface UIBarButtonItem (Static)
- (void)_getSystemItemStyle:(int *)fp8 title:(id *)fp12 image:(id *)fp16 selectedImage:(id *)fp20 forBarStyle:(int)fp24 landscape:(BOOL)fp28 alwaysBordered:(BOOL)fp32;
- (void)_getToolbarEdgeInsets:(CDAnonymousStruct2 *)fp8 forBarStyle:(int)fp12 landscape:(BOOL)fp16 alwaysBordered:(BOOL)fp20;
- (id)createViewForNavigationItem:(id)fp8;
- (id)createViewForToolbar:(id)fp8;
- (void)_updateView;
@end

