/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@interface UIBezierPath : NSObject
{
    struct CGPath *_pathRef;
    float _width;
}

+ (id)bezierPath;
+ (id)bezierPathKnockingOutTopOfRect:(struct CGRect)fp8 withCornerRadius:(float)fp24;
+ (id)bezierPathKnockingOutBottomOfRect:(struct CGRect)fp8 withCornerRadius:(float)fp24;
+ (id)roundedRectBezierPath:(struct CGRect)fp8 withRoundedEdges:(int)fp24;
+ (id)roundedRectBezierPath:(struct CGRect)fp8 withRoundedCorners:(int)fp24 withCornerRadius:(float)fp28;
+ (id)roundedRectBezierPath:(struct CGRect)fp8 withRoundedCorners:(int)fp24 withCornerRadii:(id)fp28;
+ (id)roundedRectBezierPath:(struct CGRect)fp8 withRoundedCorners:(int)fp24 visibleEdges:(int)fp28 cornerRadius:(float)fp32;
- (id)init;
- (void)dealloc;
- (void)moveToPoint:(struct CGPoint)fp8;
- (void)lineToPoint:(struct CGPoint)fp8;
- (void)appendBezierPath:(id)fp8;
- (void)appendBezierPathWithRect:(struct CGRect)fp8;
- (void)appendBezierPathWithOvalInRect:(struct CGRect)fp8;
- (void)appendBezierPathWithOvalInRect:(struct CGRect)fp8 transform:(struct CGAffineTransform)fp24;
- (void)closePath;
- (void)appendBezierPathWithArcWithCenter:(struct CGPoint)fp8 radius:(float)fp16 startAngle:(float)fp20 endAngle:(float)fp24 clockwise:(BOOL)fp28;
- (void)setLineWidth:(float)fp8;
- (void)fill;
- (void)stroke;
- (void)clip;

@end

