/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@class UIColor;

@interface UIBox : UIView
{
    int _corners;
    UIView *_contentView;
    UIColor *_backgroundColor;
}

- (void)dealloc;
- (void)setBackgroundColor:(id)fp8;
- (void)setRoundedCorners:(int)fp8;
- (void)drawRect:(struct CGRect)fp8;
- (void)placeContentLayer;
- (void)setContentView:(id)fp8;
- (id)contentView;

@end

