/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIControl.h>

@class UIFont, UIImageView, UILabel;

@interface UIButton : UIControl <NSCoding>
{
    struct __CFDictionary *_contentLookup;
    UIFont *_font;
    CDAnonymousStruct2 _contentEdgeInsets;
    CDAnonymousStruct2 _titleEdgeInsets;
    CDAnonymousStruct2 _imageEdgeInsets;
    struct CGSize _titleShadowOffset;
    int _lineBreakMode;
    UIImageView *_backgroundView;
    UIImageView *_imageView;
    UILabel *_titleView;
    struct {
        unsigned int reversesTitleShadowWhenHighlighted:1;
        unsigned int adjustsImageWhenHighlighted:1;
        unsigned int adjustsImageWhenDisabled:1;
        unsigned int autosizeToFit:1;
        unsigned int disabledDimsImage:1;
        unsigned int showsTouchWhenHighlighted:1;
        unsigned int buttonType:8;
    } _buttonFlags;
}

+ (id)_defaultContentForType:(int)fp8 andState:(unsigned int)fp12;
+ (id)buttonWithType:(int)fp8;
- (id)initWithFrame:(struct CGRect)fp8;
- (id)initWithCoder:(id)fp8;
- (void)_populateArchivedSubviews:(id)fp8;
- (void)encodeWithCoder:(id)fp8;
- (void)dealloc;
- (int)buttonType;
- (void)setFrame:(struct CGRect)fp8;
- (void)setBounds:(struct CGRect)fp8;
- (void)setSelected:(BOOL)fp8;
- (void)setEnabled:(BOOL)fp8;
- (void)setHighlighted:(BOOL)fp8;
- (id)font;
- (void)setFont:(id)fp8;
- (int)lineBreakMode;
- (void)setLineBreakMode:(int)fp8;
- (CDAnonymousStruct2)contentEdgeInsets;
- (void)setContentEdgeInsets:(CDAnonymousStruct2)fp8;
- (CDAnonymousStruct2)titleEdgeInsets;
- (void)setTitleEdgeInsets:(CDAnonymousStruct2)fp8;
- (struct CGSize)titleShadowOffset;
- (void)setTitleShadowOffset:(struct CGSize)fp8;
- (BOOL)reversesTitleShadowWhenHighlighted;
- (BOOL)reversesTitleShadowOnHighlight;
- (void)setReversesTitleShadowWhenHighlighted:(BOOL)fp8;
- (void)setReversesTitleShadowOnHighlight:(BOOL)fp8;
- (BOOL)adjustsImageWhenHighlighted;
- (void)setAdjustsImageWhenHighlighted:(BOOL)fp8;
- (BOOL)adjustsImageWhenDisabled;
- (void)setAdjustsImageWhenDisabled:(BOOL)fp8;
- (BOOL)showsTouchWhenHighlighted;
- (void)setShowsTouchWhenHighlighted:(BOOL)fp8;
- (CDAnonymousStruct2)imageEdgeInsets;
- (void)setImageEdgeInsets:(CDAnonymousStruct2)fp8;
- (void)setTitle:(id)fp8 forState:(unsigned int)fp12;
- (void)setTitleColor:(id)fp8 forState:(unsigned int)fp12;
- (void)setTitleShadowColor:(id)fp8 forState:(unsigned int)fp12;
- (void)setImage:(id)fp8 forState:(unsigned int)fp12;
- (void)setBackgroundImage:(id)fp8 forState:(unsigned int)fp12;
- (id)titleForState:(unsigned int)fp8;
- (id)titleColorForState:(unsigned int)fp8;
- (id)titleShadowColorForState:(unsigned int)fp8;
- (id)imageForState:(unsigned int)fp8;
- (id)backgroundImageForState:(unsigned int)fp8;
- (id)currentTitle;
- (id)currentTitleColor;
- (id)currentTitleShadowColor;
- (id)currentImage;
- (id)currentBackgroundImage;
- (struct CGRect)backgroundRectForBounds:(struct CGRect)fp8;
- (struct CGRect)contentRectForBounds:(struct CGRect)fp8;
- (struct CGRect)titleRectForContentRect:(struct CGRect)fp8;
- (struct CGRect)imageRectForContentRect:(struct CGRect)fp8;
- (struct CGSize)sizeThatFits:(struct CGSize)fp8;
- (void)layoutSubviews;

@end

