/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIButton.h>

@interface UIButton (UIButtonContentLookup)
- (void)_setContent:(id)fp8 forState:(unsigned int)fp12;
- (void)_setImage:(id)fp8 forStates:(unsigned int)fp12;
- (void)_setBackground:(id)fp8 forStates:(unsigned int)fp12;
- (void)_setTitle:(id)fp8 forStates:(unsigned int)fp12;
- (void)_setTitleColor:(id)fp8 forStates:(unsigned int)fp12;
- (void)_setShadowColor:(id)fp8 forStates:(unsigned int)fp12;
- (id)_contentForState:(unsigned int)fp8;
- (id)_archivableContent:(id *)fp8;
- (void)_takeContentFromArchivableContent:(id)fp8 overrides:(id)fp12;
- (id)_imageForState:(unsigned int)fp8 usesImageForNormalState:(char *)fp12;
- (id)_backgroundForState:(unsigned int)fp8 usesBackgroundForNormalState:(char *)fp12;
- (id)_titleForState:(unsigned int)fp8;
- (id)_titleColorForState:(unsigned int)fp8;
- (id)_shadowColorForState:(unsigned int)fp8;
@end

