/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

#import "NSCoding-Protocol.h"
#import "NSCopying-Protocol.h"

@class NSString, UIColor, UIImage;

@interface UIButtonContent : NSObject <NSCoding, NSCopying>
{
    NSString *title;
    UIImage *image;
    UIImage *background;
    UIColor *titleColor;
    UIColor *shadowColor;
}

- (BOOL)isEmpty;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (id)initWithCoder:(id)fp8;
- (void)encodeWithCoder:(id)fp8;
- (void)dealloc;
- (id)description;
- (id)shadowColor;
- (void)setShadowColor:(id)fp8;
- (id)titleColor;
- (void)setTitleColor:(id)fp8;
- (id)background;
- (void)setBackground:(id)fp8;
- (id)image;
- (void)setImage:(id)fp8;
- (id)title;
- (void)setTitle:(id)fp8;

@end

