/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIDeviceWhiteColor.h>

@interface UICachedDeviceWhiteColor : UIDeviceWhiteColor
{
}

- (void)release;
- (id)retain;
- (int)retainCount;
- (id)autorelease;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (id)copy;
- (void)dealloc;
- (void)finalize;

@end

