/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@class UIColor;

@interface UICheckeredPatternView : UIView
{
    UIColor *m_patternColor;
    UIColor *m_checkerColor;
}

- (id)initWithFrame:(struct CGRect)fp8;
- (void)dealloc;
- (BOOL)_canDrawContent;
- (void)updatePatternColor;
- (id)checkerColor;
- (void)setCheckerColor:(id)fp8;

@end

