/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@class UIImageView;

@interface UIClippedImageView : UIView
{
    UIImageView *m_imageView;
    struct CGRect m_originalFrame;
    struct CGRect m_baseFrame;
}

- (id)initWithFrame:(struct CGRect)fp8 image:(id)fp24;
- (void)dealloc;
- (id)image;
- (void)setImage:(id)fp8;
- (void)setOpaque:(BOOL)fp8;
- (void)setFrame:(struct CGRect)fp8;
- (void)setBaseFrame:(struct CGRect)fp8;
- (struct CGRect)baseFrame;
- (void)setImageOrigin:(struct CGPoint)fp8;
- (void)setOriginAdjustingImage:(struct CGPoint)fp8;

@end

