/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@interface UIColor : NSObject <NSCoding>
{
}

+ (id)colorWithWhite:(float)fp8 alpha:(float)fp12;
+ (id)colorWithHue:(float)fp8 saturation:(float)fp12 brightness:(float)fp16 alpha:(float)fp20;
+ (id)colorWithRed:(float)fp8 green:(float)fp12 blue:(float)fp16 alpha:(float)fp20;
+ (id)colorWithCGColor:(struct CGColor *)fp8;
+ (id)colorWithPatternImage:(id)fp8;
+ (id)blackColor;
+ (id)darkGrayColor;
+ (id)lightGrayColor;
+ (id)whiteColor;
+ (id)grayColor;
+ (UIColor *)clearColor;
+ (id)redColor;
+ (id)greenColor;
+ (id)blueColor;
+ (id)cyanColor;
+ (id)yellowColor;
+ (id)magentaColor;
+ (id)orangeColor;
+ (id)purpleColor;
+ (id)brownColor;
+ (id)lightTextColor;
+ (id)darkTextColor;
+ (id)tableSeparatorDarkColor;
+ (id)tableSeparatorLightColor;
+ (id)tableBackgroundColor;
+ (id)tableSelectionColor;
+ (id)sectionListBorderColor;
+ (id)sectionHeaderBackgroundColor;
+ (id)sectionHeaderOpaqueBackgroundColor;
+ (id)sectionHeaderBorderColor;
+ (id)textFieldAtomBlueColor;
+ (id)textFieldAtomPurpleColor;
- (id)initWithWhite:(float)fp8 alpha:(float)fp12;
- (id)initWithHue:(float)fp8 saturation:(float)fp12 brightness:(float)fp16 alpha:(float)fp20;
- (id)initWithRed:(float)fp8 green:(float)fp12 blue:(float)fp16 alpha:(float)fp20;
- (id)initWithCGColor:(struct CGColor *)fp8;
- (id)initWithPatternImage:(id)fp8;
- (id)initWithCoder:(id)fp8;
- (void)encodeWithCoder:(id)fp8;
- (void)set;
- (void)setFill;
- (void)setStroke;
- (id)colorWithAlphaComponent:(float)fp8;
- (struct CGColor *)CGColor;
- (BOOL)isEqual:(id)fp8;
- (unsigned int)hash;
- (struct CGColor *)cgColor;
- (id)styleString;

@end

