/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIControl.h>

@interface UIControl (Internal)
- (BOOL)_hasActionForEventMask:(int)fp8;
- (void)_sendActionsForEventMask:(int)fp8 withEvent:(struct __GSEvent *)fp12;
- (void)_sendActionsForEvents:(int)fp8 withEvent:(id)fp12;
- (void)_setHighlightOnMouseDown:(BOOL)fp8;
- (void)_delayActions;
- (void)_sendDelayedActions;
- (void)_cancelDelayedActions;
- (BOOL)pointMostlyInside:(struct CGPoint)fp8 forEvent:(struct __GSEvent *)fp16;
- (BOOL)pointMostlyInside:(struct CGPoint)fp8 withEvent:(id)fp16;
@end

