/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@class NSMutableArray;

@interface UIControl : UIView
{
    NSMutableArray *_targetActions;
    struct CGPoint _previousPoint;
    double _downTime;
    struct {
        unsigned int disabled:1;
        unsigned int tracking:1;
        unsigned int touchInside:1;
        unsigned int touchDragged:1;
        unsigned int requiresDisplayOnTracking:1;
        unsigned int highlighted:1;
        unsigned int dontHighlightOnTouchDown:1;
        unsigned int delayActions:1;
        unsigned int allowActionsToQueue:1;
        unsigned int pendingUnhighlight:1;
        unsigned int selected:1;
        unsigned int verticalAlignment:2;
        unsigned int horizontalAlignment:2;
    } _controlFlags;
}

- (id)initWithFrame:(struct CGRect)fp8;
- (id)initWithCoder:(id)fp8;
- (void)encodeWithCoder:(id)fp8;
- (void)dealloc;
- (void)setEnabled:(BOOL)fp8;
- (BOOL)isEnabled;
- (BOOL)isTracking;
- (unsigned int)state;
- (BOOL)isTouchInside;
- (BOOL)cancelMouseTracking;
- (BOOL)cancelTouchTracking;
- (BOOL)beginTrackingWithTouch:(id)fp8 withEvent:(id)fp12;
- (BOOL)continueTrackingWithTouch:(id)fp8 withEvent:(id)fp12;
- (void)endTrackingWithTouch:(id)fp8 withEvent:(id)fp12;
- (void)cancelTrackingWithEvent:(id)fp8;
- (void)setHighlighted:(BOOL)fp8;
- (BOOL)isHighlighted;
- (void)setContentVerticalAlignment:(int)fp8;
- (int)contentVerticalAlignment;
- (void)setContentHorizontalAlignment:(int)fp8;
- (int)contentHorizontalAlignment;
- (void)setSelected:(BOOL)fp8;
- (BOOL)isSelected;
- (id)hitTest:(struct CGPoint)fp8 withEvent:(id)fp16;
- (id)hitTest:(struct CGPoint)fp8 forEvent:(struct __GSEvent *)fp16;
- (void)mouseDown:(struct __GSEvent *)fp8;
- (void)mouseDragged:(struct __GSEvent *)fp8;
- (void)mouseUp:(struct __GSEvent *)fp8;
- (void)touchesBegan:(id)fp8 withEvent:(id)fp12;
- (void)touchesMoved:(id)fp8 withEvent:(id)fp12;
- (void)touchesEnded:(id)fp8 withEvent:(id)fp12;
- (void)touchesCancelled:(id)fp8 withEvent:(id)fp12;
- (void)_didMoveFromWindow:(id)fp8 toWindow:(id)fp12;
- (void)addTarget:(id)fp8 action:(SEL)fp12 forControlEvents:(unsigned int)fp16;
- (void)removeTarget:(id)fp8 action:(SEL)fp12 forControlEvents:(unsigned int)fp16;
- (id)allTargets;
- (unsigned int)allControlEvents;
- (id)actionsForTarget:(id)fp8 forControlEvent:(unsigned int)fp12;
- (void)sendAction:(SEL)fp8 to:(id)fp12 forEvent:(id)fp16;
- (void)sendActionsForControlEvents:(unsigned int)fp8;

@end

