/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@class NSMutableArray;

@interface UICompositeImageView : UIView
{
    NSMutableArray *m_images;
}

- (id)initWithFrame:(struct CGRect)fp8;
- (void)dealloc;
- (void)addImage:(id)fp8;
- (void)addImage:(id)fp8 operation:(int)fp12 fraction:(float)fp16;
- (void)addImage:(id)fp8 toRect:(struct CGRect)fp12 fromRect:(struct CGRect)fp28;
- (void)addImage:(id)fp8 toRect:(struct CGRect)fp12 fromRect:(struct CGRect)fp28 operation:(int)fp44 fraction:(float)fp48;
- (void)removeAllImages;
- (void)drawRect:(struct CGRect)fp8;

@end

