/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIPickerView.h>

#import "UIPickerViewDataSource-Protocol.h"
#import "UIPickerViewDelegate-Protocol.h"

@class NSCalendar, NSDate, NSDateComponents, NSLocale, NSString, NSTimeZone, UIDatePicker, UILabel;

@interface UIDatePickerView : UIPickerView <UIPickerViewDelegate, UIPickerViewDataSource>
{
    int _datePickerMode;
    NSLocale *_locale;
    NSTimeZone *_timeZone;
    NSCalendar *_calendar;
    NSDate *_date;
    NSDate *_minimumDate;
    NSDate *_maximumDate;
    double _countDownDuration;
    int _minuteInterval;
    NSDateComponents *_referenceComponents;
    double _todaySinceReferenceDate;
    NSDateComponents *_todayDateComponents;
    NSString *_amString;
    NSString *_pmString;
    UILabel *_hourLabel;
    UILabel *_minuteLabel;
    UIDatePicker *_datePickerDelegate;
    id _delegateOfDatePicker;
    int _numberOfDaysInCurrentMonth;
    NSDateComponents *_minDateComponents;
    NSDateComponents *_maxDateComponents;
    struct {
        unsigned int dateOrder:2;
        unsigned int timeOrder:2;
        unsigned int weekdayOrder:1;
        unsigned int staggerTimeIntervals:1;
        unsigned int loadingDateOrTime:1;
        unsigned int highlightsToday:1;
        unsigned int reserved:24;
    } _datePickerFlags;
}

- (id)initWithFrame:(struct CGRect)fp8;
- (void)dealloc;
- (id)pickerImageNamePrefix;
- (int)_incrementForElement:(unsigned int)fp8;
- (void)_doneLoadingDateOrTime;
- (BOOL)_showingDate;
- (int)_numberOfDaysInDate:(id)fp8;
- (void)_updateReferenceBits;
- (void)_updateBitsForDate:(id)fp8 andReload:(BOOL)fp12 animateIfNeeded:(BOOL)fp16;
- (void)setCalendar:(id)fp8;
- (void)setLocale:(id)fp8;
- (void)setTimeZone:(id)fp8;
- (void)setDate:(id)fp8;
- (void)setDate:(id)fp8 animated:(BOOL)fp12;
- (void)setMinimumDate:(id)fp8;
- (void)setMaximumDate:(id)fp8;
- (int)hour;
- (int)minute;
- (int)second;
- (id)date;
- (id)_datePickerCellFont;
- (id)_ampmCellFont;
- (id)_hrMinFont;
- (int)_numberOfDaysInWeek;
- (unsigned int)_elementForColumn:(int)fp8;
- (int)_columnForElement:(unsigned int)fp8;
- (int)numberOfComponentsInPickerView:(id)fp8;
- (void)setDatePickerMode:(int)fp8;
- (void)setMinuteInterval:(int)fp8;
- (void)setStaggerTimeIntervals:(BOOL)fp8;
- (int)_incrementedAmountForValue:(int)fp8 withElement:(unsigned int)fp12;
- (void)scrollerDidScroll:(id)fp8;
- (int)pickerView:(id)fp8 numberOfRowsInComponent:(int)fp12;
- (void)_updateRowInColumn:(int)fp8 toValue:(int)fp12 withRepeatingAmount:(int)fp16 element:(unsigned int)fp20 animated:(BOOL)fp24;
- (void)_loadDateAnimated:(BOOL)fp8;
- (void)pickerViewLoaded:(id)fp8;
- (void)_loadDesignatorStrings;
- (void)setDelegate:(id)fp8;
- (int)_selectedHourForColumn:(int)fp8;
- (int)_selectedMinuteForColumn:(int)fp8;
- (int)_minuteForRow:(int)fp8;
- (int)_secondForRow:(int)fp8;
- (void)_setDateComponent:(id)fp8 withElement:(unsigned int)fp12;
- (BOOL)_updateDateOrTime;
- (id)_fadeLabel:(id)fp8 toNewLabelWithString:(id)fp12 ifAnimated:(BOOL)fp16;
- (id)_minutesString;
- (id)_hoursString;
- (void)_updateLabels:(BOOL)fp8;
- (void)pickerView:(id)fp8 didSelectRow:(int)fp12 inComponent:(int)fp16;
- (int)_dayForRow:(int)fp8;
- (int)_hourForRow:(int)fp8;
- (BOOL)_shouldEnableDayForRow:(int)fp8 column:(int)fp12;
- (BOOL)_shouldEnableMonthForRow:(int)fp8 column:(int)fp12;
- (BOOL)_scrollingAnyColumnExcept:(int)fp8;
- (BOOL)_shouldEnableMinuteForValue:(int)fp8 column:(int)fp12;
- (BOOL)_shouldEnableHourForValue:(int)fp8 column:(int)fp12;
- (BOOL)_shouldEnableYearForRow:(int)fp8;
- (BOOL)_shouldEnableWeekMonthDayForCell:(id)fp8;
- (void)scrollerWillStartDragging:(id)fp8;
- (void)_updateEnabledCells:(BOOL)fp8;
- (id)_todayTextColor;
- (void)_ensureTodayIsSet;
- (int)_monthForRow:(int)fp8;
- (void)_setupCell:(id)fp8 atRow:(int)fp12 inColumn:(int)fp16 withElementFlag:(unsigned int)fp20;
- (void)setHighlightsToday:(BOOL)fp8;
- (id)dateComponents;
- (void)setDateComponents:(id)fp8;
- (void)setCountDownDuration:(double)fp8;
- (double)countDownDuration;
- (float)pickerView:(id)fp8 rowHeightForComponent:(int)fp12;
- (float)pickerView:(id)fp8 widthForComponent:(int)fp12;
- (id)pickerView:(id)fp8 viewForRow:(int)fp12 forComponent:(int)fp16 reusingView:(id)fp20;
- (id)shadowColor;
- (id)_createAccessoryViewWithText:(id)fp8 andFont:(id)fp12;
- (id)_createLabelWithString:(id)fp8 above:(id)fp12;
- (void)pickerView:(id)fp8 createdTable:(id)fp12 forColumn:(int)fp16;
- (id)delegateOfDatePicker;
- (void)setDelegateOfDatePicker:(id)fp8;
- (int)minuteInterval;
- (id)maximumDate;
- (id)minimumDate;
- (id)calendar;
- (id)timeZone;
- (id)locale;
- (int)datePickerMode;

@end

