/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIView.h>

#import "UIKeyboardInput-Protocol.h"

@class UITextInputTraits;

@interface UIDefaultKeyboardInput : UIView <UIKeyboardInput>
{
    UITextInputTraits *m_traits;
}

- (void)dealloc;
- (id)textInputTraits;
- (void)forwardInvocation:(id)fp8;
- (id)methodSignatureForSelector:(SEL)fp8;
- (void)takeTraitsFrom:(id)fp8;
- (id)delegate;
- (void)deleteBackward;
- (void)insertText:(id)fp8;
- (void)replaceCurrentWordWithText:(id)fp8;
- (void)setMarkedText:(id)fp8;
- (void)confirmMarkedText:(id)fp8;
- (id)markedText;
- (unsigned short)characterInRelationToCaretSelection:(int)fp8;
- (unsigned short)characterBeforeCaretSelection;
- (unsigned short)characterAfterCaretSelection;
- (id)fontForCaretSelection;
- (id)textColorForCaretSelection;
- (struct CGRect)autocorrectionRect;
- (struct CGRect)rectForNSRange:(struct _NSRange)fp8;
- (struct CGRect)rectContainingCaretSelection;
- (id)wordRangeContainingCaretSelection;
- (id)wordContainingCaretSelection;
- (id)wordInRange:(id)fp8;
- (void)expandSelectionToStartOfWordContainingCaretSelection;
- (int)wordOffsetInRange:(id)fp8;
- (BOOL)spaceFollowsWordInRange:(id)fp8;
- (id)previousNGrams:(unsigned int)fp8;
- (BOOL)hasText;
- (BOOL)hasSelection;
- (BOOL)selectionAtDocumentStart;
- (BOOL)selectionAtSentenceStart;
- (BOOL)selectionAtWordStart;
- (BOOL)rangeAtSentenceStart:(id)fp8;
- (struct _NSRange)selectionRange;
- (id)selectedDOMRange;
- (void)setSelectedDOMRange:(id)fp8 affinityDownstream:(BOOL)fp12;
- (id)rangeByMovingCurrentSelection:(int)fp8;
- (id)rangeByExtendingCurrentSelection:(int)fp8;
- (void)markCurrentWordForAutoCorrection:(id)fp8 correction:(id)fp12;
- (void)moveBackward:(unsigned int)fp8;
- (void)moveForward:(unsigned int)fp8;
- (void)selectAll;
- (void)setText:(id)fp8;
- (id)text;
- (void)updateSelectionWithPoint:(struct CGPoint)fp8;
- (void)setCaretChangeListener:(id)fp8;
- (struct CGRect)caretRect;
- (struct CGRect)convertCaretRect:(struct CGRect)fp8;
- (id)keyboardInputView;
- (BOOL)isShowingPlaceholder;
- (void)setupPlaceholderTextIfNeeded;
- (id)editingDelegate;
- (void)setEditingDelegate:(id)fp8;
- (BOOL)isSecure;
- (void)setSecure:(BOOL)fp8;
- (BOOL)isProxyFor:(id)fp8;

@end

