/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@interface UIDevice : NSObject
{
    int _numDeviceOrientationObservers;
    struct {
        unsigned int orientation:3;
        unsigned int batteryState:2;
    } _deviceFlags;
}

+ (void)initialize;
+ (UIDevice *)currentDevice;
- (id)name;
- (id)model;
- (id)localizedModel;
- (id)systemName;
- (id)systemVersion;
- (id)uniqueIdentifier;
- (void)setOrientation:(int)fp8;
- (int)orientation;
- (void)setBatteryState:(int)fp8;
- (int)batteryState;
- (void)beginGeneratingDeviceOrientationNotifications;
- (void)endGeneratingDeviceOrientationNotifications;
- (BOOL)isGeneratingDeviceOrientationNotifications;

- (BOOL) isWildcat;

@end

