/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@interface UIDefaultFormAssistantDelegate : NSObject
{
}

- (void)formAssistant:(id)fp8 didStartAssistingFormControl:(id)fp12;
- (void)formAssistant:(id)fp8 willStartAssistingFormControl:(id)fp12;
- (void)formAssistant:(id)fp8 didStopAssistingFormControl:(id)fp12;
- (void)formAssistant:(id)fp8 willStopAssistingFormControl:(id)fp12;

@end

