/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@class UIView;

@interface UIFlicker : NSObject
{
    UIView *_target;
    struct CGPoint _startLocation;
    int _throwIterations;
    id _delegate;
    int _mouseUpCount;
    int _mouseDraggedCount;
    float _delay;
    struct CGPoint _offset;
}

- (void)_mouseDraggedMemberListTest;
- (void)_mouseUpMemberListTest;
- (void)_throwMemberListTest;
- (id)init;
- (struct CGPoint)offset;
- (void)setOffset:(struct CGPoint)fp8;
- (void)setTarget:(id)fp8;
- (void)setStartLocation:(struct CGPoint)fp8;
- (void)setIterations:(int)fp8;
- (void)setDelay:(float)fp8;
- (void)setDelegate:(id)fp8;
- (void)run;

@end

