/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIAnimation.h>

@interface UIGestureAnimation : UIAnimation
{
    SEL _progressSelector;
    int _gestureType;
}

- (id)initWithTarget:(id)fp8 progressSelector:(SEL)fp12 gestureType:(int)fp16;
- (void)setProgress:(float)fp8;
- (int)gestureType;

@end

