/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

/*XXX:*/typedef struct {
    float _field1;
    float _field2;
    float _field3;
    float _field4;
    float _field5;
} CDAnonymousStruct11;

@interface UIGradient : NSObject
{
    CDAnonymousStruct11 *_values;
    float _height;
    struct CGShading *_shader;
}

- (id)initVerticalWithValues:(CDAnonymousStruct11 *)fp8;
- (void)fillRect:(struct CGRect)fp8 inContext:(struct CGContext *)fp24;
- (void)fillRect:(struct CGRect)fp8;
- (void)dealloc;

@end

