/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@interface UIGroupInsertionItem : NSObject
{
    int _index;
    struct _NSRange _range;
}

- (id)initWithExistingGroup:(int)fp8 andRowRange:(struct _NSRange)fp12;
- (id)initWithNewGroupBeforeGroup:(int)fp8 andRowCount:(int)fp12;
- (int)groupIndex;
- (struct _NSRange)range;

@end

