/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@class UIBezierPath;

@interface UIGroupTableViewCellDrawnBackground : UIView
{
    int _sectionLocation;
    int _selectionStyle;
    UIBezierPath *_fillPath;
    UIBezierPath *_strokePath;
}

- (id)initWithFrame:(struct CGRect)fp8;
- (void)dealloc;
- (void)_invalidatePaths;
- (void)setFrame:(struct CGRect)fp8;
- (void)setSelectionStyle:(int)fp8;
- (void)setSectionLocation:(int)fp8;
- (void)setSectionLocation:(int)fp8 animated:(BOOL)fp12;
- (void)_createBezierPathWithCornerRadius:(float)fp8 bottomRadius:(float)fp12 animating:(BOOL)fp16;
- (void)drawRect:(struct CGRect)fp8;
- (void)layoutSubviews;
- (int)sectionLocation;
- (int)selectionStyle;

@end

