/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UINavigationController.h>

#import "NSCoding-Protocol.h"

@interface UIImagePickerController : UINavigationController <NSCoding>
{
    unsigned int _sourceType;
    struct {
        unsigned int allowsImageEditing:1;
        unsigned int visible:1;
        unsigned int isCleaningUp:1;
    } _imagePickerFlags;
}

+ (BOOL)_loadPhotoLibraryIfNecessary;
+ (BOOL)isSourceTypeAvailable:(unsigned int)fp8;
- (id)init;
- (id)initWithCoder:(id)fp8;
- (void)_populateArchivedChildViewControllers:(id)fp8;
- (void)encodeWithCoder:(id)fp8;
- (void)setSourceType:(unsigned int)fp8;
- (unsigned int)sourceType;
- (void)setAllowsImageEditing:(BOOL)fp8;
- (BOOL)allowsImageEditing;
- (void)setParentViewController:(id)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (void)_removeAllChildren;
- (id)_createInitialController;
- (void)_setupControllersForCurrentSourceType;
- (void)_autoDismiss;
- (void)_imagePickerDidCancel;
- (void)_imagePickerDidCompleteForImage:(id)fp8 editingInfo:(id)fp12;

@end

