/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIImage.h>

@interface UIImage (UIImageInternal)
+ (void)_flushCacheOnSuspend:(id)fp8;
- (void)_setCached:(BOOL)fp8;
- (BOOL)_isCached;
- (void)_setNamed:(BOOL)fp8;
- (BOOL)_isNamed;
- (id)_flatImageWithWhite:(float)fp8 alpha:(float)fp12;
- (id)_bezeledImageWithRed:(float)fp8 green:(float)fp12 blue:(float)fp16 alpha:(float)fp20;
- (id)_imageScaledToSize:(struct CGSize)fp8 interpolationQuality:(int)fp16;
- (id)_imageScaledToProportion:(float)fp8 interpolationQuality:(int)fp12;
@end

