/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

typedef enum {
    UIImageOrientationUp,            // default orientation
    UIImageOrientationDown,          // 180 deg rotation
    UIImageOrientationLeft,          // 90 deg CCW
    UIImageOrientationRight,         // 90 deg CW
    UIImageOrientationUpMirrored,    // as above but image mirrored along other axis. horizontal flip
    UIImageOrientationDownMirrored,  // horizontal flip
    UIImageOrientationLeftMirrored,  // vertical flip
    UIImageOrientationRightMirrored, // vertical flip
} UIImageOrientation;

@interface UIImage : NSObject
{
    void *_imageRef;
    struct {
        unsigned int named:1;
        unsigned int imageOrientation:3;
        unsigned int cached:1;
        unsigned int stretchable:1;
    } _imageFlags;
}

+ (void)initialize;
+ (id)imageNamed:(id)fp8;
+ (id)imageWithContentsOfFile:(id)fp8;
+ (id)imageWithData:(id)fp8;
+ (id)imageWithCGImage:(struct CGImage *)fp8;
#if 1 // iOS 4.x
+ (id)imageWithCGImage:(struct CGImage *)fp8 scale:(CGFloat)scale orientation:(UIImageOrientation)orientation;
#endif
- (id)initWithContentsOfFile:(id)fp8;
- (id)initWithData:(id)fp8;
- (id)initWithCGImage:(struct CGImage *)fp8;
- (void)dealloc;
- (struct CGImage *)CGImage;
- (struct CGSize)size;
- (int)imageOrientation;
- (void)drawAtPoint:(struct CGPoint)fp8;
- (void)drawAtPoint:(struct CGPoint)fp8 blendMode:(int)fp16 alpha:(float)fp20;
- (void)drawInRect:(struct CGRect)fp8;
- (void)drawInRect:(struct CGRect)fp8 blendMode:(int)fp24 alpha:(float)fp28;
- (void)drawAsPatternInRect:(struct CGRect)fp8;
- (int)leftCapWidth;
- (int)topCapHeight;
- (id)stretchableImageWithLeftCapWidth:(int)fp8 topCapHeight:(int)fp12;
- (id)_automationID;

#if 1 // iOS 4.x?
- (void) setScale:(CGFloat)scale;
#endif

@end

