/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIImage.h>

@interface UIImage (UIImagePrivate)
+ (id)applicationImageNamed:(id)fp8;
+ (id)kitImageNamed:(id)fp8;
+ (id)defaultDesktopImage;
+ (void)setDesktopImageData:(id)fp8;
+ (id)imageFromAlbumArtData:(id)fp8 height:(int)fp12 width:(int)fp16 cache:(BOOL)fp20;
- (id)initWithCGImage:(struct CGImage *)fp8 imageOrientation:(int)fp12;
- (id)initWithCoreSurfaceBuffer:(struct __CoreSurfaceBuffer *)fp8;
- (struct __CoreSurfaceBuffer *)coreSurfaceBuffer;
@end

