/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIKeyboardLayoutQWERTYLandscape.h>

@interface UIKeyboardLayoutQWERTYLandscape (UI_QWERTYLandscape_NumbersAndPunctuation)
- (void)addLocalizedCurrencyKeysToSublayout:(id)fp8 keyboardType:(id)fp12;
- (id)buildUIKeyboardLayoutNumbers;
- (id)buildUIKeyboardLayoutNumbersTransparent;
@end

