/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@class NSMutableArray, NSMutableDictionary, NSString, UIClippedImageView, UIImageView, UIKeyboardReturnKeyView, UIKeyboardSpaceKeyView;

@interface UIKeyboardSublayout : UIView
{
    UIImageView *m_imageView;
    UIClippedImageView *m_activeImageView;
    UIImageView *m_shiftImageView;
    UIClippedImageView *m_shiftActiveImageView;
    UIImageView *m_shiftButtonImageView;
    UIImageView *m_shiftButtonInactiveImageView;
    UIImageView *m_autoShiftButtonImageView;
    UIImageView *m_shiftLockedButtonImageView;
    NSMutableDictionary *m_compositeImages;
    NSMutableDictionary *m_activeKeyViews;
    UIImageView *m_intlMoreImageView;
    UIImageView *m_intlSwitchImageView;
    UIImageView *m_intlSwitchActiveImageView;
    UIImageView *m_nonIntlMoreImageView;
    UIImageView *m_deleteImageView;
    UIImageView *m_deleteActiveImageView;
    UIKeyboardSpaceKeyView *m_spaceKeyView;
    UIKeyboardReturnKeyView *m_returnKeyView;
    NSMutableArray *m_extraImageViews;
    struct {
        struct CGRect _field1;
        struct CGRect _field2;
        struct CGRect _field3;
        struct CGRect _field4;
        struct CGRect _field5;
        NSString * _field6;
        NSString * _field7;
        unsigned int _field8;
        unsigned int _field9;
        unsigned int _field10;
        id _field11;
    } *m_keys;
    unsigned int m_keysCount;
    struct __CFDictionary *m_replacementKeys;
    NSMutableDictionary *m_replacementImageViews;
    BOOL m_usesAutoShift;
    BOOL m_registersKeyCentroids;
    BOOL m_usesKeyCharges;
    BOOL m_internationalKeyIsActivated;
}

+ (id)sublayoutWithFrame:(struct CGRect)fp8 imagePaths:(id)fp24 keys:(const CDAnonymousStruct9 *)fp28 keysCount:(unsigned int)fp32;
+ (id)compositedSublayoutWithFrame:(struct CGRect)fp8 compositeImagePaths:(id)fp24 keys:(const CDAnonymousStruct9 *)fp28 keysCount:(unsigned int)fp32;
- (id)initWithFrame:(struct CGRect)fp8 imagePaths:(id)fp24 keys:(const CDAnonymousStruct9 *)fp28 keysCount:(unsigned int)fp32;
- (id)initWithFrame:(struct CGRect)fp8 compositeImagePaths:(id)fp24 keys:(const CDAnonymousStruct9 *)fp28 keysCount:(unsigned int)fp32;
- (void)dealloc;
- (void)setUsesAutoShift:(BOOL)fp8;
- (BOOL)usesAutoShift;
- (void)registerKeyAreaZephyr:(struct CGPoint)fp8 keyRect:(struct CGRect)fp16 keyCode:(int)fp32 keyString:(id)fp36 keyShiftString:(id)fp40;
- (void)registerKeyCentroids;
- (void)setRegistersKeyCentroids:(BOOL)fp8;
- (BOOL)usesKeyCharges;
- (void)setUsesKeyCharges:(BOOL)fp8;
- (void)setShiftButtonImage:(id)fp8 frame:(struct CGRect)fp12;
- (void)setShiftInactiveButtonImage:(id)fp8 frame:(struct CGRect)fp12;
- (void)setAutoShiftButtonImage:(id)fp8 frame:(struct CGRect)fp12;
- (void)setShiftLockedButtonImage:(id)fp8 frame:(struct CGRect)fp12;
- (void)setDeleteButtonImage:(id)fp8 frame:(struct CGRect)fp12;
- (void)setDeleteActiveButtonImage:(id)fp8 frame:(struct CGRect)fp12;
- (void)setCompositeImage:(id)fp8 forKey:(id)fp12;
- (id)compositeImageForKey:(id)fp8;
- (void)addReplacementKeyboardKey:(CDAnonymousStruct9 *)fp8 forKey:(id)fp12;
- (void)addReplacementImageView:(id)fp8 inputMode:(id)fp12 shift:(BOOL)fp16;
- (void)addExtraImageView:(id)fp8;
- (void)addPartialLayoutViewWithFrame:(struct CGRect)fp8 imageName:(id)fp24 visibleOrigin:(struct CGPoint)fp28;
- (void)addSpaceKeyViewIfNeeded;
- (void)addSpaceKeyViewIfNeeded:(id)fp8;
- (id)createSpaceKeyViewWithFrame:(struct CGRect)fp8 orientation:(int)fp24 style:(int)fp28;
- (void)setSpaceKeyView:(id)fp8;
- (void)addReturnKeyViewIfNeeded;
- (void)addReturnKeyViewIfNeeded:(id)fp8;
- (id)createReturnKeyViewWithFrame:(struct CGRect)fp8 orientation:(int)fp24 style:(int)fp28;
- (void)setReturnKeyView:(id)fp8;
- (id)internationalImageName:(int)fp8 forKeyboard:(id)fp12 orientation:(int)fp16;
- (void)addInternationalKeyIfNeeded:(id)fp8;
- (BOOL)hitInternationalKey:(struct CGPoint)fp8;
- (void)activateInternationalKey;
- (BOOL)internationalKeyIsActivated;
- (void)deactivateInternationalKey;
- (void)bringKeySubviewsToFront;
- (id)scriptingInfoWithChildren;

@end

