/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIKeyboardLayoutQWERTZLandscape.h>

@interface UIKeyboardLayoutQWERTZLandscape (UI_QWERTZLandscape_EmailAddress)
- (id)buildUIKeyboardLayoutEmailAddress;
@end

