/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIView.h>

#import "UIKeyboardLayoutProtocol-Protocol.h"

@interface UIKeyboardLayout : UIView <UIKeyboardLayoutProtocol>
{
}

- (id)initWithFrame:(struct CGRect)fp8;
- (void)showKeyboardType:(int)fp8 withAppearance:(int)fp12;
- (void)deactivateActiveKeys;
- (void)updateReturnKey;
- (void)updateLocalizedKeys;
- (BOOL)usesAutoShift;
- (void)setShift:(BOOL)fp8;
- (BOOL)isShiftKeyBeingHeld;
- (void)longPressAction;
- (BOOL)canHandleHandEvent:(struct __GSEvent *)fp8;
- (BOOL)handleHandEvent:(struct __GSEvent *)fp8;
- (void)didClearInput;
- (id)candidateList;
- (void)setLabel:(id)fp8 forKey:(id)fp12;
- (void)setTarget:(id)fp8 forKey:(id)fp12;
- (void)setAction:(SEL)fp8 forKey:(id)fp12;
- (void)setLongPressAction:(SEL)fp8 forKey:(id)fp12;
- (void)restoreDefaultsForKey:(id)fp8;
- (void)restoreDefaultsForAllKeys;
- (id)activationIndicatorView;
- (void)handleHardwareKeyDownFromSimulator:(struct __GSEvent *)fp8;

@end

