/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIKeyboardInputManager.h>

@interface UIKeyboardInputManagerAlphabet : UIKeyboardInputManager
{
    struct KBInputManagerAlphabet *m_impl;
}

- (id)init;
- (void)dealloc;
- (struct KBInputManagerAlphabet *)initImplementation;
- (void)loadDictionaries;
- (void)setAutoCorrects:(BOOL)fp8;
- (void)setShallowPrediction:(BOOL)fp8;
- (void)setCalculatesChargedKeyProbabilities:(BOOL)fp8;
- (void)clearDynamicDictionary;
- (void)addInput:(id)fp8 flags:(unsigned int)fp12 point:(struct CGPoint)fp16;
- (void)setInput:(id)fp8;
- (void)deleteFromInput;
- (void)clearInput;
- (void)acceptInput;
- (void)setInputIndex:(unsigned int)fp8;
- (unsigned int)inputIndex;
- (unsigned int)inputCount;
- (id)inputString;
- (id)defaultCandidate;
- (void)addToTypingHistory:(id)fp8;
- (void)textAccepted:(id)fp8;
- (void)increaseUserFrequency:(id)fp8;
- (void)decreaseUserFrequency:(id)fp8;
- (void)inputLocationChanged;
- (id)shadowTyping;
- (void)setShift:(BOOL)fp8;
- (void)setAutoShift:(BOOL)fp8;
- (struct __CFArray *)chargeableKeys;
- (struct __CFDictionary *)chargedKeyProbabilities;
- (id)composedTyping;
- (id)autocorrection;

@end

