/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIView.h>

#import "UIKeyboardCandidateList-Protocol.h"

@class NSArray, NSMutableArray, NSString, NSTimer, UIAutocorrectInlinePrompt, UIImage, UIImageView, UIKeyboardGenericKeyView, UILabel, UIScroller;

@interface UIKeyboardCandidateInline : UIView <UIKeyboardCandidateList>
{
    id _delegate;
    NSArray *_candidates;
    unsigned int _currentCandidateIndex;
    unsigned int _numCandidates;
    unsigned int _currentPageIndex;
    UILabel *_inlineTextLabel;
    NSString *_inlineText;
    struct CGRect _inlineRect;
    struct CGRect _frame;
    unsigned int _lineHeight;
    unsigned int _numColumns;
    BOOL _alwaysShowBackground;
    BOOL _showControls;
    BOOL _showingAll;
    BOOL _selectedInAll;
    NSMutableArray *_candidateLines;
    UIAutocorrectInlinePrompt *_inlineView;
    UIScroller *_scrollView;
    UIImageView *_controlsView;
    UIKeyboardGenericKeyView *_subviewButton;
    UIKeyboardGenericKeyView *_nextPageButton;
    UIKeyboardGenericKeyView *_prevPageButton;
    struct CGRect _inlineCandidateFrame;
    float _lazyLayoutNextOriginY;
    unsigned int _lazyLayoutNextCandidateIndex;
    int _orientation;
    BOOL _forMobileNotes;
    BOOL _landscape;
    BOOL _animating;
    struct CGRect _windowFrame;
    struct CGPoint _draggingStartOffset;
    UIImageView *_closeButton;
    UIImage *_backgroundImage;
    struct CGRect _closeButtonFrame;
    BOOL _showScroller;
    NSTimer *_deferredLayoutTimer;
    UIView *_shadowView;
    BOOL _caretVisible;
    BOOL _caretblinking;
    struct CGRect m_caretRect;
    UIView *m_caretView;
    NSTimer *m_caretTimer;
    BOOL m_caretShowingNow;
    BOOL m_showingCompletions;
}

+ (id)sharedInstance;
+ (void)releaseSharedInstance;
- (id)initWithFrame:(struct CGRect)fp8;
- (id)rotatingContentViewForWindow:(id)fp8;
- (void)adjustForFrame:(struct CGRect)fp8 orientation:(int)fp24;
- (int)orientation;
- (void)mouseDown:(struct __GSEvent *)fp8;
- (void)mouseUp:(struct __GSEvent *)fp8;
- (void)touchesEnded:(id)fp8 withEvent:(id)fp12;
- (BOOL)ignoresMouseEvents;
- (void)dealloc;
- (void)candidateAcceptedAtIndex:(unsigned int)fp8;
- (void)drawRect:(struct CGRect)fp8;
- (void)_setInlineText:(id)fp8;
- (void)setCandidates:(id)fp8 inlineText:(id)fp12 inlineRect:(struct CGRect)fp16 maxX:(float)fp32 layout:(BOOL)fp36;
- (void)setCompletionContext:(id)fp8;
- (void)showCandidateAtIndex:(unsigned int)fp8;
- (void)showPageAtIndex:(unsigned int)fp8;
- (void)showNextPage;
- (void)showPreviousPage;
- (void)setUIKeyboardCandidateListDelegate:(id)fp8;
- (void)showNextCandidate;
- (id)currentCandidate;
- (unsigned int)currentIndex;
- (id)candidateAtIndex:(unsigned int)fp8;
- (void)setCurrentIndex:(unsigned int)fp8;
- (unsigned int)count;
- (void)configureKeyboard:(id)fp8;
- (void)setAlwaysShowBackground:(BOOL)fp8;
- (void)setShowControls:(BOOL)fp8;
- (void)inlineCandidateClicked:(id)fp8;
- (void)candidateListAcceptCandidate:(id)fp8;
- (void)cellSelected:(id)fp8;
- (void)cancelButtonSelected:(id)fp8;
- (void)prevPageButtonSelected:(id)fp8;
- (void)nextPageButtonSelected:(id)fp8;
- (void)layout;
- (void)layoutOneCandidateAtIndex:(unsigned int)fp8;
- (void)clearLayout;
- (void)_clearInlineCandidate;
- (void)_fadeInlineCandidate;
- (void)_animateInlineCandidate;
- (void)_adjustFrameSizeForCandidateLines:(int)fp8;
- (void)inlineCandidateAnimationDidStop:(id)fp8 finished:(id)fp12 context:(void *)fp16;
- (void)_showBackground;
- (void)autocorrectionAnimationDidStop:(id)fp8 finished:(id)fp12 context:(void *)fp16;
- (BOOL)scroller:(id)fp8 shouldAdjustSmoothScrollEndForVelocity:(struct CGSize)fp12;
- (struct CGPoint)scroller:(id)fp8 adjustSmoothScrollEnd:(struct CGPoint)fp12 velocity:(struct CGSize)fp20;
- (void)scrollerWillStartDragging:(id)fp8;
- (void)scrollerDidEndDragging:(id)fp8 willSmoothScroll:(BOOL)fp12;
- (void)scrollerDidEndAnimatedScrolling:(id)fp8;
- (void)_hideBackground;
- (void)_periodicLayoutNextPage:(id)fp8;
- (BOOL)_layoutNextLine;
- (BOOL)needsWebDocumentViewEventsDirectly;
- (void)setCaretPosition:(struct CGRect)fp8;
- (void)showCaret:(BOOL)fp8 gradually:(BOOL)fp12;
- (int)textEffectsVisibilityLevel;

@end

