/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UINavigationController.h>

@class UIMoreListController, UIViewController;

@interface UIMoreNavigationController : UINavigationController
{
    UIMoreListController *_moreListController;
    UINavigationController *_originalNavigationController;
    UIViewController *_originalRootViewController;
}

- (id)init;
- (void)dealloc;
- (void)pushViewController:(id)fp8 animated:(BOOL)fp12;
- (void)willShowViewController:(id)fp8 animated:(BOOL)fp12;
- (id)moreViewControllers;
- (void)setMoreViewControllers:(id)fp8;
- (BOOL)allowsCustomizing;
- (void)setAllowsCustomizing:(BOOL)fp8;

@end

