/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIMoreListController.h>

@class UITable;

@interface UIMoreListControllerLegacy : UIMoreListController
{
    UITable *_table;
}

- (void)dealloc;
- (id)table;
- (void)loadView;
- (void)viewDidDisappear:(BOOL)fp8;
- (int)numberOfRowsInTable:(id)fp8;
- (id)table:(id)fp8 cellForRow:(int)fp12 column:(id)fp16 reusing:(id)fp20;
- (void)tableSelectionDidChange:(id)fp8;
- (BOOL)table:(id)fp8 showDisclosureForRow:(int)fp12;

@end

