/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIView.h>

#import "UIModalViewDelegate-Protocol.h"
#import "UITextFieldDelegate-Protocol.h"

@class NSMutableArray, UILabel, UIToolbar, UIWindow;

@interface UIModalView : UIView <UITextFieldDelegate>
{
    id <UIModalViewDelegate> _delegate;
    UILabel *_titleLabel;
    UILabel *_subtitleLabel;
    UILabel *_bodyTextLabel;
    UILabel *_taglineTextLabel;
    float _startY;
    id _context;
    int _cancelButton;
    int _defaultButton;
    int _firstOtherButton;
    UIToolbar *_toolbar;
    UIWindow *_dimWindow;
    int _suspendTag;
    int _dismissButtonIndex;
    float _bodyTextHeight;
    NSMutableArray *_buttons;
    NSMutableArray *_textFields;
    UIView *_keyboard;
    UIView *_table;
    UIView *_dimView;
    struct {
        unsigned int numberOfRows:7;
        unsigned int delegateAlertSheetButtonClicked:1;
        unsigned int delegateDidPresentAlertSheet:1;
        unsigned int delegateDidDismissAlertSheet:1;
        unsigned int hideButtonBar:1;
        unsigned int alertStyle:3;
        unsigned int dontDimBackground:1;
        unsigned int dismissSuspended:1;
        unsigned int dontBlockInteraction:1;
        unsigned int sheetWasPoppedUp:1;
        unsigned int animating:1;
        unsigned int hideWhenDoneAnimating:1;
        unsigned int layoutWhenDoneAnimating:1;
        unsigned int titleMaxLineCount:2;
        unsigned int bodyTextMaxLineCount:3;
        unsigned int runsModal:1;
        unsigned int runningModal:1;
        unsigned int addedTextView:1;
        unsigned int addedTableShadows:1;
        unsigned int showOverSBAlerts:1;
        unsigned int showMinTableContent:1;
        unsigned int bodyTextTruncated:1;
        unsigned int orientation:3;
        unsigned int delegateBodyTextAlignment:1;
        unsigned int delegateClickedButtonAtIndex:1;
        unsigned int delegateCancel:1;
        unsigned int delegateWillPresent:1;
        unsigned int delegateDidPresent:1;
        unsigned int delegateWillDismiss:1;
        unsigned int delegateDidDismiss:1;
        unsigned int extra:21;
    } _modalViewFlags;
}

- (id)initWithFrame:(struct CGRect)fp8;
- (id)initWithTitle:(id)fp8 message:(id)fp12 delegate:(id)fp16 defaultButton:(id)fp20 cancelButton:(id)fp24 otherButtons:(id)fp28;
- (void)dealloc;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)setTitle:(id)fp8;
- (id)title;
- (void)setMessage:(id)fp8;
- (id)message;
- (int)addButtonWithTitle:(id)fp8;
- (id)buttonTitleAtIndex:(int)fp8;
- (int)numberOfButtons;
- (BOOL)isVisible;
- (void)setDefaultButtonIndex:(int)fp8;
- (int)defaultButtonIndex;
- (void)setCancelButtonIndex:(int)fp8;
- (int)cancelButtonIndex;
- (void)_setFirstOtherButtonIndex:(int)fp8;
- (int)firstOtherButtonIndex;
- (void)dismissWithClickedButtonIndex:(int)fp8 animated:(BOOL)fp12;

@end

