/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@class UIFont, UINavigationItem;

@interface UINavigationItemView : UIView
{
    UIFont *_font;
    UINavigationItem *_item;
    float _titleWidth;
    BOOL _titleAutosizesToFit;
}

- (id)initWithNavigationItem:(id)fp8;
- (id)navigationItem;
- (id)_defaultFont;
- (void)drawText:(id)fp8 inRect:(struct CGRect)fp12;
- (void)setFrame:(struct CGRect)fp8;
- (void)drawRect:(struct CGRect)fp8;
- (void)_resetTitleWidth;
- (float)_titleWidth;
- (id)title;
- (void)setTitleAutoresizesToFit:(BOOL)fp8;
- (BOOL)titleAutoresizesToFit;
- (void)setFont:(id)fp8;
- (id)font;

@end

