/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@class NSString, UINavigationBar;

@interface UINavBarPrompt : UIView
{
    NSString *_prompt;
    UINavigationBar *_navBar;
}

- (id)initWithPrompt:(id)fp8 navBar:(id)fp12;
- (void)clearWeakReference:(id)fp8;
- (void)dealloc;
- (void)setPrompt:(id)fp8;
- (id)prompt;
- (struct CGRect)promptBounds;
- (void)drawRect:(struct CGRect)fp8;

@end

