/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UINavigationItemView.h>

@interface UINavigationItemButtonView : UINavigationItemView
{
    int _style;
    BOOL _pressed;
}

- (void)drawRect:(struct CGRect)fp8;
- (id)title;
- (id)image;
- (struct CGSize)imageSize;
- (void)setStyle:(int)fp8;
- (void)setPressed:(BOOL)fp8;
- (BOOL)pressed;
- (id)_scriptingInfo;
- (id)_defaultFont;

@end

