/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIControl.h>

@class UIImage, UIView;

/*XXX*/typedef union {
    UIImage *image;
    UIView *view;
} CDAnonymousUnion1;

@interface UIOldSliderControl : UIControl
{
    UIImage *_sliderLeftFillCap;
    CDAnonymousUnion1 _sliderLeftFill;
    CDAnonymousUnion1 _sliderRightFill;
    UIImage *_minValueImage;
    UIImage *_maxValueImage;
    int _numberOfTickMarks;
    float _hitOffset;
    UIImage *_sliderRightCap;
    UIImage *_sliderRightFullCap;
    UIImage *_sliderLeftCap;
    struct {
        unsigned int allowsOnlyTickMarks:1;
        unsigned int animating:1;
        unsigned int showValue:1;
        unsigned int layeredFill:1;
        unsigned int continuous:1;
        unsigned int sendActionDuringAnimation:1;
        unsigned int alternateColors:1;
        unsigned int shouldFlipValue:1;
        unsigned int needsNonOpaqueFills:1;
        unsigned int reserved:24;
    } _sliderFlags;
    float _value;
    float _animationEndValue;
    float _minValue;
    float _maxValue;
    UIView *_knob;
}

- (id)init;
- (id)initWithFrame:(struct CGRect)fp8;
- (id)initWithFrame:(struct CGRect)fp8 layeredFill:(BOOL)fp24;
- (id)createSliderKnobView;
- (void)_resetFillFrames;
- (struct CGRect)fillBounds;
- (void)sliderBoundsChanged;
- (void)refreshImages;
- (void)dealloc;
- (id)imageForSliderPiece:(int)fp8;
- (void)drawSliderPiece:(int)fp8 inRect:(struct CGRect)fp12;
- (void)_sliderBounds:(struct CGRect)fp8 getLeftCapRect:(struct CGRect *)fp24 rightCapRect:(struct CGRect *)fp28 left:(struct CGRect *)fp32 right:(struct CGRect *)fp36;
- (void)drawSliderInRect:(struct CGRect)fp8 dirtyRect:(struct CGRect)fp24;
- (void)drawSliderInRect:(struct CGRect)fp8;
- (void)animator:(id)fp8 stopAnimation:(id)fp12;
- (void)_sendDelayedActions;
- (void)setValue:(float)fp8;
- (void)_setValue:(float)fp8 andSendAction:(BOOL)fp12;
- (BOOL)isAnimatingValueChange;
- (void)setValue:(float)fp8 animated:(BOOL)fp12 animationCurve:(int)fp16;
- (void)setValue:(float)fp8 animated:(BOOL)fp12;
- (float)value;
- (struct CGRect)sliderBounds;
- (struct CGRect)minValueImageBounds;
- (struct CGRect)maxValueImageBounds;
- (struct CGRect)valueTextBounds;
- (void)setMinValue:(float)fp8;
- (void)setMaxValue:(float)fp8;
- (void)drawRect:(struct CGRect)fp8;
- (void)setNumberOfTickMarks:(int)fp8;
- (void)setAllowsTickMarkValuesOnly:(BOOL)fp8;
- (void)setShowValue:(BOOL)fp8;
- (void)setMinValueImage:(id)fp8;
- (void)setMaxValueImage:(id)fp8;
- (void)setEnabled:(BOOL)fp8;
- (float)_validatedValue:(float)fp8;
- (float)_validatedValueForPoint:(struct CGPoint)fp8 includeTickMarks:(BOOL)fp16;
- (void)setHighlighted:(BOOL)fp8;
- (BOOL)beginTrackingAt:(struct CGPoint)fp8 withEvent:(struct __GSEvent *)fp16;
- (BOOL)continueTrackingAt:(struct CGPoint)fp8 previous:(struct CGPoint)fp16 withEvent:(struct __GSEvent *)fp24;
- (void)endTrackingAt:(struct CGPoint)fp8 previous:(struct CGPoint)fp16 withEvent:(struct __GSEvent *)fp24;
- (BOOL)cancelMouseTracking;
- (void)_controlMouseDown:(struct __GSEvent *)fp8;
- (void)_controlMouseUp:(struct __GSEvent *)fp8;
- (void)_controlMouseDragged:(struct __GSEvent *)fp8;
- (BOOL)beginTrackingWithTouch:(id)fp8 withEvent:(id)fp12;
- (BOOL)continueTrackingWithTouch:(id)fp8 withEvent:(id)fp12;
- (void)endTrackingWithTouch:(id)fp8 withEvent:(id)fp12;
- (void)_controlTouchBegan:(id)fp8 withEvent:(id)fp12;
- (void)_controlTouchMoved:(id)fp8 withEvent:(id)fp12;
- (void)_controlTouchEnded:(id)fp8 withEvent:(id)fp12;
- (BOOL)cancelTouchTracking;
- (void)setContinuous:(BOOL)fp8;
- (void)setSendActionDuringAnimation:(BOOL)fp8;

@end

