/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIAnimation.h>

@interface UIPickerScrollAnimation : UIAnimation
{
    float _initialDuration;
    struct CGPoint _originalOffset;
    struct CGPoint _targetOffset;
}

- (struct CGPoint)targetOffset;
- (void)setTargetOffset:(struct CGPoint)fp8;
- (void)setOriginalOffset:(struct CGPoint)fp8;
- (void)setProgress:(float)fp8;
- (float)initialDuration;
- (void)setInitialDuration:(float)fp8;

@end

