/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UITable.h>

@class UIPickerScrollAnimation;

@interface UIPickerTable : UITable
{
    struct CGRect _selectionBarRect;
    UIPickerScrollAnimation *_scrollAnimation;
    int _selectionBarRow;
    struct CGPoint _lastOffset;
    int _lastClickRow;
    unsigned int _allowSelectingCells:1;
    unsigned int _allowsMultipleSelection:1;
    unsigned int _lastShouldStick:1;
    unsigned int _disableDidSelect:1;
}

- (id)initWithFrame:(struct CGRect)fp8;
- (BOOL)canHandleSwipes;
- (BOOL)didSelectDisabled;
- (int)lastClickRow;
- (void)setLastClickRow:(int)fp8;
- (void)setAllowsMultipleSelection:(BOOL)fp8;
- (BOOL)allowsMultipleSelection;
- (void)setAllowsSelectingRows:(BOOL)fp8;
- (void)_scrollSelectionBarRect:(struct CGRect)fp8 animated:(BOOL)fp24 notify:(BOOL)fp28;
- (void)selectCell:(id)fp8 inRow:(int)fp12 column:(int)fp16 withFade:(BOOL)fp20;
- (void)contentMouseUpInView:(id)fp8 withEvent:(struct __GSEvent *)fp12;
- (int)selectionBarRow;
- (id)selectedTableCell;
- (void)selectRow:(int)fp8 animated:(BOOL)fp12 notify:(BOOL)fp16;
- (void)setSelectionBarRect:(struct CGRect)fp8;
- (struct CGRect)selectionBarRect;
- (void)animationSetOffset:(struct CGPoint)fp8;
- (void)mouseDown:(struct __GSEvent *)fp8;
- (void)mouseUp:(struct __GSEvent *)fp8;
- (void)_pickerScrollAnimationEnded;
- (void)_didMoveFromWindow:(id)fp8 toWindow:(id)fp12;
- (struct CGPoint)newOffsetWithCenteredRectFromOffset:(struct CGPoint)fp8;
- (BOOL)scrollCenterCellToSelectionBar;
- (BOOL)fixupCenterCellToSelectionBar:(BOOL)fp8;
- (void)setRowHeight:(CGFloat)fp8;
- (void)removeFromSuperview;
- (void)updateSelectionBarRow;

@end

