/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

#import "NSCoding-Protocol.h"

@class NSString;

@interface UIProxyObject : NSObject <NSCoding>
{
    NSString *proxiedObjectIdentifier;
}

+ (struct __CFDictionary *)proxyDecodingMap;
+ (void)addMappingFromIdentifier:(id)fp8 toObject:(id)fp12 forCoder:(id)fp16;
+ (void)addMappings:(id)fp8 forCoder:(id)fp12;
+ (id)mappedObjectForCoder:(id)fp8 withIdentifier:(id)fp12;
+ (void)removeMappingsForCoder:(id)fp8;
- (id)initWithCoder:(id)fp8;
- (void)encodeWithCoder:(id)fp8;
- (void)dealloc;
- (void)setProxiedObjectIdentifier:(id)fp8;
- (id)proxiedObjectIdentifier;

@end

