/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UITable.h>

@class NSMutableArray, UIKeyboard, UIPreferencesTableCell;

@interface UIPreferencesTable : UITable
{
    UIPreferencesTableCell *_editingCell;
    int _editingCellRow;
    NSMutableArray *_groupItems;
    UIKeyboard *_keyboard;
    float _textOffset;
    struct __CFDictionary *_piecesForCell;
    unsigned int _datasourceCellForGroup:1;
    unsigned int _datasourceIsRadioGroup:1;
    unsigned int _datasourceIsLabelGroup:1;
    unsigned int _datasourceIsRowCheckedInRadioGroup:1;
    unsigned int _centersContent:1;
    unsigned int _reserved:27;
}

- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;
- (void)setFrame:(struct CGRect)fp8;
- (BOOL)canHandleSwipes;
- (BOOL)canDeleteRow:(int)fp8;
- (BOOL)canInsertAtRow:(int)fp8;
- (void)addTableColumn:(id)fp8;
- (BOOL)canSelectRow:(int)fp8;
- (id)_visibleCheckedCellInTableRowRange:(struct _NSRange)fp8;
- (void)_fadeCellSelection;
- (void)selectRow:(int)fp8 byExtendingSelection:(BOOL)fp12 withFade:(BOOL)fp16;
- (int)tableRowForRow:(int)fp8 inGroup:(int)fp12;
- (id)_groupItemForTableRow:(int)fp8 andGroupIndex:(int *)fp12 andRow:(int *)fp16 inGroups:(id)fp20;
- (id)_groupItemForTableRow:(int)fp8 andGroupIndex:(int *)fp12 andRow:(int *)fp16;
- (BOOL)getGroup:(int *)fp8 row:(int *)fp12 ofPreferencesTableCell:(id)fp16;
- (int)groupForTableRow:(int)fp8;
- (BOOL)getGroup:(int *)fp8 row:(int *)fp12 forTableRow:(int)fp16;
- (void)setDataSource:(id)fp8;
- (BOOL)validateDataSource;
- (int)dataSourceGetRowCount;
- (int)_cellOutlineForRow:(int)fp8 withChildCount:(int)fp12 isLabelGroup:(BOOL)fp16;
- (id)dataSourceCreateCellForRow:(int)fp8 column:(int)fp12 reusing:(id)fp16;
- (struct CGRect)frameOfPreferencesCellAtRow:(int)fp8 inGroup:(int)fp12;
- (BOOL)floatArray:(id)fp8 loadValues:(float *)fp12 count:(int)fp16;
- (int)_paddingForCenteringContent;
- (void)_updatePaddingForCenteringContent;
- (void)setCentersContent:(BOOL)fp8;
- (void)_updateContentSize;
- (BOOL)dataSourceSupportsVariableRowHeights;
- (id)visiblePreferencesCellForRow:(int)fp8 inGroup:(int)fp12;
- (void)animateDeletionOfRowWithCell:(id)fp8 viaEdge:(int)fp12;
- (BOOL)shouldIndentRow:(int)fp8;
- (void)deleteRows:(id)fp8 viaEdge:(int)fp12;
- (void)_setAlpha:(float)fp8 forSubviewsOf:(id)fp12;
- (id)_existingPieceForCell:(id)fp8;
- (id)_copyPieceOfCell:(id)fp8 withContentsPosition:(int)fp12;
- (float)animationDuration;
- (void)reloadData;
- (void)insertItems:(id)fp8;
- (void)deleteItems:(id)fp8;
- (void)_fadeCellOutAnimationDidStop:(id)fp8 finished:(id)fp12 context:(id)fp16;
- (void)_removeContextFromSuperview:(id)fp8 finished:(id)fp12 context:(id)fp16;
- (void)_removePiecesFromSuperview:(id)fp8;
- (void)_removePiecesFromSuperview:(id)fp8 finished:(id)fp12 context:(id)fp16;
- (void)_fadeCellOutAnimationDidStopAndFixOutlines:(id)fp8 finished:(id)fp12 context:(id)fp16;
- (void)enableRowDeletion:(BOOL)fp8 animated:(BOOL)fp12;
- (void)_animatePiecesOfCell:(id)fp8 isFirstItemInGroup:(BOOL)fp12 isDeletion:(BOOL)fp16 isDestinationRowFrame:(struct CGRect)fp20;
- (BOOL)_userCanDeleteRows;
- (void)insertItems:(id)fp8 deleteItems:(id)fp12 andReloadIndexes:(id)fp16;
- (BOOL)keyboardVisible;
- (id)keyboard;
- (void)_keyboardRemoveAnimationCompleted:(id)fp8;
- (void)setKeyboardVisible:(BOOL)fp8;
- (void)resumeWithNotification:(id)fp8;
- (void)setBottomBufferHeight:(float)fp8;
- (void)scrollAndCenterTableCell:(id)fp8 animated:(BOOL)fp12;
- (void)setKeyboardVisible:(BOOL)fp8 animated:(BOOL)fp12;
- (id)_editingCell;
- (void)_setEditingCell:(id)fp8;
- (int)editingRow;
- (BOOL)_beginEditingNextCell;

@end

