/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIControl.h>

@interface UIRemoveControlMinusButton : UIControl
{
    unsigned int _rotated:1;
    unsigned int _rotating:1;
    unsigned int _hiding:1;
    unsigned int _showAsPlus:1;
    unsigned int _reserved:28;
    float _verticalOffset;
}

+ (float)defaultWidth;
+ (id)minusImage;
+ (id)plusImage;
+ (id)minusCenterImage;
- (id)initWithRemoveControl:(id)fp8;
- (void)dealloc;
- (void)setHiding:(BOOL)fp8;
- (BOOL)isHiding;
- (void)drawRect:(struct CGRect)fp8;
- (void)animator:(id)fp8 stopAnimation:(id)fp12;
- (void)toggleRotate:(BOOL)fp8;
- (BOOL)isRotated;
- (BOOL)isRotating;
- (void)_toggleRotateAnimationDidStop:(id)fp8 finished:(BOOL)fp12;

@end

