/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@class NSMutableDictionary;

@interface UIReachabilityManager : NSObject
{
    NSMutableDictionary *_requests;
}

+ (id)sharedReachabilityManager;
- (id)init;
- (void)dealloc;
- (void)addObserver:(id)fp8 forHostname:(id)fp12;
- (void)removeObserver:(id)fp8 forHostname:(id)fp12;

@end

