/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

#import "NSCoding-Protocol.h"

@class NSString;

@interface UIRuntimeConnection : NSObject <NSCoding>
{
    id source;
    id destination;
    NSString *label;
}

- (id)initWithCoder:(id)fp8;
- (void)encodeWithCoder:(id)fp8;
- (void)dealloc;
- (id)source;
- (void)setSource:(id)fp8;
- (id)destination;
- (void)setDestination:(id)fp8;
- (id)label;
- (void)setLabel:(id)fp8;
- (void)connect;
- (void)connectForSimulator;

@end

