/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIRuntimeConnection.h>

@interface UIRuntimeOutletConnection : UIRuntimeConnection
{
}

- (void)connect;
- (void)connectForSimulator;
- (id)description;

@end

