/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UITable.h>

@class NSMutableArray, UISectionList;

@interface UISectionTable : UITable
{
    UISectionList *_sectionList;
    struct _NSRange _visibleHeaders;
    NSMutableArray *_visibleHeaderViews;
    float _rightMargin;
    NSMutableArray *_reusableHeaderCells;
    NSMutableArray *_reusableTransparentHeaderCells;
    int _reusableHeaderCapacity;
    struct {
        unsigned int style:1;
        unsigned int delegateHeaderForSection:1;
        unsigned int disableHideHeadersInShortLists:1;
        unsigned int disallowsScrollIndicators:1;
        unsigned int reserved:28;
    } _sectionTableFlags;
}

- (id)initWithFrame:(struct CGRect)fp8 sectionList:(id)fp24;
- (id)initWithSize:(struct CGSize)fp8 sectionList:(id)fp16;
- (void)dealloc;
- (void)setFrame:(struct CGRect)fp8;
- (void)setDelegate:(id)fp8;
- (void)reloadData;
- (BOOL)floatArray:(id)fp8 loadGapIndexes:(int *)fp12 gapHeight:(float *)fp16 count:(int)fp20;
- (void)floatArray:(id)fp8 getValueCount:(int *)fp12 gapIndexCount:(int *)fp16;
- (id)createPreparedCellForRow:(int)fp8 column:(int)fp12;
- (id)_createHeaderCellForHeaderAtIndex:(int)fp8 width:(float)fp12 opaque:(BOOL)fp16 adjustOrigin:(BOOL)fp20;
- (void)_removeHeaderCellsForRange:(struct _NSRange)fp8;
- (void)_replaceCellWithTransparentOneGapIndex:(int)fp8 viewIndex:(int)fp12 width:(float)fp16;
- (void)_replaceCellWithOpaqueOneGapIndex:(int)fp8 viewIndex:(int)fp12 width:(float)fp16;
- (BOOL)_shouldHideHeaders;
- (void)_updateShowScrollIndicatorsFlag;
- (void)_updateVisibleCellsNow;
- (BOOL)showsSectionHeaders;
- (void)scrollToSection:(int)fp8;
- (void)scrollToSectionWithTitle:(id)fp8;
- (void)scrollRowToVisible:(int)fp8;
- (BOOL)sectionHeaderCellWasClicked:(id)fp8;
- (void)setRightMargin:(float)fp8;
- (void)setAllowsScrollIndicators:(BOOL)fp8;
- (void)setShouldHideHeaderInShortLists:(BOOL)fp8;
- (void)setSectionListStyle:(int)fp8;
- (id)indexTitles;
- (void)_reloadRowHeights;

@end

