/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UITextField.h>

@interface UISearchBarTextField : UITextField
{
}

- (BOOL)_hasActionForEventMask:(int)fp8;
- (struct CGRect)textRectForBounds:(struct CGRect)fp8;
- (struct CGRect)editingRectForBounds:(struct CGRect)fp8;
- (struct CGRect)leftViewRectForBounds:(struct CGRect)fp8;
- (struct CGRect)rightViewRectForBounds:(struct CGRect)fp8;

@end

