/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UILabel.h>

@interface UISegmentLabel : UILabel
{
    int _style;
}

- (id)initWithSegmentedControlStyle:(int)fp8;
- (id)_disabledFontColor;

@end

