/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UITextField.h>

@interface UISearchField : UITextField
{
}

+ (float)defaultHeight;
- (id)initWithFrame:(struct CGRect)fp8;
- (struct CGRect)iconRect;
- (struct CGRect)_textRectExcludingButtonsForBounds:(struct CGRect)fp8;
- (struct CGRect)rightViewRectForBounds:(struct CGRect)fp8;
- (Class)_systemBackgroundViewClass;
- (id)_scriptingInfo;

@end

