/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UISegmentedControl.h>

@interface UISegmentedControl (Static)
- (void)_createSegmentAtIndex:(int)fp8 position:(unsigned int)fp12 withInfo:(id)fp16;
- (void)_insertSegment:(int)fp8 withInfo:(id)fp12 animated:(BOOL)fp16;
- (void)_clearSelectedSegment;
- (void)_removeSegmentAnimationFinished:(id)fp8 finished:(id)fp12 context:(void *)fp16;
@end

