/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@class NSMutableArray, NSSet, UISectionIndex, UISectionTable;

@interface UISectionList : UIView
{
    UISectionTable *_table;
    UISectionIndex *_index;
    NSMutableArray *_titles;
    NSSet *_indexTitlesAsSet;
    int _sectionCount;
    float _listWidth;
    struct {
        unsigned int nonIndexedTitlesShownFirst:1;
    } _sectionListFlags;
}

+ (float)defaultIndexWidth;
- (id)initWithFrame:(struct CGRect)fp8 showSectionIndex:(BOOL)fp24;
- (id)initWithFrame:(struct CGRect)fp8;
- (void)dealloc;
- (void)setDataSource:(id)fp8;
- (float)marginForIndexControl:(BOOL)fp8;
- (id)allTitles;
- (void)_languageChanged;
- (id)indexTitles;
- (void)setAllowsScrollIndicators:(BOOL)fp8;
- (void)setShouldHideHeaderInShortLists:(BOOL)fp8;
- (BOOL)showsSectionHeaders;
- (BOOL)showsSectionIndex;
- (void)setNonIndexedTitlesShownLast:(BOOL)fp8;
- (void)setSectionListStyle:(int)fp8;
- (void)noteIndexTitlesDidChange;
- (void)reloadData;
- (int)numberOfSections;
- (id)titleForSection:(int)fp8;
- (int)closestSectionForTitle:(id)fp8;
- (id)_indexTitlesAsSet;
- (void)_setIndexVisible:(BOOL)fp8;
- (id)table;

@end

