/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UITableCell.h>

@class NSString, UIFont, UIImageView;

@interface UISimpleTableCell : UITableCell
{
    UIFont *_font;
    UIImageView *_iconImageView;
    unsigned int _indentationLevel;
    NSString *_title;
    int _titleColor;
}

+ (id)defaultFont;
- (id)initWithFrame:(struct CGRect)fp8;
- (void)setFont:(id)fp8;
- (id)font;
- (void)dealloc;
- (void)drawTitleInRect:(struct CGRect)fp8 selected:(BOOL)fp24;
- (void)drawContentInRect:(struct CGRect)fp8 selected:(BOOL)fp24;
- (void)setUserInteractionEnabled:(BOOL)fp8;
- (void)setTitle:(id)fp8;
- (id)title;
- (void)setTitleColor:(int)fp8;
- (id)iconImageView;
- (void)layoutSubviews;
- (void)setIcon:(id)fp8;
- (id)icon;
- (void)setIndentationLevel:(unsigned int)fp8;
- (unsigned int)indentationLevel;
- (int)lineBreakMode;
- (id)_scriptingInfo;

@end

