/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIControl.h>

@class UIImageView;

@interface UISlider : UIControl <NSCoding>
{
    float _value;
    float _minValue;
    float _maxValue;
    struct __CFDictionary *_contentLookup;
    UIImageView *_minValueImageView;
    UIImageView *_maxValueImageView;
    UIImageView *_thumbView;
    UIImageView *_minTrackView;
    UIImageView *_maxTrackView;
    struct {
        unsigned int continuous:1;
        unsigned int animating:1;
        unsigned int showValue:1;
        unsigned int creatingSnapshot:1;
    } _sliderFlags;
    float _hitOffset;
}

- (id)init;
- (id)initWithFrame:(struct CGRect)fp8;
- (id)initWithCoder:(id)fp8;
- (void)_populateArchivedSubviews:(id)fp8;
- (void)encodeWithCoder:(id)fp8;
- (void)_initImages;
- (void)_initSubviews;
- (void)dealloc;
- (void)setThumbImage:(id)fp8 forState:(unsigned int)fp12;
- (void)setMinimumTrackImage:(id)fp8 forState:(unsigned int)fp12;
- (void)setMaximumTrackImage:(id)fp8 forState:(unsigned int)fp12;
- (id)thumbImageForState:(unsigned int)fp8;
- (id)minimumTrackImageForState:(unsigned int)fp8;
- (id)maximumTrackImageForState:(unsigned int)fp8;
- (id)currentThumbImage;
- (id)currentMinimumTrackImage;
- (id)currentMaximumTrackImage;
- (void)setMinimumValueImage:(id)fp8;
- (id)minimumValueImage;
- (void)setMaximumValueImage:(id)fp8;
- (id)maximumValueImage;
- (struct CGRect)minimumValueImageRectForBounds:(struct CGRect)fp8;
- (struct CGRect)maximumValueImageRectForBounds:(struct CGRect)fp8;
- (struct CGRect)trackRectForBounds:(struct CGRect)fp8;
- (struct CGRect)thumbRectForBounds:(struct CGRect)fp8 trackRect:(struct CGRect)fp24 value:(float)fp40;
- (struct CGSize)sizeThatFits:(struct CGSize)fp8;
- (void)setFrame:(struct CGRect)fp8;
- (void)setBounds:(struct CGRect)fp8;
- (void)layoutSubviews;
- (void)_layoutSubviewsForBoundsChange:(BOOL)fp8;
- (void)_updateAppearanceForEnabled:(BOOL)fp8;
- (void)setEnabled:(BOOL)fp8;
- (void)setHighlighted:(BOOL)fp8;
- (void)setSelected:(BOOL)fp8;
- (void)setContinuous:(BOOL)fp8;
- (BOOL)isContinuous;
- (float)value;
- (void)setValue:(float)fp8;
- (void)setValue:(float)fp8 animated:(BOOL)fp12;
- (void)_setValue:(float)fp8 andSendAction:(BOOL)fp12;
- (float)minimumValue;
- (void)setMinimumValue:(float)fp8;
- (float)maximumValue;
- (void)setMaximumValue:(float)fp8;
- (void)_sliderAnimationWillStart:(id)fp8 context:(void *)fp12;
- (void)_sliderAnimationDidStop:(id)fp8 finished:(id)fp12 context:(void *)fp16;
- (void)_sendDelayedActions;
- (BOOL)beginTrackingAt:(struct CGPoint)fp8 withEvent:(struct __GSEvent *)fp16;
- (BOOL)continueTrackingAt:(struct CGPoint)fp8 previous:(struct CGPoint)fp16 withEvent:(struct __GSEvent *)fp24;
- (void)endTrackingAt:(struct CGPoint)fp8 previous:(struct CGPoint)fp16 withEvent:(struct __GSEvent *)fp24;
- (BOOL)cancelMouseTracking;
- (void)_controlMouseDown:(struct __GSEvent *)fp8;
- (void)_controlMouseUp:(struct __GSEvent *)fp8;
- (void)_controlMouseDragged:(struct __GSEvent *)fp8;
- (BOOL)beginTrackingWithTouch:(id)fp8 withEvent:(id)fp12;
- (BOOL)continueTrackingWithTouch:(id)fp8 withEvent:(id)fp12;
- (void)endTrackingWithTouch:(id)fp8 withEvent:(id)fp12;
- (void)_controlTouchBegan:(id)fp8 withEvent:(id)fp12;
- (void)_controlTouchMoved:(id)fp8 withEvent:(id)fp12;
- (void)_controlTouchEnded:(id)fp8 withEvent:(id)fp12;
- (BOOL)cancelTouchTracking;

@end

