/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UISlider.h>

@interface UISlider (UISliderContentLookup)
- (void)_setContent:(id)fp8 forState:(unsigned int)fp12;
- (void)_setThumbImage:(id)fp8 forStates:(unsigned int)fp12;
- (void)_setMinimumTrackImage:(id)fp8 forStates:(unsigned int)fp12;
- (void)_setMaximumTrackImage:(id)fp8 forStates:(unsigned int)fp12;
- (id)_contentForState:(unsigned int)fp8;
- (id)_thumbImageForState:(unsigned int)fp8;
- (id)_minimumTrackImageForState:(unsigned int)fp8;
- (id)_maximumTrackImageForState:(unsigned int)fp8;
@end

