/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@class UITabBar;

@interface UITabBarSwappableImageView : UIView
{
    id _value;
    id _alternate;
    BOOL _showAlternate;
    BOOL _flipped;
    int _currentAnimation;
    UITabBar *_tabBar;
    int _buttonTag;
}

- (id)initWithImage:(id)fp8 alternateImage:(id)fp12;
- (void)dealloc;
- (void)setCurrentImage;
- (void)showAlternateImage:(BOOL)fp8;
- (void)setFlipped:(BOOL)fp8;
- (void)animateImage:(float)fp8 withTabBar:(id)fp12 withTag:(int)fp16;
- (void)animationDidStop:(id)fp8 finished:(BOOL)fp12;

@end

