/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIViewController.h>

#import "NSCoding-Protocol.h"
#import "UITabBarDelegate-Protocol.h"

@class NSArray, NSMutableArray, UINavigationController, UITabBar, UIView;

@interface UITabBarController : UIViewController <UITabBarDelegate, NSCoding>
{
    UITabBar *_tabBar;
    UIView *_containerView;
    UIView *_viewControllerTransitionView;
    NSMutableArray *_viewControllers;
    id _tabBarItemsToViewControllers;
    UIViewController *_selectedViewController;
    UINavigationController *_moreNavigationController;
    NSArray *_customizableViewControllers;
    id <UITabBarControllerDelegate> _delegate;
    UIViewController *_selectedViewControllerDuringWillAppear;
    struct {
        unsigned int isShown:1;
        unsigned int isShowingMoreItem:1;
        unsigned int needsToRebuildItems:1;
        unsigned int isBarHidden:1;
    } _tabBarControllerFlags;
}

- (id)init;
- (id)initWithCoder:(id)fp8;
- (void)_populateArchivedChildViewControllers:(id)fp8;
- (void)encodeWithCoder:(id)fp8;
- (void)dealloc;
- (void)viewWillLayoutSubviews;
- (void)loadView;
- (void)viewWillAppear:(BOOL)fp8;
- (void)viewDidAppear:(BOOL)fp8;
- (void)viewWillDisappear:(BOOL)fp8;
- (void)viewDidDisappear:(BOOL)fp8;
- (void)purgeMemoryForReason:(int)fp8;
- (void)updateTabBarItemForViewController:(id)fp8;
- (id)viewControllers;
- (void)_configureTargetActionForTabBarItem:(id)fp8;
- (void)setViewControllers:(id)fp8;
- (void)_rebuildTabBarItemsAnimated:(BOOL)fp8;
- (void)setViewControllers:(id)fp8 animated:(BOOL)fp12;
- (id)selectedViewController;
- (void)setSelectedViewController:(id)fp8;
- (unsigned int)selectedIndex;
- (void)setSelectedIndex:(unsigned int)fp8;
- (BOOL)_allowsCustomizing;
- (id)moreNavigationController;
- (id)customizableViewControllers;
- (void)setCustomizableViewControllers:(id)fp8;
- (void)beginCustomizingTabBar:(id)fp8;
- (void)tabBar:(id)fp8 willEndCustomizingItems:(id)fp12 changed:(BOOL)fp16;
- (void)tabBar:(id)fp8 didEndCustomizingItems:(id)fp12 changed:(BOOL)fp16;
- (void)animationDidStop:(id)fp8 finished:(id)fp12 context:(void *)fp16;
- (void)hideTabBarWithTransition:(int)fp8;
- (void)showTabBarWithTransition:(int)fp8;
- (id)allViewControllers;
- (id)tabBar;
- (void)tabBarItemClicked:(id)fp8;
- (void)setSelectedTabBarItem:(id)fp8;
- (void)transitionFromViewController:(id)fp8 toViewController:(id)fp12;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (id)rotatingHeaderView;
- (id)rotatingFooterView;
- (void)willRotateToInterfaceOrientation:(int)fp8 duration:(double)fp12;
- (void)willAnimateFirstHalfOfRotationToInterfaceOrientation:(int)fp8 duration:(double)fp12;
- (void)didAnimateFirstHalfOfRotationToInterfaceOrientation:(int)fp8;
- (void)willAnimateSecondHalfOfRotationFromInterfaceOrientation:(int)fp8 duration:(double)fp12;
- (void)didRotateFromInterfaceOrientation:(int)fp8;
- (id)delegate;
- (void)setDelegate:(id)fp8;

@end

