/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@class NSMutableArray, UIImageView, UITabBar, UITabBarItem, UITabBarItemProxy;

@interface UITabBarCustomizeView : UIView
{
    UITabBar *_tabBar;
    NSMutableArray *_proxies;
    NSMutableArray *_fixedItems;
    UITabBarItemProxy *_draggingProxy;
    UITabBarItem *_draggingItem;
    UIImageView *_dragImage;
    UIImageView *_replacementGlow;
    UITabBarItem *_replaceItem;
    struct CGPoint _startPoint;
}

- (void)setTabBar:(id)fp8 currentItems:(id)fp12 availableItems:(id)fp16;
- (void)dealloc;
- (void)layoutSubviews;
- (BOOL)canHandleSwipes;
- (void)touchesBegan:(id)fp8 withEvent:(id)fp12;
- (void)touchesMoved:(id)fp8 withEvent:(id)fp12;
- (void)touchesEnded:(id)fp8 withEvent:(id)fp12;
- (void)adjustDragImageWithTouches:(id)fp8 withEvent:(id)fp12;
- (id)itemInTabBarWithTouches:(id)fp8 withEvent:(id)fp12;
- (void)tabBarTouchesBegan:(id)fp8 withEvent:(id)fp12;
- (void)tabBarTouchesMoved:(id)fp8 withEvent:(id)fp12;
- (void)tabBarTouchesEnded:(id)fp8 withEvent:(id)fp12;
- (void)_finishTouchesEndedChangeAnimation:(id)fp8 finished:(id)fp12 context:(id)fp16;

@end

