/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UITabBar.h>

@interface UITabBar (UITabBarPrivate)
+ (float)defaultHeightForBarSize:(int)fp8;
- (void)_tabBarFinishedAnimating;
- (void)dismissCustomizeSheet:(BOOL)fp8;
- (id)hitTest:(struct CGPoint)fp8 withEvent:(id)fp16;
- (void)touchesBegan:(id)fp8 withEvent:(id)fp12;
- (void)touchesMoved:(id)fp8 withEvent:(id)fp12;
- (void)touchesEnded:(id)fp8 withEvent:(id)fp12;
- (void)setBadgeValue:(id)fp8 forButton:(int)fp12;
- (void)setBadgeGlyph:(id)fp8 forButton:(int)fp12;
- (void)setBadgeAnimated:(BOOL)fp8 forButton:(int)fp12;
- (BOOL)onStateForButton:(int)fp8;
- (void)setOnStateForButton:(BOOL)fp8 forButton:(int)fp12;
- (void)setFrame:(struct CGRect)fp8;
- (void)drawRect:(struct CGRect)fp8;
- (id)buttonItems;
- (void)setButtonItems:(id)fp8;
@end

