/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@interface UITabBarButtonBadge : UIView
{
    UIView *_value;
    UIView *_background;
    UIView *_alternate;
}

- (id)initWithValue:(id)fp8 blinks:(BOOL)fp12;
- (void)dealloc;
- (struct CGSize)sizeThatFits:(struct CGSize)fp8;
- (void)setValue:(id)fp8;
- (void)layoutSubviews;
- (void)setBlinks:(BOOL)fp8;

@end

