/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@class NSArray, UITabBarItem;

@interface UITabBar : UIView
{
    UIView *_customizeView;
    id /*XXX:<UITabBarDelegate>*/ _delegate;
    NSArray *_items;
    UITabBarItem *_selectedItem;
    NSArray *_customizationItems;
    struct {
        unsigned int roundsCorners:1;
        unsigned int alertShown:1;
        unsigned int wasEnabled:1;
        unsigned int customized:1;
        unsigned int downButtonSentAction:1;
    } _tabBarFlags;
    NSArray *_buttonItems;
    struct __CFArray *_hiddenItems;
}

- (id)initWithCoder:(id)fp8;
- (void)_populateArchivedSubviews:(id)fp8;
- (void)encodeWithCoder:(id)fp8;
- (void)dealloc;
- (void)setItems:(id)fp8;
- (id)items;
- (void)setSelectedItem:(id)fp8;
- (id)selectedItem;
- (void)_sendAction:(id)fp8 withEvent:(id)fp12;
- (void)setItems:(id)fp8 animated:(BOOL)fp12;
- (struct CGSize)sizeThatFits:(struct CGSize)fp8;
- (void)setBounds:(struct CGRect)fp8;
- (void)layoutSubviews;
- (void)beginCustomizingItems:(id)fp8;
- (BOOL)endCustomizingAnimated:(BOOL)fp8;
- (BOOL)isCustomizing;
- (id)delegate;
- (void)setDelegate:(id)fp8;

@end

