/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIControl.h>

@class NSArray, UIFont;

@interface UITableViewIndex : UIControl
{
    NSArray *_titles;
    UIFont *_font;
    int _selectedSection;
    BOOL _pastTop;
    BOOL _pastBottom;
    struct CGSize _cachedSize;
    struct CGSize _cachedSizeToFit;
}

- (id)initWithFrame:(struct CGRect)fp8;
- (void)dealloc;
- (struct CGSize)sizeThatFits:(struct CGSize)fp8;
- (void)setTitles:(id)fp8;
- (id)titles;
- (void)setFont:(id)fp8;
- (id)font;
- (id)selectedSectionTitle;
- (void)drawRect:(struct CGRect)fp8;
- (void)_selectSectionForTouch:(id)fp8 withEvent:(id)fp12;
- (BOOL)beginTrackingWithTouch:(id)fp8 withEvent:(id)fp12;
- (BOOL)continueTrackingWithTouch:(id)fp8 withEvent:(id)fp12;
- (void)endTrackingWithTouch:(id)fp8 withEvent:(id)fp12;
- (void)cancelTrackingWithEvent:(id)fp8;
- (id)_createTouchesWithMouseEvent:(struct __GSEvent *)fp8 phase:(int)fp12;
- (void)mouseDown:(struct __GSEvent *)fp8;
- (void)mouseDragged:(struct __GSEvent *)fp8;
- (void)mouseUp:(struct __GSEvent *)fp8;
- (BOOL)pastBottom;
- (BOOL)pastTop;
- (int)selectedSection;

@end

