/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@class NSString, UIImage, UIImageView, UILabel;

@interface UITableViewCell : UIView <NSCoding>
{
    id _target;
    SEL _editAction;
    SEL _accessoryAction;
    id _editingData;
    float _rightMargin;
    int _indentationLevel;
    float _indentationWidth;
    NSString *_reuseIdentifier;
    UIView *_contentView;
    UIImage *_image;
    UIImage *_selectedImage;
    UILabel *_textLabel;
    UIImageView *_imageView;
    UIView *_backgroundView;
    UIView *_selectedBackgroundView;
    struct __CFDictionary *_unhighlightedStates;
    struct {
        unsigned int showingDeleteConfirmation:1;
        unsigned int separatorStyle:3;
        unsigned int selectionStyle:3;
        unsigned int selectionFadeFraction:11;
        unsigned int editing:1;
        unsigned int editingStyle:3;
        unsigned int accessoryType:3;
        unsigned int showsAccessoryWhenEditing:1;
        unsigned int showsReorderControl:1;
        unsigned int showDisclosure:1;
        unsigned int showTopSeparator:1;
        unsigned int disclosureClickable:1;
        unsigned int disclosureStyle:1;
        unsigned int showingRemoveControl:1;
        unsigned int alignment:3;
        unsigned int sectionLocation:3;
        unsigned int tableViewStyle:1;
        unsigned int shouldIndentWhileEditing:1;
        unsigned int fontSet:1;
        unsigned int usingDefaultSelectedBackgroundView:1;
    } _tableCellFlags;
    UIView *_accessoryView;
    UIView *_customAccessoryView;
}

- (id)init;
- (id)initWithFrame:(struct CGRect)fp8;
- (id)initWithFrame:(struct CGRect)fp8 reuseIdentifier:(id)fp24;
- (id)initWithCoder:(id)fp8;
- (void)_populateArchivedSubviews:(id)fp8;
- (void)encodeWithCoder:(id)fp8;
- (void)dealloc;
- (void)setText:(id)fp8;
- (id)text;
- (void)_setFont:(id)fp8 layout:(BOOL)fp12;
- (void)setFont:(id)fp8;
- (id)font;
- (void)setTextAlignment:(int)fp8;
- (int)textAlignment;
- (void)setLineBreakMode:(int)fp8;
- (int)lineBreakMode;
- (void)setTextColor:(id)fp8;
- (id)textColor;
- (void)setSelectedTextColor:(id)fp8;
- (id)selectedTextColor;
- (void)setImage:(id)fp8;
- (id)image;
- (void)setSelectedImage:(id)fp8;
- (id)selectedImage;
- (UIView *)contentView;
- (void)setBackgroundView:(id)fp8;
- (id)backgroundView;
- (void)setSelectedBackgroundView:(id)fp8;
- (id)selectedBackgroundView;
- (void)setSeparatorStyle:(int)fp8;
- (int)separatorStyle;
- (void)setReuseIdentifier:(id)fp8;
- (id)reuseIdentifier;
- (void)prepareForReuse;
- (void)setSelectionStyle:(int)fp8;
- (int)selectionStyle;
- (void)setSelected:(BOOL)fp8;
- (BOOL)isSelected;
#if 1 // iPhoneOS 3.x
- (BOOL)_isHighlighted;
- (BOOL)isHighlighted;
- (float)selectionPercent;
#endif
- (void)_deselectAnimationFinished;
- (void)setSelected:(BOOL)fp8 animated:(BOOL)fp12;
- (void)setEditingStyle:(int)fp8;
- (int)editingStyle;
- (void)setShowsReorderControl:(BOOL)fp8;
- (BOOL)showsReorderControl;
- (void)setShouldIndentWhileEditing:(BOOL)fp8;
- (BOOL)shouldIndentWhileEditing;
- (void)setAccessoryType:(int)fp8;
- (int)accessoryType;
- (void)setAccessoryView:(id)fp8;
- (id)accessoryView;
- (void)setHidesAccessoryWhenEditing:(BOOL)fp8;
- (BOOL)hidesAccessoryWhenEditing;
- (void)setIndentationLevel:(int)fp8;
- (int)indentationLevel;
- (void)setIndentationWidth:(float)fp8;
- (float)indentationWidth;
- (void)setEditing:(BOOL)fp8;
- (void)setEditing:(BOOL)fp8 animated:(BOOL)fp12;
- (BOOL)isEditing;
- (void)setShowingDeleteConfirmation:(BOOL)fp8;
- (BOOL)showingDeleteConfirmation;
- (float)_editingButtonOffset;
- (struct CGRect)_delegateConfirmationRect;
- (struct CGRect)backgroundRectForBounds:(struct CGRect)fp8;
- (struct CGRect)contentRectForBounds:(struct CGRect)fp8;
- (struct CGRect)textRectForContentRect:(struct CGRect)fp8;
- (struct CGRect)imageRectForContentRect:(struct CGRect)fp8;
- (struct CGRect)editRectForBounds:(struct CGRect)fp8;
- (struct CGRect)accessoryRectForBounds:(struct CGRect)fp8;
- (struct CGRect)reorderRectForBounds:(struct CGRect)fp8;
- (void)setTarget:(id)fp8;
- (id)target;
- (void)setEditAction:(SEL)fp8;
- (SEL)editAction;
- (void)setAccessoryAction:(SEL)fp8;
- (SEL)accessoryAction;
- (void)drawRect:(struct CGRect)fp8;
#if 1 // iPhoneOS 3.x
- (void)setDrawingEnabled:(BOOL)fp8;
#endif
- (void)_setIsAncestorOfFirstResponder:(BOOL)fp8;
- (void)removeFromSuperview;
- (void)layoutSubviews;
- (void)setBackgroundColor:(id)fp8;
- (void)touchesBegan:(id)fp8 withEvent:(id)fp12;
- (void)touchesMoved:(id)fp8 withEvent:(id)fp12;
- (void)touchesEnded:(id)fp8 withEvent:(id)fp12;
- (void)touchesCancelled:(id)fp8 withEvent:(id)fp12;
- (int)sectionLocation;
- (void)_setupSelectedBackgroundView;
- (void)setSectionLocation:(int)fp8;
- (void)setSectionLocation:(int)fp8 animated:(BOOL)fp12;

@end

