/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UITabBarItem.h>

@interface UITabBarItem (UITabBarItem_Private)
- (BOOL)isSystemItem;
- (int)systemItem;
- (void)setView:(id)fp8;
- (id)view;
- (void)setViewIsCustom:(BOOL)fp8;
- (BOOL)viewIsCustom;
- (void)setAnimatedBadge:(BOOL)fp8;
- (BOOL)animatedBadge;
- (void)setSelectedImage:(id)fp8;
- (id)selectedImage;
- (void)setUnselectedImage:(id)fp8;
- (id)unselectedImage;
- (void)setTarget:(id)fp8;
- (id)target;
- (void)setAction:(SEL)fp8;
- (SEL)action;
- (id)_internalTitle;
- (id)_internalTemplateImage;
@end

