/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIBarItem.h>

@class NSSet, NSString, UIImage, UIView;

@interface UITabBarItem : UIBarItem
{
    NSString *_title;
    NSSet *_possibleTitles;
    SEL _action;
    id _target;
    UIImage *_image;
    UIImage *_selectedImage;
    UIImage *_unselectedImage;
    CDAnonymousStruct2 _imageInsets;
    NSString *_badgeValue;
    UIView *_view;
    int _tag;
    struct {
        unsigned int enabled:1;
        unsigned int style:3;
        unsigned int isSystemItem:1;
        unsigned int systemItem:7;
        unsigned int viewIsCustom:1;
        unsigned int animatedBadge:1;
        unsigned int customSelectedImage:1;
        unsigned int customUnselectedImage:1;
    } _tabBarItemFlags;
}

- (id)init;
- (id)initWithTitle:(id)fp8 image:(id)fp12 tag:(int)fp16;
- (id)initWithTabBarSystemItem:(int)fp8 tag:(int)fp12;
- (id)initWithCoder:(id)fp8;
- (void)encodeWithCoder:(id)fp8;
- (void)dealloc;
- (void)setEnabled:(BOOL)fp8;
- (BOOL)isEnabled;
- (void)setTitle:(id)fp8;
- (id)title;
- (void)setImage:(id)fp8;
- (id)image;
- (void)setImageInsets:(CDAnonymousStruct2)fp8;
- (CDAnonymousStruct2)imageInsets;
- (void)setBadgeValue:(id)fp8;
- (id)badgeValue;
- (int)tag;
- (void)setTag:(int)fp8;

@end

