/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIAnimation.h>

@interface UITableCellFadeAnimation : UIAnimation
{
    BOOL _select;
}

- (id)initWithTarget:(id)fp8 select:(BOOL)fp12;
- (void)dealloc;
- (void)_appSuspended:(id)fp8;
- (void)setProgress:(float)fp8;

@end

