/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UITabBarItem.h>

@interface UITabBarItem (Static)
- (id)nextResponder;
- (id)_createViewForTabBar:(id)fp8 showingBadge:(BOOL)fp12;
- (void)_updateView;
@end

