/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@interface UITextFieldBackgroundView : UIView
{
    BOOL _active;
    float _progress;
}

- (void)_updateImages;
- (id)initWithFrame:(struct CGRect)fp8 active:(BOOL)fp24;
- (void)setFrame:(struct CGRect)fp8;
- (void)setBounds:(struct CGRect)fp8;
- (void)setActive:(BOOL)fp8;
- (void)setProgress:(float)fp8;
- (BOOL)ignoresMouseEvents;

@end

