/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIScrollView.h>

#import <UIKit/UITextInputTraits-Protocol.h>

@class DOMHTMLElement, UIColor, UIDelayedAction, UIFont, UITouch, UIWebDocumentView, WebCoreFrameBridge, WebFrame;

/*XXX:*/typedef struct {
    char _field1;
    union {
        struct {
            id _field1;
            id _field2;
        } _field1;
        struct __GSEvent *_field2;
    } _field2;
} CDAnonymousStruct14;

@interface UITextView : UIScrollView <UITextInputTraits>
{
    WebFrame *m_frame;
    WebCoreFrameBridge *m_bridge;
    DOMHTMLElement *m_body;
    int m_marginTop;
    UIDelayedAction *m_selectionTimer;
    UIDelayedAction *m_longPressAction;
    struct CGPoint m_touchPoint;
    struct CGPoint m_touchOffset;
    UITouch *m_syntheticTouch;
    BOOL m_selecting;
    BOOL m_handlingMouse;
    BOOL m_sentMouseDown;
    BOOL m_passMouseDownToOther;
    BOOL m_scrollOnMouseUp;
    UIWebDocumentView *m_webView;
    UIFont *m_font;
    UIColor *m_textColor;
    int m_textAlignment;
    struct _NSRange m_selectedRange;
    BOOL m_editable;
}

- (id)initWithFrame:(struct CGRect)fp8;
- (id)initWithFrame:(struct CGRect)fp8 webView:(id)fp24;
- (id)initWithCoder:(id)fp8;
- (void)_populateArchivedSubviews:(id)fp8;
- (void)encodeWithCoder:(id)fp8;
- (void)commonInitWithWebDocumentView:(id)fp8 isDecoding:(BOOL)fp12;
- (void)dealloc;
- (void)registerForEditingDelegateNotification:(id)fp8 selector:(SEL)fp12;
- (BOOL)_alwaysHandleScrollerMouseEvent;
- (struct CGSize)tileSizeForSize:(struct CGSize)fp8;
- (id)styleString;
- (void)recalculateStyle;
- (void)didMoveToSuperview;
- (void)updateWebViewObjects;
- (BOOL)becomeFirstResponder;
- (BOOL)resignFirstResponder;
- (BOOL)canBecomeFirstResponder;
- (BOOL)canResignFirstResponder;
- (void)ensureSelection;
- (struct CGPoint)constrainedPoint:(struct CGPoint)fp8;
- (void)textLoupeTimerAction;
- (id)_syntheticTouch;
- (void)callSuperTouchBegan:(CDAnonymousStruct14 *)fp8;
- (void)callSuperTouchMoved:(CDAnonymousStruct14 *)fp8;
- (void)callSuperTouchEnded:(CDAnonymousStruct14 *)fp8;
- (void)touchBegan:(CDAnonymousStruct14 *)fp8 atLocation:(struct CGPoint)fp12;
- (void)touchMoved:(CDAnonymousStruct14 *)fp8 atLocation:(struct CGPoint)fp12;
- (void)touchEnded:(CDAnonymousStruct14 *)fp8 atLocation:(struct CGPoint)fp12 loupeActive:(BOOL)fp20 loupeTerminalPoint:(struct CGPoint)fp24;
- (void)touchesBegan:(id)fp8 withEvent:(id)fp12;
- (void)touchesMoved:(id)fp8 withEvent:(id)fp12;
- (void)touchesEnded:(id)fp8 withEvent:(id)fp12;
- (void)touchesCancelled:(id)fp8 withEvent:(id)fp12;
- (id)hitTest:(struct CGPoint)fp8 withEvent:(id)fp16;
- (void)mouseDown:(struct __GSEvent *)fp8;
- (void)mouseDragged:(struct __GSEvent *)fp8;
- (void)mouseUp:(struct __GSEvent *)fp8;
#if 1 // iPhoneOS 3.x
- (void)insertText:(id)fp8;
#endif
- (void)scrollRectToVisible:(struct CGRect)fp8 animated:(BOOL)fp24;
- (void)webViewDidChange:(id)fp8;
- (void)performBecomeEditableTasks;
- (void)setFrame:(struct CGRect)fp8;
- (void)setSelectionWithPoint:(struct CGPoint)fp8;
- (void)setSelectionToStart;
- (void)setSelectionToEnd;
- (struct CGRect)rectForSelection:(struct _NSRange)fp8;
- (void)scrollToMakeCaretVisible:(BOOL)fp8;
- (void)setContentToHTMLString:(id)fp8;
- (id)contentAsHTMLString;
- (id)textInputTraits;
- (void)forwardInvocation:(id)fp8;
- (id)methodSignatureForSelector:(SEL)fp8;
- (id)font;
- (void)setFont:(id)fp8;
- (id)textColor;
- (void)setTextColor:(id)fp8;
- (BOOL)hasText;
- (id)text;
- (void)setText:(id)fp8;
- (int)textAlignment;
- (void)setTextAlignment:(int)fp8;
- (struct _NSRange)selectedRange;
- (void)setSelectedRange:(struct _NSRange)fp8;
- (BOOL)isEditable;
- (void)setEditable:(BOOL)fp8;
- (int)marginTop;
- (void)setMarginTop:(int)fp8;
- (struct CGRect)visibleRect;
- (struct CGRect)visibleTextRect;
- (id)webView;
- (void)scrollRangeToVisible:(struct _NSRange)fp8;
- (BOOL)keyboardInput:(id)fp8 shouldReplaceTextInRange:(struct _NSRange)fp12 replacementText:(id)fp20;
- (BOOL)keyboardInput:(id)fp8 shouldInsertText:(id)fp12 isMarkedText:(BOOL)fp16;
- (BOOL)keyboardInputShouldDelete:(id)fp8;
- (BOOL)keyboardInputChanged:(id)fp8;
- (void)keyboardInputChangedSelection:(id)fp8;
- (id)keyboardInputOverlayContainer:(id)fp8;
- (int)keyboardInput:(id)fp8 positionForAutocorrection:(id)fp12;
- (void)setBottomBufferHeight:(float)fp8;
- (float)bottomBufferHeight;
- (void)setShowScrollerIndicators:(BOOL)fp8;
- (BOOL)showScrollerIndicators;
- (void)displayScrollerIndicators;
- (void)setOffset:(struct CGPoint)fp8;
- (struct CGPoint)offset;
- (void)setAllowsRubberBanding:(BOOL)fp8;
- (void)setScrollingEnabled:(BOOL)fp8;
- (BOOL)scrollingEnabled;
- (void)setAllowsFourWayRubberBanding:(BOOL)fp8;
- (void)setScrollerIndicatorSubrect:(struct CGRect)fp8;

@end

