/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

@protocol UITextInputTraits <NSObject>
- (BOOL)isSecureTextEntry;
- (void)setSecureTextEntry:(BOOL)fp8;
- (BOOL)enablesReturnKeyAutomatically;
- (void)setEnablesReturnKeyAutomatically:(BOOL)fp8;
- (int)returnKeyType;
- (void)setReturnKeyType:(int)fp8;
- (int)keyboardAppearance;
- (void)setKeyboardAppearance:(int)fp8;
- (int)keyboardType;
- (void)setKeyboardType:(int)fp8;
- (int)autocorrectionType;
- (void)setAutocorrectionType:(int)fp8;
- (int)autocapitalizationType;
- (void)setAutocapitalizationType:(int)fp8;
@end

