/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UILabel.h>

@interface UITextLabel : UILabel
{
}

- (struct CGSize)ellipsizedTextSize;
- (void)setColor:(id)fp8;
- (id)color;
- (void)setHighlightedColor:(id)fp8;
- (id)highlightedColor;
- (void)setCentersHorizontally:(BOOL)fp8;
- (BOOL)centersHorizontally;
- (void)setWrapsText:(BOOL)fp8;
- (BOOL)wrapsText;
- (void)setTextAutoresizesToFit:(BOOL)fp8;
- (BOOL)textAutoresizesToFit;
- (void)setMinFontSize:(float)fp8;
- (float)minFontSize;
- (void)setAlignment:(int)fp8;
- (int)alignment;
- (void)setEllipsisStyle:(int)fp8;
- (int)ellipsisStyle;
- (void)drawRect:(struct CGRect)fp8;
- (void)drawTextInRect:(struct CGRect)fp8;
- (void)drawContentsInRect:(struct CGRect)fp8;

@end

