/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@interface UITextFieldAtomBackgroundView : UIView
{
    int _atomStyle;
}

+ (id)_blueAtomBackgroundImage;
+ (id)_purpleAtomBackgroundImage;
- (id)initWithFrame:(struct CGRect)fp8;
- (void)drawRect:(struct CGRect)fp8;
- (int)atomStyle;
- (void)setAtomStyle:(int)fp8;

@end

