/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UITextInputTraits-Protocol.h>

@protocol UITextInputTraits_Private <NSObject, UITextInputTraits>
- (void)takeTraitsFrom:(id)fp8;
- (BOOL)contentsIsSingleValue;
- (void)setContentsIsSingleValue:(BOOL)fp8;
- (id)textSuggestionDelegate;
- (void)setTextSuggestionDelegate:(id)fp8;
- (int)textSelectionBehavior;
- (void)setTextSelectionBehavior:(int)fp8;
- (int)textLoupeVisibility;
- (void)setTextLoupeVisibility:(int)fp8;
- (unsigned int)insertionPointWidth;
- (void)setInsertionPointWidth:(unsigned int)fp8;
- (id)insertionPointColor;
- (void)setInsertionPointColor:(id)fp8;
- (struct __CFCharacterSet *)textTrimmingSet;
- (void)setTextTrimmingSet:(struct __CFCharacterSet *)fp8;
@end

