/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIWindow.h>

@class NSMutableArray;

@interface UITextEffectsWindow : UIWindow
{
    unsigned int _activeEffectsCount;
    int _orientation;
    NSMutableArray *_touchableSubviews;
}

+ (id)sharedTextEffectsWindow;
+ (id)sharedTextEffectsWindowAboveStatusBar;
- (BOOL)acceptsGlobalPoint:(struct CGPoint)fp8;
- (id)hitTest:(struct CGPoint)fp8 withEvent:(id)fp16;
- (void)setBounds:(struct CGRect)fp8;
- (BOOL)shouldExcludeFromSnapshot;
- (id)initWithFrame:(struct CGRect)fp8 output:(int)fp24 bitsPerComponent:(int)fp28;
- (void)dealloc;
- (void)didRemoveSubview:(id)fp8;
- (void)addSubview:(id)fp8;
- (void)sortSubviews;
- (int)currentOrientation;
- (void)matchDeviceOrientation;

@end

