/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@interface UITile : UIView
{
    struct CGRect _dirtyRect;
    BOOL _hasDrawnContent;
}

- (id)initWithFrame:(struct CGRect)fp8;
- (id)hitTest:(struct CGPoint)fp8 forEvent:(struct __GSEvent *)fp16;
- (void)setNeedsDisplayInRect:(struct CGRect)fp8;
- (void)setNeedsDisplay;
- (BOOL)_canDrawContent;
- (BOOL)willDrawContent;
- (void)drawRect:(struct CGRect)fp8;
- (BOOL)hasDrawnContent;
- (void)setDirtyRect:(struct CGRect)fp8;
- (void)setNeedsDisplayInDirtyRect;
- (void)invalidateContents;

@end

