/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIToolbar.h>

@interface UIToolbar (UIButtonBarButtonItem)
- (id)initInView:(id)fp8 withFrame:(struct CGRect)fp12 withItems:(CDAnonymousStruct3 *)fp28 withCount:(int)fp32;
- (id)initInView:(id)fp8 withItems:(CDAnonymousStruct3 *)fp12 withCount:(int)fp16;
@end

