/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@class NSMutableArray, UIBarButtonItem, UIBarButtonItemProxy, UIImageView, UIToolbar;

@interface UIToolbarCustomizeView : UIView
{
    UIToolbar *_toolbar;
    NSMutableArray *_proxies;
    NSMutableArray *_fixedItems;
    UIBarButtonItemProxy *_draggingProxy;
    UIBarButtonItem *_draggingItem;
    UIImageView *_dragImage;
    UIImageView *_replacementGlow;
    UIBarButtonItem *_replaceItem;
    struct CGPoint _startPoint;
}

- (void)setToolbar:(id)fp8 currentItems:(id)fp12 availableItems:(id)fp16;
- (void)dealloc;
- (void)layoutSubviews;
- (BOOL)canHandleSwipes;
- (void)touchesBegan:(id)fp8 withEvent:(id)fp12;
- (void)touchesMoved:(id)fp8 withEvent:(id)fp12;
- (void)touchesEnded:(id)fp8 withEvent:(id)fp12;
- (void)adjustDragImageWithTouches:(id)fp8 withEvent:(id)fp12;
- (id)itemInToolbarWithTouches:(id)fp8 withEvent:(id)fp12;
- (void)buttonBarTouchesBegan:(id)fp8 withEvent:(id)fp12;
- (void)buttonBarTouchesMoved:(id)fp8 withEvent:(id)fp12;
- (void)buttonBarTouchesEnded:(id)fp8 withEvent:(id)fp12;
- (void)_finishTouchesEndedChangeAnimation:(id)fp8 finished:(id)fp12 context:(id)fp16;

@end

