/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIToolbar.h>

@interface UIToolbar (UIButtonBarPrivate)
+ (Class)defaultButtonClass;
+ (Class)defaultTextButtonClass;
+ (id)defaultButtonFont;
+ (float)defaultHeight;
+ (float)defaultSelectionModeHeight;
+ (float)defaultHeightForBarSize:(int)fp8;
- (id)initInView:(id)fp8 withFrame:(struct CGRect)fp12 withItemList:(id)fp28;
- (id)initInView:(id)fp8 withItemList:(id)fp12;
- (id)createButtonWithDescription:(id)fp8;
- (void)positionButtons:(id)fp8 tags:(int *)fp12 count:(int)fp16 group:(int)fp20;
- (void)_buttonBarFinishedAnimating;
- (void)showButtons:(int *)fp8 withCount:(int)fp12 withDuration:(double)fp16;
- (void)registerButtonGroup:(int)fp8 withButtons:(int *)fp12 withCount:(int)fp16;
- (void)showButtonGroup:(int)fp8 withDuration:(double)fp12;
- (int)currentButtonGroup;
- (void)getVisibleButtonTags:(int *)fp8 count:(unsigned int *)fp12 maxItems:(unsigned int)fp16;
- (void)setButtonBarTrackingMode:(int)fp8;
- (void)customize:(const int *)fp8 withCount:(int)fp12;
- (void)dismissCustomizeSheet:(BOOL)fp8;
- (id)hitTest:(struct CGPoint)fp8 forEvent:(struct __GSEvent *)fp16;
- (id)hitTest:(struct CGPoint)fp8 withEvent:(id)fp16;
- (void)mouseDown:(struct __GSEvent *)fp8;
- (void)mouseDragged:(struct __GSEvent *)fp8;
- (void)mouseUp:(struct __GSEvent *)fp8;
- (void)touchesBegan:(id)fp8 withEvent:(id)fp12;
- (void)touchesMoved:(id)fp8 withEvent:(id)fp12;
- (void)touchesEnded:(id)fp8 withEvent:(id)fp12;
- (int)selectedButton;
- (void)showSelectionForButton:(int)fp8;
- (void)setBadgeValue:(id)fp8 forButton:(int)fp12;
- (void)setBadgeGlyph:(id)fp8 forButton:(int)fp12;
- (void)setBadgeAnimated:(BOOL)fp8 forButton:(int)fp12;
- (BOOL)onStateForButton:(int)fp8;
- (void)setOnStateForButton:(BOOL)fp8 forButton:(int)fp12;
- (void)animateWithDuration:(float)fp8 forButton:(int)fp12;
- (void)setBounds:(struct CGRect)fp8;
- (void)setFrame:(struct CGRect)fp8;
- (void)drawRect:(struct CGRect)fp8;
- (id)buttonItems;
- (void)setButtonItems:(id)fp8;
@end

