/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@class UIBezierPath;

@interface UITouchDiagnosticsLayer : UIView
{
    struct __CFArray *_eventQueue;
    UIBezierPath *_hitRectsPath;
    UIBezierPath *_customHitRectsPath;
    UIBezierPath *_chargesPath;
    BOOL _trackTouchEvents;
    BOOL _displayTouchEvents;
    BOOL _displayHitRects;
    BOOL _displayChargeMap;
}

- (id)initWithFrame:(struct CGRect)fp8;
- (void)dealloc;
- (BOOL)layerRespondsToEvents:(id)fp8;
- (void)_addLayerHitRects:(id)fp8 toPath:(id)fp12 customPath:(id)fp16;
- (void)drawChargeMap;
- (void)drawRect:(struct CGRect)fp8;
- (void)diagnoseEvent:(struct __GSEvent *)fp8;
- (BOOL)pointInside:(struct CGPoint)fp8 forEvent:(struct __GSEvent *)fp16;
- (void)refreshHitRects;
- (void)setTrackTouchEvents:(BOOL)fp8;
- (void)setDisplayHitRects:(BOOL)fp8;
- (void)setDisplayTouchEvents:(BOOL)fp8;
- (void)setDisplayChargeMap:(BOOL)fp8;
- (void)tearDown;

@end

