/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIToolbar.h>

@interface UIToolbar (SynthEvents)
- (BOOL)_isHidden:(id)fp8;
- (id)_buttonName:(id)fp8 withType:(int)fp12;
- (id)scriptingInfoWithChildren;
@end

