/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIToolbar.h>

@interface UIToolbar (UIButtonBarInternal)
+ (float)_buttonGap;
- (void)_alertWillShow:(BOOL)fp8 duration:(float)fp12;
- (void)_alertDidHide;
- (void)_positionToolbarButtons:(id)fp8 ignoringItem:(id)fp12;
@end

