/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIToolbar.h>

@interface UIToolbar (Static)
- (id)_descriptionForTag:(int)fp8;
- (void)_buttonDown:(id)fp8;
- (void)_buttonDownDelayed:(id)fp8;
- (void)_buttonUp:(id)fp8;
- (void)_buttonCancel:(id)fp8;
- (void)_adjustButtonSelection:(id)fp8;
- (id)_buttonWithDescription:(id)fp8;
- (void)_customizeWithCurrentButtons:(id)fp8 availableButton:(id)fp12;
- (void)_dismissCustomizeSheet:(BOOL)fp8;
- (void)_customizeDoneButtonAction:(id)fp8;
- (void)_finishCustomizeAnimation:(id)fp8;
- (void)_showButtons:(int *)fp8 withCount:(int)fp12 group:(int)fp16 withDuration:(double)fp20 adjustPositions:(BOOL)fp28 skipTag:(int)fp32;
- (id)_currentButtons;
- (id)_configureFromOldButton:(id)fp8 toNewButtonWithTag:(int)fp12 skipTag:(int)fp16;
- (void)_finishButtonAnimation:(int)fp8 forButton:(int)fp12;
- (void)_customizeWithAvailableItems:(id)fp8;
- (void)_configureToolbarReplacingItem:(id)fp8 withNewItem:(id)fp12 dragging:(BOOL)fp16 swapping:(BOOL)fp20;
- (void)_updateButtonBarForNewFrame;
@end

