/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIAnimation.h>

@interface UITransformAnimation : UIAnimation
{
    struct CGAffineTransform _startTransform;
    struct CGAffineTransform _endTransform;
}

- (void)setStartTransform:(struct CGAffineTransform)fp8;
- (void)setEndTransform:(struct CGAffineTransform)fp8;
- (struct CGAffineTransform)_transformWithMultiplier:(float)fp8;
- (void)setProgress:(float)fp8;
- (struct CGAffineTransform)transformForFraction:(float)fp8;

@end

