/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIThreePartButton.h>

@class NSString, UIColor, UIImage;

@interface UIValueButton : UIThreePartButton
{
    int _displayStyle;
    NSString *_labelString;
    NSString *_valueString;
    NSString *_valueStyle;
    NSString *_valueHighlightStyle;
    UIImage *_labelBadgeImage;
    float _disclosureAlpha;
    UIColor *_valueColor;
    struct {
        unsigned int disclosureShown:1;
        unsigned int unused:31;
    } _valueButtonFlags;
}

+ (float)defaultHeight;
+ (struct CGRect)frameRectForOpaqueContentRect:(struct CGRect)fp8;
+ (struct CGRect)opaqueContentRectForFrameRect:(struct CGRect)fp8;
- (void)_commonInitValueButton;
- (id)initWithFrame:(struct CGRect)fp8;
- (id)initWithTitle:(id)fp8;
- (void)dealloc;
- (id)_titleByCombiningLabelAndValue;
- (void)setValue:(id)fp8;
- (id)value;
- (void)setValueStyle:(id)fp8;
- (void)setValueHighlightStyle:(id)fp8;
- (void)setLabel:(id)fp8;
- (id)label;
- (void)setLabelBadgeImage:(id)fp8;
- (id)labelBadgeImage;
- (void)setTitle:(id)fp8;
- (void)setDisplayStyle:(int)fp8;
- (int)displayStyle;
- (void)setShowsDisclosure:(BOOL)fp8;
- (BOOL)showsDisclosure;
- (float)rightEndPadding;
- (void)setDisclosureAlpha:(float)fp8;
- (float)disclosureAlpha;
- (float)buttonEdge;
- (void)_drawValueStyleInteriorInRect:(struct CGRect)fp8 withValueColor:(id)fp24 valueFont:(id)fp28 isPressed:(BOOL)fp32;
- (void)_drawLabelAndValueStyleInteriorInRect:(struct CGRect)fp8;
- (void)drawButtonPart:(int)fp8 inRect:(struct CGRect)fp12;
- (void)setValueColor:(id)fp8;
- (void)sizeToFit;

@end

