/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@interface UIView (ZoomAnimationPrivate)
- (struct CGPoint)_scrollPointForBoundedRect:(struct CGRect)fp8 withBoundary:(struct CGRect)fp24 scale:(float)fp40;
- (float)boundedScaleForFocusRect:(struct CGRect)fp8 deviceBoundaryRect:(struct CGRect)fp24;
@end

