/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIViewController.h>

@interface UIViewController (UITabBarControllerItem)
- (id)tabBarItem;
- (void)setTabBarItem:(id)fp8;
- (id)tabBarController;
- (void)updateTabBarItemForViewController:(id)fp8;
- (id)moreListImage;
- (id)moreListSelectedImage;
- (id)moreListTableCell;
@end

