/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIView.h>

#import "UITextEffectsOrdering-Protocol.h"

@interface UIView (UITextEffectsOrdering) <UITextEffectsOrdering>
- (int)textEffectsVisibilityLevel;
- (int)compareTextEffectsOrdering:(id)fp8;
@end

