/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@interface UIView (Deprecated)
+ (void)setAnimationTransition:(int)fp8 forView:(id)fp12;
- (id)initWithSize:(struct CGSize)fp8;
- (struct CGSize)size;
- (void)setSize:(struct CGSize)fp8;
- (struct CGPoint)frameOrigin;
- (void)setFrameOrigin:(struct CGPoint)fp8;
- (id)hitTest:(struct CGPoint)fp8 forEvent:(struct __GSEvent *)fp16;
- (BOOL)pointInside:(struct CGPoint)fp8 forEvent:(struct __GSEvent *)fp16;
- (void)setEnabled:(BOOL)fp8;
- (BOOL)isEnabled;
- (void)setClipsSubviews:(BOOL)fp8;
@end

