/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@interface UIView (Animation)
+ (void)beginAnimations:(id)fp8;
+ (void)beginAnimations:(id)fp8 context:(void *)fp12;
+ (void)commitAnimations;
+ (void)endAnimations;
+ (BOOL)_pendingAnimations;
+ (void)setAnimationDelegate:(id)fp8;
+ (void)setAnimationPosition:(struct CGPoint)fp8;
+ (void)disableAnimation;
+ (void)enableAnimation;
+ (void)setAnimationsEnabled:(BOOL)fp8;
+ (BOOL)areAnimationsEnabled;
+ (void)setAnimationDuration:(double)fp8;
+ (void)setAnimationDelay:(double)fp8;
+ (void)setAnimationFrameInterval:(double)fp8;
+ (void)setAnimationStartDate:(id)fp8;
+ (void)setAnimationStartTime:(double)fp8;
+ (void)setAnimationCurve:(int)fp8;
+ (void)setAnimationRepeatCount:(float)fp8;
+ (void)setAnimationRepeatAutoreverses:(BOOL)fp8;
+ (void)setAnimationBeginsFromCurrentState:(BOOL)fp8;
+ (void)setAnimationAutoreverses:(BOOL)fp8;
+ (void)setAnimationFromCurrentState:(BOOL)fp8;
+ (void)setAnimationRoundsToInteger:(BOOL)fp8;
+ (void)setAnimationTransition:(int)fp8 forView:(id)fp12 cache:(BOOL)fp16;
+ (void)setAnimationWillStartSelector:(SEL)fp8;
+ (void)setAnimationDidStopSelector:(SEL)fp8;
- (void)addAnimation:(id)fp8 forKey:(id)fp12;
@end

