/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@interface UIView (Geometry)
- (struct CGRect)frame;
- (struct CGRect)extent;
- (void)setFrame:(struct CGRect)fp8;
- (struct CGAffineTransform)transform;
- (void)setTransform:(struct CGAffineTransform)fp8;
- (void)setMultipleTouchEnabled:(BOOL)fp8;
- (BOOL)isMultipleTouchEnabled;
- (void)setExclusiveTouch:(BOOL)fp8;
- (BOOL)isExclusiveTouch;
- (BOOL)ignoresMouseEvents;
- (id)hitTest:(struct CGPoint)fp8 withEvent:(id)fp16;
- (BOOL)pointInside:(struct CGPoint)fp8 withEvent:(id)fp16;
- (struct CGPoint)convertPoint:(struct CGPoint)fp8 toView:(id)fp16;
- (struct CGPoint)convertPoint:(struct CGPoint)fp8 fromView:(id)fp16;
- (struct CGSize)convertSize:(struct CGSize)fp8 toView:(id)fp16;
- (struct CGSize)convertSize:(struct CGSize)fp8 fromView:(id)fp16;
- (struct CGRect)convertRect:(struct CGRect)fp8 toView:(id)fp24;
- (struct CGRect)convertRect:(struct CGRect)fp8 fromView:(id)fp24;
- (struct CGRect)hitRect;
- (void)setFrame:(struct CGRect)fp8 forFields:(int)fp24;
- (void)setRotationBy:(float)fp8;
- (void)setAutoresizesSubviews:(BOOL)fp8;
- (BOOL)autoresizesSubviews;
- (void)setAutoresizingMask:(unsigned int)fp8;
- (unsigned int)autoresizingMask;
- (struct CGSize)sizeThatFits:(struct CGSize)fp8;
- (void)sizeToFit;
- (void)resizeSubviewsWithOldSize:(struct CGSize)fp8;
- (void)resizeWithOldSuperviewSize:(struct CGSize)fp8;
- (struct CGRect)bounds;
- (void)setBounds:(struct CGRect)fp8;
- (struct CGPoint)position;
- (void)setPosition:(struct CGPoint)fp8;
- (struct CGPoint)center;
- (void)setCenter:(struct CGPoint)fp8;
- (struct CGPoint)origin;
- (void)setOrigin:(struct CGPoint)fp8;
@end

