/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@class NSURL, NSURLRequest, UIAlertView, UICheckeredPatternView, UIScroller, UIWebDocumentView;

@interface UIWebViewInternal : NSObject
{
    UIScroller *scroller;
    UIWebDocumentView *documentView;
    UICheckeredPatternView *checkeredPatternView;
    id <UIWebViewDelegate> delegate;
    NSURLRequest *request;
    UIAlertView *telephoneAlertView;
    NSURL *telephoneURL;
    BOOL scalesPageToFit;
    BOOL isLoading;
    BOOL drawsCheckeredPattern;
}

@end

