/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "WAKView.h"

@class UIView, UIWebDocumentView;

@interface UIWebPlugInView : WAKView
{
    UIWebDocumentView *_webView;
    UIView *_uiView;
    struct __CFRunLoopObserver *_mainRunLoopDrawObserver;
    BOOL _isFullScreen;
}

- (id)initWithWebView:(id)fp8 plugInView:(id)fp12;
- (void)dealloc;
- (void)setFrame:(struct CGRect)fp8;
- (void)setFrameSize:(struct CGSize)fp8;
- (void)viewDidMoveToWindow;
- (void)invalidateGState;
- (id)plugInView;
- (void)reshape;
- (void)layout;
- (void)drawRect:(struct CGRect)fp8;
- (void)webPlugInInitialize;
- (void)webPlugInStart;
- (void)webPlugInStop;
- (void)webPlugInDestroy;
- (BOOL)respondsToSelector:(SEL)fp8;
- (void)forwardInvocation:(id)fp8;
- (id)methodSignatureForSelector:(SEL)fp8;
- (id)objectForWebScript;
- (void)mouseDown:(id)fp8;
- (void)mouseUp:(id)fp8;

@end

