/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIAnimation.h>

@interface UIZoomAnimation : UIAnimation
{
    float _endScale;
    float _startScale;
    struct CGPoint _endScrollPoint;
    struct CGPoint _startScrollPoint;
}

+ (float)defaultDuration;
+ (id)zoomAnimationForTarget:(id)fp8 endScale:(float)fp12 endScrollPoint:(struct CGPoint)fp16;
+ (id)zoomAnimationForTarget:(id)fp8 focusRect:(struct CGRect)fp12 deviceBoundaryRect:(struct CGRect)fp28 scale:(float)fp44;
- (void)setEndScale:(float)fp8;
- (void)setStartScale:(float)fp8;
- (void)setEndScrollPoint:(struct CGPoint)fp8;
- (void)setStartScrollPoint:(struct CGPoint)fp8;
- (void)setProgress:(float)fp8;

@end

