/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <MediaPlayer/MediaDetailScrubberControl.h>

@interface MediaDetailScrubberControl (MPInternal_DebugDetailScrubVis)
- (float)_debugDetailDisplayedDetailScrubValue;
- (void)__debugDetailToggleDetailScrubbingMode;
- (void)view:(id)fp8 handleTapWithCount:(int)fp12 event:(struct __GSEvent *)fp16 fingerCount:(int)fp20;
- (void)__debugDetailPositionAreaView:(id)fp8 forSuperview:(id)fp12;
- (id)__debugDetailCreateAreaViewInView:(id)fp8;
- (void)_debugDetailUpdateModeIndicatorView;
- (void)__debugDetailDisplayAreaView;
- (void)__debugDetailHideAreaView;
- (void)_debugDetailUpdateAllViews;
- (void)_debugDetailHideViewsForEndScrubbing;
- (void)_debugDetailNoteCenterChanged;
- (void)_debugDetailNoteWillMoveToSuperview;
- (void)_debugDetailNoteDidMoveToSuperview;
- (void)_debugDetailNoteTimeFramesDidReset;
@end

