/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@interface MediaAppTestState : NSObject
{
    BOOL _gatherPerformanceData;
    id _delegate;
}

+ (id)sharedTestState;
- (void)setGatherPerformanceData:(BOOL)fp8;
- (void)setDelegate:(id)fp8;
- (BOOL)gatherPerformanceData;
- (void)clearState;
- (void)sendPlaybackDidEndMessage:(id)fp8;

@end

