/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class UIView;

@interface MovieSnapshot : NSObject
{
    id _delegate;
    struct CGSize _size;
    int _orientation;
    float _time;
    float _originalTime;
    UIView *_snapshot;
}

+ (id)infoWithSize:(struct CGSize)fp8 orientation:(int)fp16 time:(float)fp20 delegate:(id)fp24;
- (void)dealloc;
- (id)description;
- (BOOL)prepareForSnapshotOfLayer:(id)fp8;
- (void)snapshotLayer:(id)fp8;
- (id)delegate;
- (id)snapshot;
- (float)time;

@end

