/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <MediaPlayer/MediaDetailScrubberControl.h>

@interface MovieScrubberControl : MediaDetailScrubberControl
{
}

+ (BOOL)allowLayeredFillForKnob;
- (id)initWithFrame:(struct CGRect)fp8 preferredTrackWidth:(float)fp24;
- (void)setValueAvailable:(float)fp8;
- (void)setPlayableDuration:(double)fp8;
- (const CDAnonymousStruct1 *)metrics;

@end

