/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIView.h"

@class MovieTVOutCounter, UIImageView;

@interface MovieTVHUDView : UIView
{
    int _currentState;
    MovieTVOutCounter *_counter;
    UIImageView *_playbackMode;
}

- (id)initWithFrame:(struct CGRect)fp8;
- (void)_changeState;
- (void)_fadeOut;
- (void)animationDidStop:(id)fp8;
- (void)setPlaybackState:(int)fp8;

@end

