/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class MPItem, NSDictionary, NSMutableDictionary;

@interface MPAlternateTracks : NSObject
{
    MPItem *_item;
    NSDictionary *_alternateTracks;
    NSMutableDictionary *_trackChangeDictionary;
}

- (id)initWithItem:(id)fp8;
- (void)dealloc;
- (void)beginTrackChanges;
- (void)commitTrackChanges;
- (id)currentTrackForType:(unsigned int)fp8;
- (unsigned int)indexOfCurrentTrackForType:(unsigned int)fp8;
- (void)setTrack:(id)fp8 forType:(unsigned int)fp12;
- (id)tracksForType:(unsigned int)fp8;
- (BOOL)hasTracksForTypes:(unsigned int)fp8;
- (void)reloadData;
- (id)_keyForTrackType:(unsigned int)fp8;

@end

