/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString;

@interface MPAlternateTrack : NSObject
{
    int _trackID;
    NSString *_languageCode;
    NSString *_name;
}

+ (id)createOffTrack;
+ (id)threeCharCodesForEncodedISO639_2_T:(id)fp8;
- (id)initWithDictionary:(id)fp8;
- (void)dealloc;
- (int)compare:(id)fp8;
- (id)humanReadableLanguage;
- (id)languageCode;
- (id)name;
- (void)setName:(id)fp8;
- (int)trackID;

@end

