/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIPreferencesTableCell.h"

@class UIImageView;

@interface MPAlternateTrackCell : UIPreferencesTableCell
{
    UIImageView *_checkMarkView;
    unsigned int _isChecked:1;
}

+ (void)destroyCache;
- (void)dealloc;
- (id)titleTextLabel;
- (BOOL)isChecked;
- (void)setChecked:(BOOL)fp8;
- (struct CGColor *)outlineColor;
- (id)_bezierPathForCellOutline:(int)fp8;
- (id)_bezierPath;
- (void)drawBackgroundInRect:(struct CGRect)fp8 withFade:(float)fp24;
- (void)layoutSubviews;

@end

