/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class UIImage;

@interface MPArtworkInfo : NSObject
{
    UIImage *_image;
    struct CGRect _imageSubRect;
    double _time;
}

+ (id)artworkInfoWithImage:(id)fp8 rect:(struct CGRect)fp12 time:(double)fp28;
- (void)dealloc;
- (double)time;
- (void)setTime:(double)fp8;
- (struct CGRect)imageSubRect;
- (void)setImageSubRect:(struct CGRect)fp8;
- (id)image;
- (void)setImage:(id)fp8;

@end

