/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIView.h"

@class MPFullScreenTransportControls, MPItem, MPVideoViewController, MovieScrubberControl, UINavigationBar, UINavigationButton, UINavigationItem;

@interface MPFullScreenVideoOverlay : UIView
{
    MPVideoViewController *_videoController;
    id _target;
    MPItem *_item;
    int _orientation;
    UIView *_loadingMovieIndicatorView;
    MovieScrubberControl *_scrubControl;
    MPFullScreenTransportControls *_transportControls;
    UINavigationButton *_backButton;
    UINavigationBar *_navigationBar;
    UINavigationItem *_navigationItem;
    UINavigationButton *_scaleModeButton;
    unsigned int _desiredParts;
    unsigned int _disabledParts;
    unsigned int _visibleParts;
    unsigned int _tvOutEnabled:1;
    unsigned int _wantsTick:1;
}

- (id)initWithFrame:(struct CGRect)fp8 orientation:(int)fp24;
- (void)dealloc;
- (void)didMoveToSuperview;
- (void)didMoveToWindow;
- (void)layoutSubviews;
- (void)reloadNavigationBarWithAnimation:(BOOL)fp8;
- (void)restoreSanity;
- (void)startTicking;
- (void)stopTicking;
- (id)hitTest:(struct CGPoint)fp8 forEvent:(struct __GSEvent *)fp16;
- (id)hitTest:(struct CGPoint)fp8 withEvent:(id)fp16;
- (void)setDesiredParts:(unsigned int)fp8;
- (void)setDesiredParts:(unsigned int)fp8 animate:(BOOL)fp12;
- (void)setDisabledParts:(unsigned int)fp8;
- (void)setItem:(id)fp8;
- (void)setOrientation:(int)fp8;
- (void)setTarget:(id)fp8;
- (void)setTVOutEnabled:(BOOL)fp8;
- (void)setVideoController:(id)fp8;
- (void)setVisibleParts:(unsigned int)fp8;
- (void)setVisibleParts:(unsigned int)fp8 animate:(BOOL)fp12;
- (BOOL)TVOutEnabled;
- (void)_backButtonAction:(id)fp8;
- (void)_scaleButtonAction:(id)fp8;
- (void)_tickNotification:(id)fp8;
- (void)_validityChangedNotification:(id)fp8;
- (void)_statusBarHeightChanged:(id)fp8;
- (void)scrubberControl:(id)fp8 didEnterScrubbingState:(BOOL)fp12;
- (void)scrubberControl:(id)fp8 didChangeToScrubValue:(float)fp12;
- (id)_loadingMovieIndicatorView;
- (void)_initNavigationBar;
- (void)_reloadTransportControls:(BOOL)fp8;
- (id)_scrubControlWithFrame:(struct CGRect)fp8;
- (void)_updateScrubControlWithAnimation:(BOOL)fp8;
- (void)_updateTimeBasedValues;
- (unsigned int)visibleParts;
- (id)videoController;
- (id)transportControls;
- (id)target;
- (int)orientation;
- (id)navigationBar;
- (id)item;
- (unsigned int)disabledParts;
- (unsigned int)desiredParts;

@end

