/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <MediaPlayer/MPFullScreenVideoViewController.h>

@interface MPMoviePlayerVideoViewController : MPFullScreenVideoViewController
{
    BOOL _hideNavigationBar;
}

- (void)_showOverlay;
- (BOOL)hideNavigationBar;
- (void)setHideNavigationBar:(BOOL)fp8;

@end

