/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UITableCell.h"

@interface MPPlayingIndicatorTableCell : UITableCell
{
    unsigned int _isCurrent:1;
}

- (void)drawContentInRect:(struct CGRect)fp8 selected:(BOOL)fp24;
- (void)setCurrent:(BOOL)fp8;
- (struct CGPoint)indicatorPoint;
- (struct CGColor *)indicatorColor;
- (struct CGColor *)selectedIndicatorColor;

@end

