/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <MediaPlayer/MPVideoViewController.h>

@class MPPortraitInfoOverlay, MPPortraitTransportControls, MPReflectionImageView, UINavigationBar;

@interface MPPortraitVideoViewController : MPVideoViewController
{
    MPPortraitInfoOverlay *_overlayView;
    MPReflectionImageView *_imageView;
    UINavigationBar *_navigationBar;
    MPPortraitTransportControls *_transportControls;
    unsigned int _ownsTransportControls:1;
}

- (id)init;
- (id)initWithTransportControls:(BOOL)fp8;
- (void)dealloc;
- (BOOL)canDisplayItem:(id)fp8 withOrientation:(int)fp12;
- (id)copyOverlayViewForTransitionToItem:(id)fp8;
- (id)createAlternateTracksTransition;
- (id)createChapterFlipTransition;
- (void)displayVideoViewOnScreen;
- (void)loadView;
- (void)restoreOverlayViewAfterTransition:(id)fp8;
- (void)setDesiredParts:(unsigned int)fp8 animate:(BOOL)fp12;
- (void)setDisabledParts:(unsigned int)fp8;
- (void)setVisibleParts:(unsigned int)fp8 animate:(BOOL)fp12;
- (void)startTicking;
- (void)stopTicking;
- (void)viewDidDisappear:(BOOL)fp8;
- (void)showChaptersController;
- (BOOL)ownsTransportControls;
- (void)setItem:(id)fp8;
- (void)setOrientation:(int)fp8 animate:(BOOL)fp12;
- (void)setTVOutEnabled:(BOOL)fp8;
- (BOOL)backstopView:(id)fp8 swipedInDirection:(int)fp12;
- (void)backstopView:(id)fp8 tappedWithCount:(int)fp12;
- (BOOL)transportControls:(id)fp8 tappedButtonPart:(unsigned int)fp12;
- (id)createOverlayViewWithFrame:(struct CGRect)fp8;
- (id)_overlayView;
- (void)_handleSwipeRight;
- (void)_reloadImageView;
- (void)_removeOverlayView;
- (id)navigationBar;
- (void)setNavigationBar:(id)fp8;

@end

