/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIView.h"

@class MediaDetailScrubberControl;

@interface MPProgressIndicator : UIView
{
    MediaDetailScrubberControl *_scrubberControl;
    unsigned int _duration;
    unsigned int _elapsed;
    unsigned int _offset;
    id _delegate;
    BOOL _tracking;
    BOOL _scheduledDelayedCommit;
    double _nextValidUpdateDate;
    double _scheduledDelayedCommitDurationRemaining;
    double _scheduledDelayedCommitSetupTime;
}

+ (float)defaultHeight;
- (id)initWithFrame:(struct CGRect)fp8;
- (void)dealloc;
- (void)_itemChangedNotification:(id)fp8;
- (void)_ignoreElapsedTimeUpdatesForALittleBit:(float)fp8;
- (void)_commitNow;
- (void)_delayedDoCommitNow;
- (void)_commitValue;
- (void)scrubberControl:(id)fp8 didEnterScrubbingState:(BOOL)fp12;
- (void)scrubberControl:(id)fp8 didChangeToScrubValue:(float)fp12;
- (void)cancelTracking;
- (void)setDuration:(unsigned int)fp8;
- (unsigned int)duration;
- (void)setDelegate:(id)fp8;
- (void)setElapsedTime:(unsigned int)fp8 offset:(unsigned int)fp12 force:(BOOL)fp16;

@end

