/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIView.h"

@class NSMutableString, UIImage, UIImageView, UIProgressIndicator, UITextLabel, UITextViewLegacy, UIWebDocumentView;

@interface MPTextView : UIView
{
    id _delegate;
    UIImage *_albumArtwork;
    NSMutableString *_text;
    UIImageView *_background;
    UIImageView *_faderView;
    UIWebDocumentView *_webView;
    UITextViewLegacy *_textView;
    UITextLabel *_loadingLabel;
    UIProgressIndicator *_loadingIndicator;
}

- (id)initWithFrame:(struct CGRect)fp8;
- (void)dealloc;
- (void)layoutSubviews;
- (void)movedToSuperview:(id)fp8;
- (void)movedFromSuperview:(id)fp8;
- (BOOL)hasText;
- (void)noteWillSnapshot;
- (void)noteDidSnapshot;
- (void)setArtwork:(id)fp8;
- (void)setDelegate:(id)fp8;
- (void)setText:(id)fp8 willLoad:(BOOL)fp12;
- (void)view:(id)fp8 handleTapWithCount:(int)fp12 event:(struct __GSEvent *)fp16;
- (double)viewDoubleTapDelay:(id)fp8;
- (double)viewRejectAsTapThrehold:(id)fp8;
- (void)webView:(id)fp8 didFinishLoadForFrame:(id)fp12;
- (void)_addLoadingUI;
- (void)_addTextUI;
- (void)_createTextUIIfNeeded;
- (void)_removeLoadingUI;
- (void)_removeTextUI;
- (struct CGImage *)_createFaderImageBackgroundWithSize:(struct CGSize)fp8;
- (struct CGImage *)_createFaderImage:(BOOL)fp8;
- (void)_updateFaderImage:(BOOL)fp8;

@end

