/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIPushButton.h"

@interface MPTransportPushButton : UIPushButton
{
}

- (id)initWithImage:(id)fp8;
- (BOOL)pointInside:(struct CGPoint)fp8 forEvent:(struct __GSEvent *)fp16;
- (BOOL)pointInside:(struct CGPoint)fp8 withEvent:(id)fp16;
- (struct CGRect)hitRect;

@end

