/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class MPViewController, NSMutableSet, UIView;

@interface MPTransitionController : NSObject
{
    struct __CFDictionary *_observers;
    float _duration;
    UIView *_rootView;
    NSMutableSet *_persistentViewsToFadeOut;
    NSMutableSet *_viewsToFadeOut;
    NSMutableSet *_persistentViewsToFadeIn;
    NSMutableSet *_viewsToFadeIn;
    MPViewController *_fromViewController;
    int _fromOrientation;
    MPViewController *_toViewController;
    int _toOrientation;
}

- (id)init;
- (void)dealloc;
- (void)addObserver:(id)fp8 didEndSelector:(SEL)fp12;
- (void)addViewToFadeIn:(id)fp8 restoreOnPop:(BOOL)fp12;
- (void)addViewToFadeOut:(id)fp8 restoreOnPop:(BOOL)fp12;
- (void)fadeViewsForRestore:(BOOL)fp8;
- (void)removeObserver:(id)fp8;
- (void)transition:(unsigned int)fp8;
- (void)messageObservers;
- (id)toViewController;
- (void)setToViewController:(id)fp8;
- (int)toOrientation;
- (void)setToOrientation:(int)fp8;
- (id)rootView;
- (void)setRootView:(id)fp8;
- (id)fromViewController;
- (void)setFromViewController:(id)fp8;
- (int)fromOrientation;
- (void)setFromOrientation:(int)fp8;
- (float)duration;
- (void)setDuration:(float)fp8;

@end

