/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol MPVideoTransferViewController <NSObject>
- (void)displayVideoView;
- (id)videoView;
- (void)setOwnsVideoView:(BOOL)fp8;
@end

