/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <MediaPlayer/MPPlayingIndicatorTableCell.h>

@class MPTimeMarker;

@interface MPVideoChapterCell : MPPlayingIndicatorTableCell
{
    MPTimeMarker *_marker;
    unsigned int _index;
    float _timeColumnWidth;
    unsigned int _showThumbnailColumn:1;
}

- (id)initWithFrame:(struct CGRect)fp8;
- (void)dealloc;
- (void)drawBackgroundInRect:(struct CGRect)fp8 withFade:(float)fp24;
- (void)drawContentInRect:(struct CGRect)fp8 selected:(BOOL)fp24;
- (void)layoutSubviews;
- (void)setIndex:(unsigned int)fp8;
- (void)setShowThumbnailColumn:(BOOL)fp8;
- (void)setChapterTimeMarker:(id)fp8;
- (void)setTimeColumnWidth:(float)fp8;
- (struct CGPoint)indicatorPoint;
- (void)_addThumbnailIfNecessary:(id)fp8;
- (void)_removeThumbnailIfNecessary:(id)fp8;

@end

