/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <MediaPlayer/MPVideoView.h>

@interface MPVideoView (PlaybackControl)
- (id)mpavController;
- (id)avController;
- (int)bufferingStatusMask;
- (double)currentTime;
- (double)duration;
- (int)playableContentType;
- (int)playbackState;
- (void)pause;
- (void)play;
- (void)setCurrentTime:(double)fp8;
- (void)setRepeatGap:(double)fp8;
- (void)setRepeatMode:(int)fp8;
- (void)stop;
@end

