/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "CALayer.h"

@interface MPVideoBufferLayer : CALayer
{
    unsigned int _animationsEnablesCount;
}

+ (id)defaultValueForKey:(id)fp8;
- (id)actionForKey:(id)fp8;
- (void)enableAnimations;
- (void)disableAnimations;
- (void)display;
- (void)setRenderTransform:(struct CGAffineTransform)fp8;

@end

