/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIImage.h"

@interface UIImage (MusicUtilities)
- (id)imageScaledToSize:(struct CGSize)fp8;
- (id)imageWithRect:(struct CGRect)fp8;
@end

