/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@class MPItem, MPVideoViewController;

@interface UIMoviePlayerController : NSObject
{
    MPItem *_item;
    MPVideoViewController *_videoController;
    struct CGRect _layoutRect;
    id _delegate;
    int _orientation;
    unsigned int _displayableParts;
    unsigned int _desiredParts;
    struct {
        unsigned int canShowControlsOverlay:1;
        unsigned int wantsControlsOverlayVis:1;
        unsigned int wantsControlsOverlayAnim:1;
        unsigned int wantsControlsOverlayDisableAutohide:1;
        unsigned int isFullScreen:1;
        unsigned int canAnimateControlsOverlay:1;
        unsigned int orientationIsForced:1;
        unsigned int autoplayWhenLikelyToKeepUp:1;
        unsigned int externalSourceManagesStatusBar:1;
        unsigned int disallowsVideoOut:1;
        unsigned int exited:1;
        unsigned int unused:22;
    } _mpcBitfield;
}

+ (struct CGSize)fillSizeForMovieBounds:(struct CGRect)fp8 movieNaturalSize:(struct CGSize)fp24 orientation:(int)fp32 destinationTVOut:(BOOL)fp36;
+ (Class)preferredWindowClass;
- (id)initWithPlayerSize:(struct CGSize)fp8 isFullScreen:(BOOL)fp16;
- (void)dealloc;
- (void)unlockMoviePlaybackResources;
- (BOOL)canContinuePlayingWhenLocked;
- (id)delegate;
- (BOOL)disallowsVideoOut;
- (id)movieView;
- (id)playerView;
- (void)setAutoPlayWhenLikelyToKeepUp:(BOOL)fp8;
- (void)setDelegate:(id)fp8;
- (void)setDisallowsVideoOut:(BOOL)fp8;
- (void)setManagesStatusBar:(BOOL)fp8;
- (BOOL)videoOutActive;
- (int)orientation;
- (BOOL)setUIOrientation:(int)fp8 animated:(BOOL)fp12 forced:(BOOL)fp16;
- (void)setDesiredMovieParts:(unsigned int)fp8 animated:(BOOL)fp12;
- (void)setDisplayableMovieParts:(unsigned int)fp8 animated:(BOOL)fp12;
- (void)setDisplayable:(BOOL)fp8 movieParts:(unsigned int)fp12 animated:(BOOL)fp16;
- (void)setCanAnimateControlsOverlay:(BOOL)fp8;
- (void)setCanShowControlsOverlay:(BOOL)fp8;
- (void)setControlsOverlayVisible:(BOOL)fp8 disableAutohide:(BOOL)fp12 animate:(BOOL)fp16;
- (void)layoutUIInRect:(struct CGRect)fp8 fullScreen:(BOOL)fp24;
- (struct CGRect)moviePlaceholderImageRectForMovieWithAspectRatio:(float)fp8;
- (void)prepareAndSetupUI;
- (void)tearDownUI;
- (id)backgroundView;
- (void)viewControllerRequestsExit:(id)fp8 reason:(unsigned int)fp12;
- (BOOL)videoController:(id)fp8 tappedButtonPart:(unsigned int)fp12;
- (void)_pausePlaybackForNotification:(id)fp8;
- (void)_willSuspendNotification:(id)fp8;
- (void)_willBeginSuspendAnimationNotification:(id)fp8;
- (void)_willResignNotification:(id)fp8;
- (void)_willTerminateNotification:(id)fp8;
- (void)_bufferingStateChangedNotification:(id)fp8;
- (void)_itemChangedNotification:(id)fp8;
- (void)_serverDeathNotification:(id)fp8;
- (void)_validityChangedNotification:(id)fp8;
- (unsigned int)_convertedPartsMask:(unsigned int)fp8;
- (void)_exitPlayer:(int)fp8;
- (int)_exitReasonForMPViewControllerExitReason:(unsigned int)fp8;
- (void)_updateEnabledParts;
- (id)_videoController;
- (void)_tvOutCapabilityChanged:(id)fp8;

@end

