/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class AVController, NSString, NSTimer;

@interface VolumeController : NSObject
{
    AVController *_avController;
    id _delegate;
    float _volume;
    float _unmutedVolume;
    NSTimer *_fadeTimer;
    float _fadeVolume;
    NSString *_debugName;
    int _volumeBehaviorWhenEnabled;
    struct {
        unsigned int fadeIncreasesVolume:1;
        unsigned int enabled:1;
        unsigned int isSuspending:1;
        unsigned int shouldPushLocalVolumeToServer:1;
        unsigned int unused:28;
    } _vcBitfields;
}

+ (void)setCurrentVolumeController:(id)fp8;
+ (void)removeCurrentVolumeController:(id)fp8;
+ (void)forgetController:(id)fp8;
+ (id)currentVolumeController;
- (id)init;
- (id)description;
- (void)setDebugName:(id)fp8;
- (void)_postVolumeChangedNotification;
- (void)postCurrentVolumeNotification;
- (void)systemSoundControllerVolumeDidChange:(id)fp8;
- (void)avControllerVolumeDidChange:(id)fp8;
- (void)applicationWillSuspend:(id)fp8;
- (void)applicationDidSuspendOrResume:(id)fp8;
- (void)dealloc;
- (void)setDelegate:(id)fp8;
- (void)setAVController:(id)fp8;
- (void)activateAndPushLocalVolumeToServerIfNecessary;
- (void)_updateAVControllerVolumeBehavior;
- (void)_didOrderOut;
- (void)_didBecomeCurrent;
- (void)setVolumeBehaviorWhenEnabled:(int)fp8;
- (int)volumeBehaviorWhenEnabled;
- (void)setEnabled:(BOOL)fp8;
- (BOOL)isEnabled;
- (void)_setPlayerVolume:(float)fp8;
- (float)_playerVolume;
- (void)toggleMuted;
- (void)setMuted:(BOOL)fp8;
- (BOOL)muted;
- (BOOL)setVolume:(float)fp8;
- (float)volume;
- (void)_stopFade;
- (void)_delayedFadeEndedForDirection:(int)fp8;
- (void)_delayedDidFinishFadeOut;
- (void)_delayedDidFinishFadeIn;
- (void)_handleFadeEvent:(id)fp8;
- (void)_startFade;
- (void)fadeIn;
- (void)fadeOut;

@end

