/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@class UIProgressIndicator;

@interface CameraLoadingView : UIView
{
    UIProgressIndicator *_progressIndicator;
}

- (id)initWithFrame:(struct CGRect)fp8;
- (void)startAnimation;
- (void)stopAnimation;
- (void)drawRect:(struct CGRect)fp8;

@end

