/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <MusicLibrary/MLPhotoAlbum.h>

@class MLPhotoDCIMDirectory;

@interface CameraAlbum : MLPhotoAlbum
{
    MLPhotoDCIMDirectory *_dcimDirectory;
}

+ (id)sharedInstance;
+ (void)clearSharedInstance;
- (id)init;
- (void)dealloc;
- (void)dcimContentsDidChange;
- (id)name;
- (id)images;
- (unsigned int)count;
- (id)posterImage;
- (BOOL)addImage:(id)fp8 withPreview:(id)fp12 exifProperties:(id)fp16 date:(id)fp20 jpegData:(struct __CFData *)fp24;
- (void)deleteImageAtIndex:(int)fp8;

@end

