/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MLPhotoDCFFileGroup.h"

@interface MLPhotoDCFFileGroup (CameraAdditions)
- (int)_orientationForExifProperties:(id)fp8;
- (void)writeJPEG:(id)fp8;
- (void)writeJPEGFinished:(id)fp8;
- (void)setImage:(id)fp8 previewImage:(id)fp12 exifProperties:(id)fp16 date:(id)fp20 jpegData:(struct __CFData *)fp24 completionTarget:(id)fp28 completionSelector:(SEL)fp32 contextInfo:(void *)fp36;
@end

