/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MLPhoto.h"

@interface MLPhoto (PhotosAdditions)
+ (struct CGImage *)createAndSaveIconForWallpaperImage:(id)fp8;
+ (struct CGImage *)createUnrotatedImageWithSize:(struct CGSize)fp8 originalImage:(struct CGImage *)fp16 imageOrientation:(int)fp20;
- (id)thumbnailImage;
- (struct CGImage *)createThumbnailCGImageRef;
- (struct CGImage *)createFullScreenCGImageRef:(int *)fp8 properties:(const struct __CFDictionary **)fp12;
- (struct CGImage *)createFullSizeCGImageRef:(int *)fp8;
- (struct CGImage *)createLowResolutionFullScreenCGImageRef;
- (BOOL)hasFullSizeImage;
@end

