/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Foundation/NSObject.h>

@interface PhotosMusicPlayer : NSObject
{
}

+ (void)startMusicForAlbum:(id)fp8;
+ (void)_setMusicPlaybackState:(int)fp8;
+ (void)stopMusic;
+ (void)pauseMusic;
+ (void)continueMusic;

@end

