/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UINavigationItem.h>

@interface PhotosNavigationItem : UINavigationItem
{
    int _barStyle;
}

- (int)barStyle;
- (void)setBarStyle:(int)fp8;

@end

