/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIScroller.h"

@class NSTimer, UIView;

@interface PLAlbumScroller : UIScroller
{
    BOOL _dragging;
    float _lastX;
    double _lastTimeStamp;
    float _dragSpeed;
    float _grabX;
    struct CGPoint _grabLoc;
    float _mySpeed;
    float _myX;
    float _destinationX;
    NSTimer *_updateTimer;
    int _lastScrollDirection;
    int _lastDragDirection;
    BOOL _shouldAdvance;
    UIView *_leftBackstopView;
    UIView *_rightBackstopView;
    float _slowDownFactor;
}

- (void)dealloc;
- (void)_cancelUpdateTimer;
- (void)_startTimer;
- (BOOL)isScrollingEnabled;
- (BOOL)isSmoothScrolling;
- (BOOL)isDragging;
- (int)lastScrollDirection;
- (BOOL)shouldAdvance;
- (BOOL)_alwaysHandleInteractionEvents;
- (void)mouseDown:(struct __GSEvent *)fp8;
- (void)_updateDragInfoWithTimeInterval:(double)fp8 event:(struct __GSEvent *)fp16 smoothScrolling:(BOOL)fp20;
- (void)_updateScrollWithTimeInterval:(double)fp8;
- (void)_updateTimerFired:(id)fp8;
- (void)mouseDragged:(struct __GSEvent *)fp8;
- (void)mouseUp:(struct __GSEvent *)fp8;
- (void)contentMouseUpInView:(id)fp8 withEvent:(struct __GSEvent *)fp12;
- (void)_releaseDrag;
- (void)setScrollingEnabled:(BOOL)fp8;
- (id)hitTest:(struct CGPoint)fp8 forEvent:(struct __GSEvent *)fp16;
- (void)setContentSize:(struct CGSize)fp8;
- (void)setOffset:(struct CGPoint)fp8;
- (void)_doScrollToOffset:(struct CGPoint)fp8 animate:(BOOL)fp16;
- (void)ensureOffsetToImageBoundary;
- (void)scrollToNextImageWithAnimation:(BOOL)fp8 offset:(struct CGPoint)fp12;
- (void)scrollToPreviousImageWithAnimation:(BOOL)fp8 offset:(struct CGPoint)fp12;
- (void)gestureStarted:(struct __GSEvent *)fp8;
- (void)gestureEnded:(struct __GSEvent *)fp8;
- (void)gestureChanged:(struct __GSEvent *)fp8;

@end

