/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MLPhoto.h"

@class MLPhotoDCFFileGroup;

@interface PLCameraImage : MLPhoto
{
    MLPhotoDCFFileGroup *_fileGroup;
}

+ (void)setMaxImageSize:(int)fp8;
+ (int)imageIDForFileGroup:(id)fp8;
- (id)initWithDCFFileGroup:(id)fp8;
- (void)dealloc;
- (id)fileGroup;
- (void)fileGroupWillBeginSaving:(id)fp8;
- (void)fileGroupDidFinishSaving:(id)fp8;
- (int)compare:(id)fp8;
- (id)description;
- (id)thumbnailImage;
- (struct CGImage *)_createCGImageForFormat:(int)fp8 orientation:(int *)fp12 ignoringSizeCaps:(BOOL)fp16 properties:(const struct __CFDictionary **)fp20;
- (struct CGImage *)createFullScreenCGImageRef:(int *)fp8 properties:(const struct __CFDictionary **)fp12;
- (struct CGImage *)createFullSizeCGImageRef:(int *)fp8;
- (struct CGImage *)createLowResolutionFullScreenCGImageRef;
- (BOOL)hasFullSizeImage;
- (void)deleteFiles;

@end

