/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MLPhotoAlbum.h"

@class MLPhotoDCIMDirectory;

@interface PLCameraAlbum : MLPhotoAlbum
{
    MLPhotoDCIMDirectory *_dcimDirectory;
}

+ (id)sharedInstance;
+ (void)clearSharedInstance;
- (id)init;
- (void)dealloc;
- (void)dcimContentsDidChange;
- (id)name;
- (id)images;
- (unsigned int)count;
- (id)posterImage;
- (BOOL)_addImage:(id)fp8 withPreview:(id)fp12 exifProperties:(id)fp16 date:(id)fp20 jpegData:(struct __CFData *)fp24 notifyingTarget:(id)fp28 selector:(SEL)fp32 contextInfo:(void *)fp36 sendPath:(BOOL)fp40;
- (BOOL)addImage:(id)fp8 withPreview:(id)fp12 exifProperties:(id)fp16 date:(id)fp20 jpegData:(struct __CFData *)fp24 notifyingTarget:(id)fp28 selector:(SEL)fp32 contextInfo:(void *)fp36;
- (BOOL)addImage:(id)fp8 withPreview:(id)fp12 exifProperties:(id)fp16 date:(id)fp20 jpegData:(struct __CFData *)fp24 notifyingTargetWithPath:(id)fp28 selector:(SEL)fp32;
- (void)deleteImageAtIndex:(int)fp8;
- (void)cameraImageFinishedSaving:(id)fp8;

@end

