/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIView.h"

@class NSString;

@interface PLCropLCDLayer : UIView
{
    NSString *_subtitle;
    NSString *_title;
}

- (void)dealloc;
- (void)setTitle:(id)fp8;
- (id)title;
- (void)setSubtitle:(id)fp8;
- (void)drawRect:(struct CGRect)fp8;

@end

