/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <PhotoLibrary/PLCropOverlay.h>

@interface PLCropOverlay (PhotoSaving)
- (void)beginBackgroundSaveWithTile:(id)fp8 progressTitle:(id)fp12 completionCallbackTarget:(id)fp16 options:(int)fp20;
- (void)_backgroundSavePhoto:(id)fp8;
- (void)_savePhotoFinished:(id)fp8;
@end

