/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UITile.h"

@interface PLImageViewTile : UITile
{
}

- (void)_adjustContents;
- (BOOL)_canDrawContent;
- (void)movedToSuperview:(id)fp8;
- (void)setFrame:(struct CGRect)fp8;

@end

