/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@interface PLImageLoader : NSObject
{
}

+ (void)_imageLoader;
+ (void)pauseLoading;
+ (void)resumeLoading;
+ (void)_finishedLoadingImageRef:(id)fp8;
+ (void)_finishDeferredImageLoads;
+ (void)stop;
+ (void)loadFullSizeImageRefForImageView:(id)fp8;
+ (void)cancelLoadRequestsForImageView:(id)fp8;

@end

