/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIViewController.h"

@class PLPhotoLibrary;

@interface PLLibraryViewController : UIViewController
{
    PLPhotoLibrary *_library;
    struct {
        unsigned int albumsInvalid:1;
        unsigned int visible:1;
        unsigned int reserved:30;
    } _libraryControllerFlags;
}

- (id)init;
- (void)dealloc;
- (void)loadView;
- (id)_library;
- (void)_updateAlbumsIfNecessary;
- (void)iTunesSyncRequestedStart;
- (void)iTunesSyncHasCompleted:(int)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (void)viewDidDisappear:(BOOL)fp8;
- (void)cancelButtonClicked:(id)fp8;
- (void)libraryView:(id)fp8 didSelectAlbum:(id)fp12;

@end

