/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

#import "CLLocationManagerDelegate-Protocol.h"

@class CLLocationManager, NSMutableArray;

@interface PLLocationController : NSObject <CLLocationManagerDelegate>
{
    CLLocationManager *_locationManager;
    int _managerRefCount;
    NSMutableArray *_locationPendingPaths;
}

+ (id)sharedInstance;
- (void)dealloc;
- (void)start;
- (void)stop;
- (BOOL)isRunning;
- (id)location;
- (id)locationEXIFDictionary;
- (void)addLocationToImageAtPathWhenAvailable:(id)fp8;
- (void)_updatePendingImagePaths;
- (void)locationManager:(id)fp8 didUpdateToLocation:(id)fp12 fromLocation:(id)fp16;

@end

