/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIToolbar.h"

@interface PLPhotosButtonBar : UIToolbar
{
}

+ (id)backgroundImage;
+ (float)defaultHeight;
- (id)initInView:(id)fp8 withItems:(CDAnonymousStruct1 *)fp12 withCount:(int)fp16;
- (void)drawRect:(struct CGRect)fp8;

@end

