/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MLPhotoLibrary.h"

@interface PLPhotoLibrary : MLPhotoLibrary
{
}

+ (id)sharedPhotoLibrary;
+ (id)photosDirectory;
+ (struct CGImage *)createThumbnailOfImage:(struct CGImage *)fp8 format:(int)fp12 atPath:(id)fp16;
+ (struct CGImage *)createThumbnailOfImage:(struct CGImage *)fp8 format:(int)fp12 atPath:(id)fp16 orientation:(int)fp20;
+ (struct CGImage *)createThumbnailOfImage:(struct CGImage *)fp8 format:(int)fp12 atPath:(id)fp16 orientation:(int)fp20 thumbnailDataOut:(id *)fp24;
- (id)init;
- (void)dealloc;
- (struct CGImage *)createCGImageForDulcimerImage:(id)fp8 format:(int)fp12;
- (id)imageForFormat:(int)fp8 forImage:(id)fp12;
- (id)albums;
- (id)posterImageForAlbum:(id)fp8;
- (void)_cameraAlbumContentsChanged:(id)fp8;

@end

