/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UITableCell.h"

@class NSMutableArray, UIImage, UIView;

@interface PLThumbnailTableCell : UITableCell
{
    NSMutableArray *_slideImages;
    UIImage *_image;
    struct CGImage *_cgImage;
    UIView *_highlightView;
    int _highlightPhoto;
    BOOL _trackingHighlight;
}

- (id)initWithSize:(struct CGSize)fp8;
- (void)dealloc;
- (id)selectedImage;
- (id)slideImageAtIndex:(unsigned int)fp8;
- (void)setSlideImage:(id)fp8 atIndex:(unsigned int)fp12;
- (void)setImage:(id)fp8;
- (void)setNeedsDisplay;
- (void)setNeedsDisplayInRect:(struct CGRect)fp8;
- (void)setImageRef:(struct CGImage *)fp8;
- (BOOL)_canDrawContent;
- (void)drawContentInRect:(struct CGRect)fp8 selected:(BOOL)fp24;
- (void)_updateSelectedColumnWithEvent:(struct __GSEvent *)fp8;
- (void)mouseDown:(struct __GSEvent *)fp8;
- (void)mouseUp:(struct __GSEvent *)fp8;
- (void)mouseDragged:(struct __GSEvent *)fp8;
- (void)touchesBegan:(id)fp8 withEvent:(id)fp12;
- (void)touchesMoved:(id)fp8 withEvent:(id)fp12;
- (void)touchesEnded:(id)fp8 withEvent:(id)fp12;
- (void)setSelected:(BOOL)fp8 withFade:(BOOL)fp12;
- (void)setBackgroundColor:(id)fp8;

@end

