/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UITable.h>

@class UITableCell;

@interface SelectableTable : UITable
{
    BOOL _allowsCellSelection;
    UITableCell *_selectedCell;
}

- (BOOL)_canDrawContent;
- (void)dealloc;
- (void)setAllowsCellSelection:(BOOL)fp8;
- (void)selectRow:(int)fp8 byExtendingSelection:(BOOL)fp12;
- (void)highlightView:(id)fp8 state:(BOOL)fp12;

@end

