/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@class UIImageView;

@interface SyncProgressView : UIView
{
    UIImageView *_icon;
}

- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)fp8;
- (void)dealloc;

@end

