/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@class PLImageScroller;

@interface TransitionContainerView : UIView
{
    PLImageScroller *_scroller;
}

- (id)scroller;
- (void)setRotationView:(id)fp8 scroller:(id)fp12;

@end

