/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIView.h"

@interface UIView (PhotosCGPathUtilities)
+ (void)calculateControlPointsFromMidpoint:(struct CGPoint)fp8 toMidpoint:(struct CGPoint)fp16 controlPoint1:(struct CGPoint *)fp24 controlPoint2:(struct CGPoint *)fp28;
+ (void)addCurveToPath:(struct CGPath *)fp8 fromRect:(struct CGRect)fp12 toRect:(struct CGRect)fp28 swapControlPoints:(BOOL)fp44;
@end

