/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <WebKit/WebPreferences.h>

@interface WebPreferences (WebPrivate)
+ (id)_getInstanceForIdentifier:(id)fp8;	// IMP=0x332caf00
+ (void)_setInstance:(id)fp8 forIdentifier:(id)fp12;	// IMP=0x332caf5c
+ (void)_checkLastReferenceForIdentifier:(id)fp8;	// IMP=0x332dea88
+ (void)_removeReferenceForIdentifier:(id)fp8;	// IMP=0x332da904
+ (unsigned long)_systemCFStringEncoding;	// IMP=0x332e2f0c
+ (void)_setInitialDefaultTextEncodingToSystemEncoding;	// IMP=0x332e2e50
+ (void)_setIBCreatorID:(id)fp8;	// IMP=0x33329440
- (BOOL)developerExtrasEnabled;	// IMP=0x332d15f4
- (void)setDeveloperExtrasEnabled:(BOOL)fp8;	// IMP=0x33329658
- (BOOL)authorAndUserStylesEnabled;	// IMP=0x332d16bc
- (void)setAuthorAndUserStylesEnabled:(BOOL)fp8;	// IMP=0x3332962c
- (BOOL)applicationChromeModeEnabled;	// IMP=0x332d16e8
- (void)setApplicationChromeModeEnabled:(BOOL)fp8;	// IMP=0x33329600
- (BOOL)webArchiveDebugModeEnabled;	// IMP=0x332d18c8
- (void)setWebArchiveDebugModeEnabled:(BOOL)fp8;	// IMP=0x333295d4
- (BOOL)offlineWebApplicationCacheEnabled;	// IMP=0x332d18f4
- (void)setOfflineWebApplicationCacheEnabled:(BOOL)fp8;	// IMP=0x332da684
- (BOOL)zoomsTextOnly;	// IMP=0x332d1920
- (void)setZoomsTextOnly:(BOOL)fp8;	// IMP=0x333295a8
- (BOOL)automaticallyDetectsCacheModel;	// IMP=0x33329300
- (void)setAutomaticallyDetectsCacheModel:(BOOL)fp8;	// IMP=0x332e2e2c
- (double)_backForwardCacheExpirationInterval;	// IMP=0x33329558
- (unsigned long)_maximumImageSize;	// IMP=0x332d1788
- (long long)_maximumResourceDataLength;	// IMP=0x332d1714
- (BOOL)_standalone;	// IMP=0x332d175c
- (void)_setStandalone:(BOOL)fp8;	// IMP=0x3332952c
- (void)_setTelephoneNumberParsingEnabled:(BOOL)fp8;	// IMP=0x332db050
- (BOOL)_telephoneNumberParsingEnabled;	// IMP=0x332d17cc
- (void)_setMinimumZoomFontSize:(float)fp8;	// IMP=0x332e3a48
- (float)_minimumZoomFontSize;	// IMP=0x332d17f8
- (void)_setLayoutInterval:(int)fp8;	// IMP=0x332e3a20
- (int)_layoutInterval;	// IMP=0x332d1878
- (void)_setMaxParseDuration:(float)fp8;	// IMP=0x33329504
- (float)_maxParseDuration;	// IMP=0x332d18a0
- (int)editableLinkBehavior;	// IMP=0x332d1468
- (void)setEditableLinkBehavior:(int)fp8;	// IMP=0x333294dc
- (int)textDirectionSubmenuInclusionBehavior;	// IMP=0x332d14f0
- (void)setTextDirectionSubmenuInclusionBehavior:(int)fp8;	// IMP=0x333294b4
- (BOOL)_useSiteSpecificSpoofing;	// IMP=0x332d10ec
- (void)_setUseSiteSpecificSpoofing:(BOOL)fp8;	// IMP=0x33329488
- (BOOL)databasesEnabled;	// IMP=0x332d136c
- (void)setDatabasesEnabled:(BOOL)fp8;	// IMP=0x332da62c
- (BOOL)localStorageEnabled;	// IMP=0x332d1398
- (void)setLocalStorageEnabled:(BOOL)fp8;	// IMP=0x332da658
- (void)_postPreferencesChangesNotification;	// IMP=0x332cb00c
- (BOOL)isDOMPasteAllowed;	// IMP=0x332d1538
- (void)setDOMPasteAllowed:(BOOL)fp8;	// IMP=0x33329414
- (void)_setFTPDirectoryTemplatePath:(id)fp8;	// IMP=0x333293c8
- (id)_localStorageDatabasePath;	// IMP=0x332cca80
- (void)_setLocalStorageDatabasePath:(id)fp8;	// IMP=0x3332937c
- (id)_ftpDirectoryTemplatePath;	// IMP=0x332d1234
- (void)_setForceFTPDirectoryListings:(BOOL)fp8;	// IMP=0x33329350
- (BOOL)_forceFTPDirectoryListings;	// IMP=0x332d1208
- (void)didRemoveFromWebView;	// IMP=0x332daa20
- (void)willAddToWebView;	// IMP=0x332cbeb8
- (void)setFullDocumentTeardownEnabled:(BOOL)fp8;	// IMP=0x33329324
- (BOOL)fullDocumentTeardownEnabled;	// IMP=0x332dc76c
- (void)_invalidateCachedPreferences;	// IMP=0x332e3e4c
@end

