/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIControl.h"

@class NSString, SlicedImageView, UITextLabel;

@interface AddressAtom : UIControl
{
    CDAnonymousStruct2 _atomImageSlices;
    SlicedImageView *_leftCap;
    SlicedImageView *_rightCap;
    SlicedImageView *_center;
    UITextLabel *_addressLabel;
    id _delegate;
    NSString *_fullAddress;
    void *_person;
    NSString *_displayString;
    struct CGPoint _displayStringOrigin;
    unsigned int _maxWidth;
    int _identifier;
    unsigned int _addressIsPhoneNumber:1;
    unsigned int _needsToSendMouseUpEvents:1;
    unsigned int _dragging:1;
    unsigned int _updatedABPerson:1;
}

+ (void)initialize;
- (void)_registerForNotifications;
- (void)_unregisterForNotifications;
- (id)initWithAddress:(id)fp8 isPhoneNumber:(BOOL)fp12 maxWidth:(float)fp16 useDisplayString:(BOOL)fp20;
- (void)setDelegate:(id)fp8;
- (void)mouseUp:(struct __GSEvent *)fp8;
- (void)mouseDragged:(struct __GSEvent *)fp8;
- (void)sendAction:(SEL)fp8 toTarget:(id)fp12 forEvent:(struct __GSEvent *)fp16;
- (void)dealloc;
- (void)setFrame:(struct CGRect)fp8;
- (void)sizeToFit;
- (void)_updateABPerson;
- (void)_addressBookRecordDidChange;
- (void)_updateDisplayStringIncludingABPerson:(BOOL)fp8;
- (void *)ABPerson;
- (int)identifier;
- (id)unmodifiedAddressString;
- (id)displayString;
- (void)setHighlighted:(BOOL)fp8;
- (BOOL)_alwaysHandleScrollerMouseEvent;

@end

