/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIDefaultKeyboardInput.h"

@class AtomBackgroundView, UILabel;

@interface AtomView : UIDefaultKeyboardInput
{
    AtomBackgroundView *_background;
    UILabel *_label;
    id _delegate;
    unsigned int _disclosure:1;
    unsigned int _needsCentering:1;
    float _width;
}

+ (id)backgroundImageWithDisclosure:(BOOL)fp8 selected:(BOOL)fp12;
+ (CDAnonymousStruct2)backgroundImageSlicesWithDisclosure:(BOOL)fp8;
+ (float)defaultHeight;
+ (float)horizontalPadding;
- (id)initWithFrame:(struct CGRect)fp8;
- (void)dealloc;
- (id)title;
- (void)setTitle:(id)fp8;
- (float)preferredWidth;
- (void)setShowsDisclosure:(BOOL)fp8;
- (BOOL)selected;
- (void)setSelected:(BOOL)fp8;
- (void)showBackground:(BOOL)fp8;
- (void)layoutSubviews;

@end

