/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

struct CGColor;

struct CGPoint {
    float x;
    float y;
};

struct CGRect {
    struct CGPoint origin;
    struct CGSize size;
};

struct CGSize {
    float width;
    float height;
};

struct _NSRange {
    unsigned int location;
    unsigned int length;
};

struct _NSZone;

struct __CFArray;

struct __CFDictionary;

struct __GSEvent;

typedef struct {
    unsigned int :1;
    unsigned int :1;
    unsigned int :1;
} CDAnonymousStruct1;

typedef struct {
    struct CGRect left;
    struct CGRect middle;
    struct CGRect right;
} CDAnonymousStruct2;

