/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <MessageUI/ComposeHeaderView.h>

@class UIImageView, UITextLabel;

@interface ComposeFromView : ComposeHeaderView
{
    UITextLabel *_accountLabel;
    UIImageView *_background;
}

- (id)initWithFrame:(struct CGRect)fp8;
- (void)dealloc;
- (void)layoutSubviews;
- (id)_accountLabel;
- (void)setAccountLabel:(id)fp8;
- (void)setLabelHighlighted:(BOOL)fp8;

@end

