/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <MessageUI/ComposeHeaderView.h>

@class UILabel;

@interface ComposeMultiView : ComposeHeaderView
{
    UILabel *_accountLabel;
}

- (void)dealloc;
- (id)accountLabel;
- (void)setAccountDescription:(id)fp8;
- (void)layoutSubviews;

@end

