/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <MessageUI/ComposeHeaderView.h>

#import "UITextFieldDelegate-Protocol.h"

@class UITextField;

@interface ComposeSubjectView : ComposeHeaderView <UITextFieldDelegate>
{
    UITextField *_textField;
    unsigned int _delegateRespondsToTextChange:1;
}

- (id)initWithFrame:(struct CGRect)fp8;
- (BOOL)becomeFirstResponder;
- (void)textFieldDidResignFirstResponder:(id)fp8;
- (id)text;
- (void)setText:(id)fp8;
- (void)setDelegate:(id)fp8;
- (void)textChanged:(id)fp8;
- (BOOL)keyboardInput:(id)fp8 shouldInsertText:(id)fp12 isMarkedText:(BOOL)fp16;
- (id)keyboardInputOverlayContainer:(id)fp8;
- (BOOL)endEditing:(BOOL)fp8;
- (void)dealloc;
- (BOOL)_canBecomeFirstResponder;

@end

