/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <MessageUI/AtomView.h>

@class ComposeRecipient, UITextInputTraits;

@interface ComposeRecipientAtom : AtomView
{
    ComposeRecipient *_recipient;
    UITextInputTraits *_traits;
}

- (id)initWithFrame:(struct CGRect)fp8 recipient:(id)fp24;
- (void)dealloc;
- (id)title;
- (void)setDelegate:(id)fp8;
- (void)mouseUp:(struct __GSEvent *)fp8;
- (void)setMarkedText:(id)fp8;
- (void)deleteBackward;
- (BOOL)canBecomeFirstResponder;
- (BOOL)becomeFirstResponder;
- (id)textInputTraits;
- (BOOL)canResignFirstResponder;
- (BOOL)resignFirstResponder;

@end

