/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString;

@interface ComposeRecipient : NSObject
{
    int _identifier;
    int _uid;
    NSString *_address;
}

+ (id)recipientWithAddress:(id)fp8;
+ (id)recipientWithRecord:(void *)fp8 identifier:(int)fp12;
+ (id)_abFindAddressForRecord:(void *)fp8 identifier:(int)fp12;
+ (void *)_abFindRecordForAddress:(id)fp8 identifier:(int *)fp12 uniqueID:(int *)fp16;
+ (int)_recipientABProperty;
- (id)initWithRecord:(void *)fp8 identifier:(int)fp12 address:(id)fp16;
- (void *)record;
- (id)address;
- (id)commentedAddress;
- (id)label;
- (void)setAddress:(id)fp8;
- (int)identifier;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (void)dealloc;
- (id)displayString;
- (id)uncommentedAddress;

@end

