/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIView.h"

@class NSString;

@interface HeaderLabelView : UIView
{
    NSString *_label;
    unsigned int _highlighted:1;
}

- (struct CGColor *)labelColor;
- (void)drawRect:(struct CGRect)fp8;

@end

