/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class Message, MessageViewingContext, NSString, NSURL;

@interface MailCompositionContext : NSObject
{
    int _composeType;
    Message *_originalMessage;
    NSString *_sendingAddress;
    NSURL *_url;
    id _originalContent;
    MessageViewingContext *_loadingContext;
    unsigned int _loadRest:1;
    unsigned int _includeAttachments:1;
}

- (id)initWithComposeType:(int)fp8;
- (id)initWithComposeType:(int)fp8 originalMessage:(id)fp12;
- (id)initReplyToMessage:(id)fp8;
- (id)initReplyAllToMessage:(id)fp8;
- (id)initForwardOfMessage:(id)fp8;
- (id)initDraftRestoreOfMessage:(id)fp8;
- (id)initNewMessageWithURL:(id)fp8;
- (void)dealloc;
- (id)loadingContext;
- (void)setLoadingContext:(id)fp8;
- (id)originalMessage;
- (id)url;
- (id)originalContent;
- (void)setOriginalContent:(id)fp8;
- (id)sendingAddress;
- (void)setSendingAddress:(id)fp8;
- (int)composeType;
- (BOOL)loadRest;
- (void)setLoadRest:(BOOL)fp8;
- (BOOL)includeAttachments;
- (void)setIncludeAttachments:(BOOL)fp8;

@end

