/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

@protocol MailComposeViewDelegate
- (void)selectCurrentEntryForPickerView:(id)fp8;
- (id)runDASearchIfNecessary:(id)fp8;
- (void)cancelSearchQuery:(id)fp8;
@end

