/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIWebDocumentView.h"

@interface MessageWebLayer : UIWebDocumentView
{
}

+ (void)initialize;
- (id)initWithFrame:(struct CGRect)fp8 visibleSize:(struct CGSize)fp24;
- (void)defaultMouseDragged:(struct __GSEvent *)fp8;
- (void)webView:(id)fp8 decidePolicyForNewWindowAction:(id)fp12 request:(id)fp16 newFrameName:(id)fp20 decisionListener:(id)fp24;
- (void)webView:(id)fp8 decidePolicyForNavigationAction:(id)fp12 request:(id)fp16 frame:(id)fp20 decisionListener:(id)fp24;
- (void)notifyDelegateToLoad:(id)fp8 client:(id)fp12;
- (void)notifyDelegateToDisplayInSeparateView:(id)fp8;
- (void)loadHTMLString:(id)fp8 baseURL:(id)fp12;
- (void)_sendDelegateSizeDidChange;
- (void)setFrame:(struct CGRect)fp8;
- (void)appendMarkupString:(id)fp8 baseURL:(id)fp12;
- (void)_updateImageURL:(id)fp8 withURL:(id)fp12 width:(id)fp16;
- (void)updateImageURL:(id)fp8 withURL:(id)fp12 width:(float)fp16;
- (void)_updateInlinePluginWithContentID:(id)fp8 htmlRepresentation:(id)fp12;
- (void)updateInlinePluginWithContentID:(id)fp8 htmlRepresentation:(id)fp12;
- (id)webView:(id)fp8 identifierForInitialRequest:(id)fp12 fromDataSource:(id)fp16;
- (id)webView:(id)fp8 resource:(id)fp12 willSendRequest:(id)fp16 redirectResponse:(id)fp20 fromDataSource:(id)fp24;
- (void)webView:(id)fp8 resource:(id)fp12 didFinishLoadingFromDataSource:(id)fp16;
- (void)webView:(id)fp8 resource:(id)fp12 didFailLoadingWithError:(id)fp16 fromDataSource:(id)fp20;
- (void)webView:(id)fp8 didStartProvisionalLoadForFrame:(id)fp12;
- (void)adjustSizeBasedOnMainFrame:(id)fp8;
- (void)webView:(id)fp8 didFinishLoadForFrame:(id)fp12;
- (void)fixParagraphsAndQuotesFromMicrosoft;
- (void)setSuperviewBackgroundColor:(id)fp8;
- (void)_urlifyMessage:(id)fp8;
- (void)_replaceURLifiedPieces:(id)fp8;
- (void)_webthread_webView:(id)fp8 didFinishLoadForFrame:(id)fp12;

@end

