/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class ActivityMonitor, Message, MessageBody, MimePart;

@interface MessageViewingContext : NSObject
{
    Message *_message;
    MessageBody *_body;
    id _content;
    unsigned int _contentOffset;
    id _delegate;
    ActivityMonitor *_loadTask;
    unsigned int _loadIncrement;
    BOOL _loadBestAlternative;
    MimePart *_loadedPart;
    BOOL _loadedFullData;
    unsigned int _hasNoContent:1;
    unsigned int _isOutgoingMessage:1;
}

- (id)initWithMessage:(id)fp8;
- (void)dealloc;
- (BOOL)hasLoaded;
- (BOOL)isPartial;
- (void)cancelLoad;
- (void)setLoadTask:(id)fp8;
- (id)loadTask;
- (void)setDelegate:(id)fp8;
- (void)setContent:(id)fp8;
- (id)content;
- (BOOL)hasNoContent;
- (id)message;
- (BOOL)isOutgoingMessage;
- (void)setOutgoingMessage:(BOOL)fp8;
- (void)setContentOffset:(unsigned int)fp8;
- (unsigned int)contentOffset;
- (id)messageBody;
- (void)setMessageBody:(id)fp8;
- (id)fileWrappersForImageAttachments;
- (unsigned int)numberOfImageAttachments;
- (void)_loadAttachments:(id)fp8;
- (void)loadAsPlainText:(BOOL)fp8 asHTML:(BOOL)fp12;
- (void)loadFull;
- (void)loadWithPriority:(int)fp8;
- (void)load;
- (void)abortAttachmentLoad:(id)fp8 pluginClient:(id)fp12;
- (void)loadAttachment:(id)fp8 pluginClient:(id)fp12;
- (void)loadMore;
- (void)loadBestAlternative;
- (void)setLoadedPart:(id)fp8;
- (id)loadedPart;
- (void)_notifyInitialLoadComplete;
- (void)_notifyAttachmentComplete:(id)fp8;
- (void)_notifyCompletelyComplete;

@end

