/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSArray.h"

@interface NSArray (RecipientListStrings)
- (id)commaSeparatedRecipientListWithWidth:(float)fp8 forFont:(id)fp12;
- (id)commaSeparatedRecipientListWithWidth:(float)fp8 forFont:(id)fp12 usingSelector:(SEL)fp16;
@end

