/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@interface SoundController : NSObject
{
}

+ (BOOL)_shouldPlaySound:(id)fp8;
+ (void)preheatSounds;
+ (void)playNewMailSound;
+ (void)playSentMailSound;
- (id)init;
- (void)dealloc;

@end

