/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSLock;

@interface WebKitMainThread : NSObject
{
    struct __CFDictionary *_visibleDict;
    NSLock *_visibleDictLock;
}

+ (id)sharedInstance;
- (id)init;
- (void)dealloc;
- (void)_mainThreadPopulateDictForMimeType:(id)fp8;
- (int)dictValueForMimeType:(id)fp8;

@end

